easy_log_slots = [
{'taskName' : 'Get bolt racks from Barrows', 'category' : 'Bosses', 'logName' : 'Barrows Chests',  'include' : {'Bolt rack'}, 'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get a Mole claw + skin', 'category' : 'Bosses', 'logName' : 'Giant Mole',  'include' : {'Mole skin', 'Mole claw'}, 'db_count' : 2, 'log_count' : 0},
{'taskName' : 'Get 1 Unique from Wintertodt', 'category' : 'Bosses', 'logName' : 'Wintertodt',  'exclude' : {'Phoenix', 'Dragon axe'}, 'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get 1 Unique from Wintertodt', 'category' : 'Bosses', 'logName' : 'Wintertodt',  'exclude' : {'Phoenix', 'Dragon axe'}, 'db_count' : 2, 'log_count' : 0},
{'taskName' : 'Get 1 Unique from Wintertodt', 'category' : 'Bosses', 'logName' : 'Wintertodt',  'exclude' : {'Phoenix', 'Dragon axe'}, 'db_count' : 3, 'log_count' : 0},
{'taskName' : 'Get 1 Unique from Wintertodt', 'category' : 'Bosses', 'logName' : 'Wintertodt',  'exclude' : {'Phoenix', 'Dragon axe'}, 'db_count' : 4, 'log_count' : 0},
{'taskName' : 'Get 1 Unique from Wintertodt', 'category' : 'Bosses', 'logName' : 'Wintertodt',  'exclude' : {'Phoenix', 'Dragon axe'}, 'db_count' : 5, 'log_count' : 0},
{'taskName' : 'Get 3 new uniques from beginner clues', 'category' : 'Clues', 'logName' : 'Beginner Treasure Trails',  'exclude' : {'Black pickaxe'}, 'db_count' : 3, 'log_count' : 0},
{'taskName' : 'Get 3 new uniques from beginner clues', 'category' : 'Clues', 'logName' : 'Beginner Treasure Trails',  'exclude' : {'Black pickaxe'}, 'db_count' : 6, 'log_count' : 0},
{'taskName' : 'Get 5 new uniques from easy clues', 'category' : 'Clues', 'logName' : 'Easy Treasure Trails', 'exclude': {'N/A'},'db_count' : 5, 'log_count' : 0},
{'taskName' : 'Get 5 new uniques from easy clues', 'category' : 'Clues', 'logName' : 'Easy Treasure Trails', 'exclude': {'N/A'},'db_count' : 10, 'log_count' : 0},
{'taskName' : 'Get 5 new uniques from easy clues', 'category' : 'Clues', 'logName' : 'Easy Treasure Trails', 'exclude': {'N/A'},'db_count' : 15, 'log_count' : 0},
{'taskName' : 'Get 5 new uniques from easy clues', 'category' : 'Clues', 'logName' : 'Easy Treasure Trails', 'exclude': {'N/A'},'db_count' : 20, 'log_count' : 0},
{'taskName' : 'Get 5 new uniques from easy clues', 'category' : 'Clues', 'logName' : 'Easy Treasure Trails', 'exclude': {'N/A'},'db_count' : 25, 'log_count' : 0},
{'taskName' : 'Get 5 new uniques from easy clues', 'category' : 'Clues', 'logName' : 'Easy Treasure Trails', 'exclude': {'N/A'},'db_count' : 30, 'log_count' : 0},
{'taskName' : 'Get 5 new uniques from medium clues', 'category' : 'Clues', 'logName' : 'Medium Treasure Trails', 'exclude': {'N/A'}, 'count': 5, 'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get 5 new uniques from medium clues', 'category' : 'Clues', 'logName' : 'Medium Treasure Trails', 'exclude': {'N/A'}, 'count': 10, 'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get 5 new uniques from medium clues', 'category' : 'Clues', 'logName' : 'Medium Treasure Trails', 'exclude': {'N/A'}, 'count': 15, 'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get 5 new uniques from medium clues', 'category' : 'Clues', 'logName' : 'Medium Treasure Trails', 'exclude': {'N/A'}, 'count': 20, 'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get 5 new uniques from hard clues', 'category' : 'Clues', 'logName' : 'Hard Treasure Trails', 'exclude': {'N/A'}, 'count': 5, 'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get 5 new uniques from hard clues', 'category' : 'Clues', 'logName' : 'Hard Treasure Trails', 'exclude': {'N/A'}, 'count': 10, 'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get Runner boots', 'category' : 'Minigames', 'logName' : 'Barbarian Assault',  'include' : {'Runner boots'}, 'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get Penance gloves', 'category' : 'Minigames', 'logName' : 'Barbarian Assault',  'include' : {'Penance gloves'}, 'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get a Granite body', 'category' : 'Minigames', 'logName' : 'Barbarian Assault',  'include' : {'Granite body'}, 'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get 1 new halo', 'category' : 'Minigames', 'logName' : 'Castle Wars',  'include' : {'Saradomin halo', 'Zamorak halo', 'Guthix halo'}, 'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get the full Red decorative set', 'category' : 'Minigames', 'logName' : 'Castle Wars', 'include' : {'Decorative helm', 'Decorative full helm', 'Decorative armour', 'Decorative sword', 'Decorative shield', 'Decorative boots'},'db_count' : 8, 'log_count' : 0},
{'taskName' : 'Get the Zamorak hood & cloak', 'category' : 'Minigames', 'logName' : 'Castle Wars', 'include' : {'Castlewars hood', 'Castlewars cloak'}, 'db_count' : 2, 'log_count' : 0},
{'taskName' : 'Get the Saradomin hood & cloak', 'category' : 'Minigames', 'logName' : 'Castle Wars', 'include' : {'Castlewars hood', 'Castlewars cloak'}, 'db_count' : 4, 'log_count' : 0},
{'taskName' : 'Get 1 Angler piece', 'category' : 'Minigames', 'logName' : 'Fishing Trawler','exclude': {'N/A'}, 'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get 1 Angler piece', 'category' : 'Minigames', 'logName' : 'Fishing Trawler','exclude': {'N/A'}, 'db_count' : 2, 'log_count' : 0},
{'taskName' : 'Get 1 Angler piece', 'category' : 'Minigames', 'logName' : 'Fishing Trawler','exclude': {'N/A'}, 'db_count' : 3, 'log_count' : 0},
{'taskName' : 'Get 1 Angler piece', 'category' : 'Minigames', 'logName' : 'Fishing Trawler','exclude': {'N/A'}, 'db_count' : 4, 'log_count' : 0},
{'taskName' : 'Get 1 new unique from Gnome Restaurant', 'category' : 'Minigames', 'logName' : 'Gnome Restaurant', 'exclude' : {'N/A'},'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get a Beginner wand', 'category' : 'Minigames', 'logName' : 'Magic Training Arena',  'include' : {'Beginner wand'}, 'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Unlock bones to peaches', 'category' : 'Minigames', 'logName' : 'Magic Training Arena',  'include' : {'Bones to peaches'}, 'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get Infinity boots', 'category' : 'Minigames', 'logName' : 'Magic Training Arena',  'include' : {'Infinity boots'}, 'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get Infinity gloves', 'category' : 'Minigames', 'logName' : 'Magic Training Arena',  'include' : {'Infinity gloves'}, 'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get a Void Knight seal', 'category' : 'Minigames', 'logName' : 'Pest Control',  'include' : {'Void seal(8)'}, 'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get Void Knight gloves', 'category' : 'Minigames', 'logName' : 'Pest Control',  'include' : {'Void knight gloves'}, 'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get a Void Knight mace', 'category' : 'Minigames', 'logName' : 'Pest Control',  'include' : {'Void knight mace'}, 'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get 1 piece of Rogue equipment', 'category' : 'Minigames', 'logName' : 'Rogues\' Den', 'exclude': {'N/A'}, 'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get 1 piece of Rogue equipment', 'category' : 'Minigames', 'logName' : 'Rogues\' Den', 'exclude': {'N/A'}, 'db_count' : 2, 'log_count' : 0},
{'taskName' : 'Get 1 unique from Shades of Mort\'ton', 'category' : 'Minigames', 'logName' : 'Shades of Mort\'ton', 'exclude' : {'N/A'}, 'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get 1 unique from Shades of Mort\'ton', 'category' : 'Minigames', 'logName' : 'Shades of Mort\'ton', 'exclude' : {'N/A'}, 'db_count' : 2, 'log_count' : 0},
{'taskName' : 'Get 1 piece of Lumberjack equipment', 'category' : 'Minigames', 'logName' : 'Temple Trekking', 'exclude' : {'N/A'}, 'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get the Gricoller\'s can', 'category' : 'Minigames', 'logName' : 'Tithe Farm',  'include' : {'Gricoller\'s can'}, 'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get 1 piece of Farmer\'s equipment', 'category' : 'Minigames', 'logName' : 'Tithe Farm',  'exclude' : {'Gricoller\'s can', 'Herb sack', 'Seed box'}, 'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get Blue Rum', 'category' : 'Minigames', 'logName' : 'Trouble Brewing',  'include' : {'Rum'}, 'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get Red Rum', 'category' : 'Minigames', 'logName' : 'Trouble Brewing',  'include' : {'Rum'}, 'db_count' : 2, 'log_count' : 0},
{'taskName' : 'Get The stuff', 'category' : 'Minigames', 'logName' : 'Trouble Brewing',  'include' : {'The stuff'}, 'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get the Pearl fishing rod', 'category' : 'Other', 'logName' : 'Aerial Fishing',  'include' : {'Pearl fishing rod'}, 'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get 1 unique Champion scroll', 'category' : 'Other', 'logName' : 'Champion\'s Challenge',  'exclude' : {'Champion\'s cape'}, 'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get the Marksman headpiece', 'category' : 'Other', 'logName' : 'Chompy Bird Hunting',  'exclude' : {'Chompy chick'}, 'db_count' : 6, 'log_count' : 0},
{'taskName' : 'Get a Tea flask', 'category' : 'Other', 'logName' : 'Creature Creation',  'include' : {'Tea flask'}, 'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get a Rune satchel', 'category' : 'Other', 'logName' : 'Creature Creation',  'include' : {'Rune satchel'}, 'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get a Green satchel', 'category' : 'Other', 'logName' : 'Creature Creation',  'include' : {'Green satchel'}, 'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get a Red satchel', 'category' : 'Other', 'logName' : 'Creature Creation',  'include' : {'Red satchel'}, 'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get a Black satchel', 'category' : 'Other', 'logName' : 'Creature Creation',  'include' : {'Black satchel'}, 'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get a Rune defender', 'category' : 'Other', 'logName' : 'Cyclopes',  'include' : {'Rune defender'}, 'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get 2 unique notes from Fossil Island', 'category' : 'Other', 'logName' : 'Fossil Island Notes', 'exclude' : {'N/A'}, 'db_count' : 2, 'log_count' : 0},
{'taskName' : 'Get 2 unique notes from Fossil Island', 'category' : 'Other', 'logName' : 'Fossil Island Notes', 'exclude' : {'N/A'}, 'db_count' : 4, 'log_count' : 0},
{'taskName' : 'Get 1 piece of Prospector equipment', 'category' : 'Other', 'logName' : 'Motherlode Mine',  'exclude' : {'Coal bag','Gem bag'}, 'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get 1 piece of Prospector equipment', 'category' : 'Other', 'logName' : 'Motherlode Mine',  'exclude' : {'Coal bag','Gem bag'}, 'db_count' : 2, 'log_count' : 0},
{'taskName' : 'Get 1 piece of Prospector equipment', 'category' : 'Other', 'logName' : 'Motherlode Mine',  'exclude' : {'Coal bag','Gem bag'}, 'db_count' : 3, 'log_count' : 0},
{'taskName' : 'Get 1 piece of Prospector equipment', 'category' : 'Other', 'logName' : 'Motherlode Mine',  'exclude' : {'Coal bag','Gem bag'}, 'db_count' : 4, 'log_count' : 0},
{'taskName' : 'Get 2 unique Ancient pages', 'category' : 'Other', 'logName' : 'My Notes','exclude' : {'N/A'},'db_count' : 2, 'log_count' : 0},
{'taskName' : 'Get 2 unique Ancient pages', 'category' : 'Other', 'logName' : 'My Notes','exclude' : {'N/A'},'db_count' : 4, 'log_count' : 0},
{'taskName' : 'Get Revenant ether', 'category' : 'Other', 'logName' : 'Revenants',  'include' : {'Revenant ether'}, 'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get 1 piece of Graceful equipment', 'category' : 'Other', 'logName' : 'Rooftop Agility',  'exclude' : {'Mark of grace'}, 'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get 1 piece of Graceful equipment', 'category' : 'Other', 'logName' : 'Rooftop Agility',  'exclude' : {'Mark of grace'}, 'db_count' : 2, 'log_count' : 0},
{'taskName' : 'Get 1 piece of Graceful equipment', 'category' : 'Other', 'logName' : 'Rooftop Agility',  'exclude' : {'Mark of grace'}, 'db_count' : 3, 'log_count' : 0},
{'taskName' : 'Get a Crawling hand', 'category' : 'Other', 'logName' : 'Slayer',  'include' : {'Crawling hand'}, 'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get a Cockatrice head', 'category' : 'Other', 'logName' : 'Slayer',  'include' : {'Cockatrice head'}, 'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get 1 unique from Mogres', 'category' : 'Other', 'logName' : 'Slayer',  'include' : {'Mudskipper hat', 'Flippers'}, 'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get 1 unique from Mogres', 'category' : 'Other', 'logName' : 'Slayer',  'include' : {'Mudskipper hat', 'Flippers'}, 'db_count' : 2, 'log_count' : 0},
{'taskName' : 'Get a Brine sabre', 'category' : 'Other', 'logName' : 'Slayer',  'include' : {'Brine sabre'}, 'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get 1 unique from Turoths', 'category' : 'Other', 'logName' : 'Slayer',  'include' : {'Leaf-bladed sword', 'Mystic robe bottom (light)'}, 'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get 1 unique from Turoths', 'category' : 'Other', 'logName' : 'Slayer',  'include' : {'Leaf-bladed sword', 'Mystic robe bottom (light)'}, 'db_count' : 2, 'log_count' : 0},
{'taskName' : 'Get a Black mask', 'category' : 'Other', 'logName' : 'Slayer',  'include' : {'Black mask (10)'}, 'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get the next tier of metal boots', 'category' : 'Other', 'logName' : 'Slayer',  'include' : {'Bronze boots', 'Iron boots', 'Steel boots', 'Black boots', 'Mithril boots'}, 'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get the next tier of metal boots', 'category' : 'Other', 'logName' : 'Slayer',  'include' : {'Bronze boots', 'Iron boots', 'Steel boots', 'Black boots', 'Mithril boots'}, 'db_count' : 2, 'log_count' : 0},
{'taskName' : 'Get the next tier of metal boots', 'category' : 'Other', 'logName' : 'Slayer',  'include' : {'Bronze boots', 'Iron boots', 'Steel boots', 'Black boots', 'Mithril boots'}, 'db_count' : 3, 'log_count' : 0},
{'taskName' : 'Get the next tier of metal boots', 'category' : 'Other', 'logName' : 'Slayer',  'include' : {'Bronze boots', 'Iron boots', 'Steel boots', 'Black boots', 'Mithril boots'}, 'db_count' : 4, 'log_count' : 0},
{'taskName' : 'Get the next tier of metal boots', 'category' : 'Other', 'logName' : 'Slayer',  'include' : {'Bronze boots', 'Iron boots', 'Steel boots', 'Black boots', 'Mithril boots'}, 'db_count' : 5, 'log_count' : 0},
{'taskName' : 'Get a Mystic hat (light)', 'category' : 'Other', 'logName' : 'Slayer',  'include' : {'Mystic hat (light)'}, 'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get Mystic gloves (light)', 'category' : 'Other', 'logName' : 'Slayer',  'include' : {'Mystic gloves (light)'}, 'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get Mystic boots (light)', 'category' : 'Other', 'logName' : 'Slayer',  'include' : {'Mystic boots (light)'}, 'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get 1 unique from Infernal Mages', 'category' : 'Other', 'logName' : 'Slayer',  'include' : {'Mystic boots (dark)', 'Mystic hat (dark)'}, 'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get 1 unique from Infernal Mages', 'category' : 'Other', 'logName' : 'Slayer',  'include' : {'Mystic boots (dark)', 'Mystic hat (dark)'}, 'db_count' : 2, 'log_count' : 0},
{'taskName' : 'Get Mystic gloves (dark)', 'category' : 'Other', 'logName' : 'Slayer',  'include' : {'Mystic gloves (dark)'}, 'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get 1 unique Tzhaar drop', 'category' : 'Other', 'logName' : 'TzHaar',  'exclude' : {'Toktz-mej-tal', 'Obsidian helmet', 'Obsidian platebody', 'Obsidian platelegs'}, 'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get 1 unique Tzhaar drop', 'category' : 'Other', 'logName' : 'TzHaar',  'exclude' : {'Toktz-mej-tal', 'Obsidian helmet', 'Obsidian platebody', 'Obsidian platelegs'}, 'db_count' : 2, 'log_count' : 0},
{'taskName' : 'Get a Big swordfish', 'category' : 'Other', 'logName' : 'Miscellaneous',  'include' : {'Big swordfish'}, 'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get a Big bass', 'category' : 'Other', 'logName' : 'Miscellaneous',  'include' : {'Big bass'}, 'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get a Long bone', 'category' : 'Other', 'logName' : 'Miscellaneous',  'include' : {'Long bone'}, 'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get an Ecumenical key', 'category' : 'Other', 'logName' : 'Miscellaneous',  'include' : {'Ecumenical key'}, 'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get 1 unique Dark totem piece / Ancient shard', 'category' : 'Other', 'logName' : 'Miscellaneous',  'include' : {'Dark totem base', 'Dark totem middle', 'Dark totem top'}, 'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get 1 unique Dark totem piece / Ancient shard', 'category' : 'Other', 'logName' : 'Miscellaneous',  'include' : {'Dark totem base', 'Dark totem middle', 'Dark totem top'}, 'db_count' : 2, 'log_count' : 0},
{'taskName' : 'Get 1 unique Dark totem piece / Ancient shard', 'category' : 'Other', 'logName' : 'Miscellaneous',  'include' : {'Dark totem base', 'Dark totem middle', 'Dark totem top'}, 'db_count' : 3, 'log_count' : 0},
{'taskName' : 'Get 1 unique Dark totem piece / Ancient shard', 'category' : 'Bosses', 'logName' : 'Skotizo',  'include' : {'Ancient shard'}, 'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get Mining gloves', 'category' : 'Other', 'logName' : 'Miscellaneous',  'include' : {'Mining gloves'}, 'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get a Right skull half', 'category' : 'Other', 'logName' : 'Miscellaneous',  'include' : {'Right skull half'}, 'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get a Left skull half', 'category' : 'Other', 'logName' : 'Miscellaneous',  'include' : {'Left skull half'}, 'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get a Top of sceptre', 'category' : 'Other', 'logName' : 'Miscellaneous',  'include' : {'Top of sceptre'}, 'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get a Bottom of sceptre', 'category' : 'Other', 'logName' : 'Miscellaneous',  'include' : {'Bottom of sceptre'}, 'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get a Mossy key', 'category' : 'Other', 'logName' : 'Miscellaneous',  'include' : {'Mossy key'}, 'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get a Giant key', 'category' : 'Other', 'logName' : 'Miscellaneous',  'include' : {'Giant key'}, 'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get a Fresh crab claw & Fresh crab shell', 'category' : 'Other', 'logName' : 'Miscellaneous',  'include' : {'Fresh crab claw', 'Fresh crab shell'}, 'db_count' : 2, 'log_count' : 0},
{'taskName' : 'Get a Xeric\'s talisman (inert)', 'category' : 'Other', 'logName' : 'Miscellaneous',  'include' : {'Xeric\'s talisman (inert)'}, 'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get a Supply crate from Mahogany Homes', 'category' : 'Minigames', 'logName' : 'Mahogany Homes',  'include' : {'Supply crate'}, 'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get 1 unique from Tempoross', 'category' : 'Bosses', 'logName' : 'Tempoross',  'exclude' : {'Dragon harpoon', 'Tiny tempor'}, 'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get 1 unique from Tempoross', 'category' : 'Bosses', 'logName' : 'Tempoross',  'exclude' : {'Dragon harpoon', 'Tiny tempor'}, 'db_count' : 2, 'log_count' : 0},
{'taskName' : 'Get 1 unique from Tempoross', 'category' : 'Bosses', 'logName' : 'Tempoross',  'exclude' : {'Dragon harpoon', 'Tiny tempor'}, 'db_count' : 3, 'log_count' : 0},
{'taskName' : 'Get 1 unique from Tempoross', 'category' : 'Bosses', 'logName' : 'Tempoross',  'exclude' : {'Dragon harpoon', 'Tiny tempor'}, 'db_count' : 4, 'log_count' : 0},
{'taskName' : 'Get 5 unique items at Camdozaal', 'category' : 'Other', 'logName' : 'Camdozaal', 'exclude' : {'N/A'}, 'db_count' : 5, 'log_count' : 0},
{'taskName' : 'Get 5 unique items at Camdozaal', 'category' : 'Other', 'logName' : 'Camdozaal', 'exclude' : {'N/A'}, 'db_count' : 10, 'log_count' : 0},
{'taskName' : 'Get 1 unique from Guardians of the Rift', 'category' : 'Minigames', 'logName' : 'Guardians of the Rift',  'exclude' : {'Abyssal protector'}, 'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get 1 unique from Guardians of the Rift', 'category' : 'Minigames', 'logName' : 'Guardians of the Rift',  'exclude' : {'Abyssal protector'}, 'db_count' : 2, 'log_count' : 0},
{'taskName' : 'Get 1 unique from Guardians of the Rift', 'category' : 'Minigames', 'logName' : 'Guardians of the Rift',  'exclude' : {'Abyssal protector'}, 'db_count' : 3, 'log_count' : 0},
{'taskName' : 'Get 1 unique from Guardians of the Rift', 'category' : 'Minigames', 'logName' : 'Guardians of the Rift',  'exclude' : {'Abyssal protector'}, 'db_count' : 4, 'log_count' : 0},
{'taskName' : 'Get 1 unique from Giants\' Foundry', 'category' : 'Minigames', 'logName' : 'Giants\' Foundry', 'exclude' : {'Colossal blade'}, 'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get 1 unique from Giants\' Foundry', 'category' : 'Minigames', 'logName' : 'Giants\' Foundry', 'exclude' : {'Colossal blade'}, 'db_count' : 2, 'log_count' : 0},
{'taskName' : 'Get 1 unique from Giants\' Foundry', 'category' : 'Minigames', 'logName' : 'Giants\' Foundry', 'exclude' : {'Colossal blade'}, 'db_count' : 3, 'log_count' : 0},
{'taskName' : 'Get 1 unique from Giants\' Foundry', 'category' : 'Minigames', 'logName' : 'Giants\' Foundry', 'exclude' : {'Colossal blade'}, 'db_count' : 4, 'log_count': 0},
{'taskName' : 'Get 1 unique from Forestry', 'category' : 'Other', 'logName' : 'Forestry', 'exclude' : {'Pheasant hat', 'Pheasant legs', 'Pheasant boots', 'Pheasant cape', 'Lumberjack hat', 'Lumberjack top', 'Lumberjack legs', 'Lumberjack boots'}, 'db_count' : 1, 'log_count': 0},
{'taskName' : 'Get the full Pheasant costume', 'category' : 'Other', 'logName' : 'Forestry', 'include' : {'Pheasant hat', 'Pheasant legs', 'Pheasant boots', 'Pheasant cape'}, 'db_count' : 4, 'log_count': 0},
{'taskName' : 'Get the Sturdy beehive parts', 'category' : 'Other', 'logName' : 'Forestry', 'include' : {'Sturdy beehive parts'}, 'db_count' : 1, 'log_count': 0},
{'taskName' : 'Get a Warped sceptre', 'category' : 'Other', 'logName' : 'Slayer', 'include' : {'Warped sceptre (uncharged)'}, 'db_count' : 1, 'log_count': 0},
{'taskName' : 'Get 1 unique from the Hunter Guild', 'category': 'Other', 'logName' : 'Hunter Guild', 'exclude' : {'Quetzin'}, 'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get the Sulphur blades', 'category' : 'Other', 'logName' : 'Slayer', 'include' : {'Sulphur blades'}, 'db_count' : 1, 'log_count': 0},
]

medium_log_slots = [
{'taskName' : 'Get 1 unique from Barrows','category' : 'Bosses','logName' : 'Barrows Chests', 'exclude' : {'Bolt rack'}, 'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get 1 unique from Barrows','category' : 'Bosses','logName' : 'Barrows Chests', 'exclude' : {'Bolt rack'}, 'db_count' : 2, 'log_count' : 0},
{'taskName' : 'Get 1 unique from Barrows','category' : 'Bosses','logName' : 'Barrows Chests', 'exclude' : {'Bolt rack'}, 'db_count' : 3, 'log_count' : 0},
{'taskName' : 'Get 1 unique from Barrows','category' : 'Bosses','logName' : 'Barrows Chests', 'exclude' : {'Bolt rack'}, 'db_count' : 4, 'log_count' : 0},
{'taskName' : 'Get 1 unique from Barrows','category' : 'Bosses','logName' : 'Barrows Chests', 'exclude' : {'Bolt rack'}, 'db_count' : 5, 'log_count' : 0},
{'taskName' : 'Get 1 unique from Crazy Archeologist','category' : 'Bosses','logName' : 'Crazy Archaeologist','exclude' : {'N/A'},'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get 1 unique from Crazy Archeologist','category' : 'Bosses','logName' : 'Crazy Archaeologist','exclude' : {'N/A'},'db_count' : 2, 'log_count' : 0},
{'taskName' : 'Get 1 unique from Crazy Archeologist','category' : 'Bosses','logName' : 'Crazy Archaeologist','exclude' : {'N/A'},'db_count' : 3, 'log_count' : 0},
{'taskName' : 'Get a Fire cape','category' : 'Bosses','logName' : 'The Fight Caves','exclude' : {'Tzrek-jad'},'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get Granite dust','category' : 'Bosses','logName' : 'Grotesque Guardians','include' : {'Granite dust'},'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get a Hill giant club','category' : 'Bosses','logName' : 'Obor','include' : {'Hill giant club'},'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get 1 Unique from Wintertodt','category' : 'Bosses','logName' : 'Wintertodt','exclude' : {'Phoenix', 'Dragon axe'},'db_count' : 6, 'log_count' : 0},
{'taskName' : 'Get 1 Unique from Wintertodt','category' : 'Bosses','logName' : 'Wintertodt','exclude' : {'Phoenix', 'Dragon axe'},'db_count' : 7, 'log_count' : 0},
{'taskName' : 'Get 1 Unique from Wintertodt','category' : 'Bosses','logName' : 'Wintertodt','exclude' : {'Phoenix', 'Dragon axe'},'db_count' : 8, 'log_count' : 0},
{'taskName' : 'Get 1 Unique from Zulrah','category' : 'Bosses','logName' : 'Zulrah','include' : {'Zulrah\'s scales', 'Magic fang', 'Tanzanite fang', 'Uncut onyx', 'Serpentine visage', 'Zul-andra teleport'}, 'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get 1 Unique from Zulrah','category' : 'Bosses','logName' : 'Zulrah','include' : {'Zulrah\'s scales', 'Magic fang', 'Tanzanite fang', 'Uncut onyx', 'Serpentine visage', 'Zul-andra teleport'}, 'db_count' : 2, 'log_count' : 0},
{'taskName' : 'Get 3 new uniques from beginner clues','category' : 'Clues','logName' : 'Beginner Treasure Trails','exclude' : {'Black pickaxe'},'db_count' : 9, 'log_count' : 0},
{'taskName' : 'Get 3 new uniques from beginner clues','category' : 'Clues','logName' : 'Beginner Treasure Trails','exclude' : {'Black pickaxe'},'db_count' : 12, 'log_count' : 0},
{'taskName' : 'Get 5 new uniques from easy clues','category' : 'Clues','logName' : 'Easy Treasure Trails','exclude' : {'N/A'}, 'db_count' : 35, 'log_count' : 0},
{'taskName' : 'Get 5 new uniques from easy clues','category' : 'Clues','logName' : 'Easy Treasure Trails','exclude' : {'N/A'}, 'db_count' : 40, 'log_count' : 0},
{'taskName' : 'Get 5 new uniques from easy clues','category' : 'Clues','logName' : 'Easy Treasure Trails','exclude' : {'N/A'}, 'db_count' : 45, 'log_count' : 0},
{'taskName' : 'Get 5 new uniques from easy clues','category' : 'Clues','logName' : 'Easy Treasure Trails','exclude' : {'N/A'}, 'db_count' : 50, 'log_count' : 0},
{'taskName' : 'Get 5 new uniques from easy clues','category' : 'Clues','logName' : 'Easy Treasure Trails','exclude' : {'N/A'}, 'db_count' : 55, 'log_count' : 0},
{'taskName' : 'Get 5 new uniques from easy clues','category' : 'Clues','logName' : 'Easy Treasure Trails','exclude' : {'N/A'}, 'db_count' : 60, 'log_count' : 0},
{'taskName' : 'Get 5 new uniques from medium clues','category' : 'Clues','logName' : 'Medium Treasure Trails','exclude' : {'N/A'}, 'db_count' : 25, 'log_count' : 0},
{'taskName' : 'Get 5 new uniques from medium clues','category' : 'Clues','logName' : 'Medium Treasure Trails','exclude' : {'N/A'}, 'db_count' : 30, 'log_count' : 0},
{'taskName' : 'Get 5 new uniques from medium clues','category' : 'Clues','logName' : 'Medium Treasure Trails','exclude' : {'N/A'}, 'db_count' : 35, 'log_count' : 0},
{'taskName' : 'Get 5 new uniques from medium clues','category' : 'Clues','logName' : 'Medium Treasure Trails','exclude' : {'N/A'}, 'db_count' : 40, 'log_count' : 0},
{'taskName' : 'Get 5 new uniques from hard clues','category' : 'Clues','logName' : 'Hard Treasure Trails','exclude' : {'N/A'}, 'db_count' : 15, 'log_count' : 0},
{'taskName' : 'Get 5 new uniques from hard clues','category' : 'Clues','logName' : 'Hard Treasure Trails','exclude' : {'N/A'}, 'db_count' : 20, 'log_count' : 0},
{'taskName' : 'Get 5 new uniques from hard clues','category' : 'Clues','logName' : 'Hard Treasure Trails','exclude' : {'N/A'}, 'db_count' : 25, 'log_count' : 0},
{'taskName' : 'Get 5 new uniques from hard clues','category' : 'Clues','logName' : 'Hard Treasure Trails','exclude' : {'N/A'}, 'db_count' : 30, 'log_count' : 0},
{'taskName' : 'Get a Fighter hat','category' : 'Minigames','logName' : 'Barbarian Assault','include' : {'Fighter hat'},'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get a Healer hat','category' : 'Minigames','logName' : 'Barbarian Assault','include' : {'Healer hat'},'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get a Runner hat','category' : 'Minigames','logName' : 'Barbarian Assault','include' : {'Runner hat'},'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get a Ranger hat','category' : 'Minigames','logName' : 'Barbarian Assault','include' : {'Ranger hat'},'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get a Fighter torso','category' : 'Minigames','logName' : 'Barbarian Assault','include' : {'Fighter torso'},'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get a Granite helm','category' : 'Other','logName' : 'Slayer','include' : {'Granite helm'},'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get 1 new halo','category' : 'Minigames','logName' : 'Castle Wars','include' : {'Saradomin halo', 'Zamorak halo', 'Guthix halo'},'db_count' : 2, 'log_count' : 0},
{'taskName' : 'Get the Decorative ranged set','category' : 'Minigames','logName' : 'Castle Wars','include' : {'Decorative helm', 'Decorative full helm', 'Decorative armour', 'Decorative sword', 'Decorative shield', 'Decorative boots'},'db_count' : 11, 'log_count' : 0},
{'taskName' : 'Get the Decorative magic set','category' : 'Minigames','logName' : 'Castle Wars','include' : {'Decorative helm', 'Decorative full helm', 'Decorative armour', 'Decorative sword', 'Decorative shield', 'Decorative boots'},'db_count' : 14, 'log_count' : 0},
{'taskName' : 'Get 1 new unique from Gnome Restaurant','category' : 'Minigames','logName' : 'Gnome Restaurant','exclude' : {'N/A'},'db_count' : 2, 'log_count' : 0},
{'taskName' : 'Get 1 new unique from Gnome Restaurant','category' : 'Minigames','logName' : 'Gnome Restaurant','exclude' : {'N/A'},'db_count' : 3, 'log_count' : 0},
{'taskName' : 'Upgrade the MTA wand once','category' : 'Minigames','logName' : 'Magic Training Arena','include' : {'Beginner wand'},'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Upgrade the MTA wand once','category' : 'Minigames','logName' : 'Magic Training Arena','include' : {'Apprentice wand'},'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Upgrade the MTA wand once','category' : 'Minigames','logName' : 'Magic Training Arena','include' : {'Teacher wand'},'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get an Infinity hat','category' : 'Minigames','logName' : 'Magic Training Arena','include' : {'Infinity hat'},'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get a Mage\'s book','category' : 'Minigames','logName' : 'Magic Training Arena','include' : {'Mage\'s book'},'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get a Void melee helm','category' : 'Minigames','logName' : 'Pest Control','include' : {'Void melee helm'},'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get a Void magic helm','category' : 'Minigames','logName' : 'Pest Control','include' : {'Void mage helm'},'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get a Void ranger helm','category' : 'Minigames','logName' : 'Pest Control','include' : {'Void ranger helm'},'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get a Void Knight top','category' : 'Minigames','logName' : 'Pest Control','include' : {'Void knight top'},'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get a Void Knight robe','category' : 'Minigames','logName' : 'Pest Control','include' : {'Void knight robe'},'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get 1 piece of Rogue equipment','category' : 'Minigames','logName' : 'Rogues\' Den','exclude' : {'N/A'},'db_count' : 3, 'log_count' : 0},
{'taskName' : 'Get 1 piece of Rogue equipment','category' : 'Minigames','logName' : 'Rogues\' Den','exclude' : {'N/A'},'db_count' : 4, 'log_count' : 0},
{'taskName' : 'Get 1 piece of Rogue equipment','category' : 'Minigames','logName' : 'Rogues\' Den','exclude' : {'N/A'},'db_count' : 5, 'log_count' : 0},
{'taskName' : 'Get 1 unique from Shades of Mort\'ton','category' : 'Minigames','logName' : 'Shades of Mort\'ton','exclude' : {'N/A'},'db_count' : 3, 'log_count' : 0},
{'taskName' : 'Get 1 unique from Shades of Mort\'ton','category' : 'Minigames','logName' : 'Shades of Mort\'ton','exclude' : {'N/A'},'db_count' : 4, 'log_count' : 0},
{'taskName' : 'Get 1 unique from Shades of Mort\'ton','category' : 'Minigames','logName' : 'Shades of Mort\'ton','exclude' : {'N/A'},'db_count' : 5, 'log_count' : 0},
{'taskName' : 'Get 1 piece of Lumberjack equipment','category' : 'Minigames','logName' : 'Temple Trekking','exclude' : {'N/A'},'db_count' : 2, 'log_count' : 0},
{'taskName' : 'Get 1 piece of Lumberjack equipment','category' : 'Minigames','logName' : 'Temple Trekking','exclude' : {'N/A'},'db_count' : 3, 'log_count' : 0},
{'taskName' : 'Get 1 piece of Lumberjack equipment','category' : 'Minigames','logName' : 'Temple Trekking','exclude' : {'N/A'},'db_count' : 4, 'log_count' : 0},
{'taskName' : 'Get 1 piece of Farmer\'s equipment','category' : 'Minigames','logName' : 'Tithe Farm','exclude' : {'Gricoller\'s can', 'Herb sack', 'Seed box'}, 'db_count' : 2, 'log_count' : 0},
{'taskName' : 'Get 1 piece of Farmer\'s equipment','category' : 'Minigames','logName' : 'Tithe Farm','exclude' : {'Gricoller\'s can', 'Herb sack', 'Seed box'}, 'db_count' : 3, 'log_count' : 0},
{'taskName' : 'Get 1 piece of Farmer\'s equipment','category' : 'Minigames','logName' : 'Tithe Farm','exclude' : {'Gricoller\'s can', 'Herb sack', 'Seed box'}, 'db_count' : 4, 'log_count' : 0},
{'taskName' : 'Get the Seed box','category' : 'Minigames','logName' : 'Tithe Farm','include' : {'Seed box'},'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get 1 Naval set','category' : 'Minigames','logName' : 'Trouble Brewing', 'exclude' : {'Cutthroat flag', 'Gilded smile flag', 'Bronze fist flag', 'Lucky shot flag', 'Treasure flag', 'Phasmatys flag', 'The stuff', 'rum'}, 'db_count' : 3, 'log_count' : 0},
{'taskName' : 'Get 1 Naval set','category' : 'Minigames','logName' : 'Trouble Brewing', 'exclude' : {'Cutthroat flag', 'Gilded smile flag', 'Bronze fist flag', 'Lucky shot flag', 'Treasure flag', 'Phasmatys flag', 'The stuff', 'rum'}, 'db_count' : 6, 'log_count' : 0},
{'taskName' : 'Get the Cutthroat flag','category' : 'Minigames','logName' : 'Trouble Brewing','include' : {'Cutthroat flag'},'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get the Guilded smile flag','category' : 'Minigames','logName' : 'Trouble Brewing','include' : {'Gilded smile flag'},'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get the Pearl fly fishing rod','category' : 'Other','logName' : 'Aerial Fishing','include' : {'Pearl fly fishing rod'},'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get the Pearl barbarian rod','category' : 'Other','logName' : 'Aerial Fishing','include' : {'Pearl barbarian rod'},'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get 1 unique Champion scroll','category' : 'Other','logName' : 'Champion\'s Challenge','exclude' : {'Champion\'s cape'},'db_count' : 2, 'log_count' : 0},
{'taskName' : 'Get 1 unique Champion scroll','category' : 'Other','logName' : 'Champion\'s Challenge','exclude' : {'Champion\'s cape'},'db_count' : 3, 'log_count' : 0},
{'taskName' : 'Get 1 unique Elder chaos robe piece','category' : 'Other','logName' : 'Chaos Druids','exclude' : {'N/A'},'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get 1 unique Elder chaos robe piece','category' : 'Other','logName' : 'Chaos Druids','exclude' : {'N/A'},'db_count' : 2, 'log_count' : 0},
{'taskName' : 'Get the Ogre forester headpiece','category' : 'Other','logName' : 'Chompy Bird Hunting','db_count' : 9, 'log_count' : 0},
{'taskName' : 'Get a Gold satchel','category' : 'Other','logName' : 'Creature Creation','include' : {'Gold satchel'},'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get a Plain satchel','category' : 'Other','logName' : 'Creature Creation','include' : {'Plain satchel'},'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get a Dragon defender','category' : 'Other','logName' : 'Cyclopes','include' : {'Dragon defender'},'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get 2 unique notes from Fossil Island','category' : 'Other','logName' : 'Fossil Island Notes', 'exclude': {'N/A'}, 'db_count' : 6, 'log_count' : 0},
{'taskName' : 'Get 2 unique notes from Fossil Island','category' : 'Other','logName' : 'Fossil Island Notes', 'exclude': {'N/A'}, 'db_count' : 8, 'log_count' : 0},
{'taskName' : 'Get 2 unique notes from Fossil Island','category' : 'Other','logName' : 'Fossil Island Notes', 'exclude': {'N/A'}, 'db_count' : 10, 'log_count' : 0},
{'taskName' : 'Get the Coal bag','category' : 'Other','logName' : 'Motherlode Mine','include' : {'Coal bag'},'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get the Gem bag','category' : 'Other','logName' : 'Motherlode Mine','include' : {'Gem bag'},'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get 2 unique Ancient pages','category' : 'Other','logName' : 'My Notes','count' : 2, 'db_count' : 6, 'log_count' : 0},
{'taskName' : 'Get 2 unique Ancient pages','category' : 'Other','logName' : 'My Notes','count' : 2, 'db_count' : 8, 'log_count' : 0},
{'taskName' : 'Get 2 unique Ancient pages','category' : 'Other','logName' : 'My Notes','count' : 2, 'db_count' : 10, 'log_count' : 0},
{'taskName' : 'Get 2 unique Ancient pages','category' : 'Other','logName' : 'My Notes','count' : 2, 'db_count' : 12, 'log_count' : 0},
{'taskName' : 'Get 2 unique Ancient pages','category' : 'Other','logName' : 'My Notes','count' : 2, 'db_count' : 14, 'log_count' : 0},
{'taskName' : 'Get 2 unique Ancient pages','category' : 'Other','logName' : 'My Notes','count' : 2, 'db_count' : 16, 'log_count' : 0},
{'taskName' : 'Get 1 piece of Graceful equipment','category' : 'Other','logName' : 'Rooftop Agility','exclude' : {'Mark of grace'},'db_count' : 2, 'log_count' : 0},
{'taskName' : 'Get 1 piece of Graceful equipment','category' : 'Other','logName' : 'Rooftop Agility','exclude' : {'Mark of grace'},'db_count' : 3, 'log_count' : 0},
{'taskName' : 'Get 1 piece of Graceful equipment','category' : 'Other','logName' : 'Rooftop Agility','exclude' : {'Mark of grace'},'db_count' : 4, 'log_count' : 0},
{'taskName' : 'Get tier 5 Shayzien armour','category' : 'Other','logName' : 'Shayzien Armour','exclude' : {'N/A'},'db_count' : 25, 'log_count' : 0},
{'taskName' : 'Get a Basilisk head','category' : 'Other','logName' : 'Slayer','include' : {'Basilisk head'},'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get 1 unique from Gargoyles','category' : 'Other','logName' : 'Slayer','include' : {'Granite maul', 'Mystic robe top (dark)'},'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get 1 unique from Gargoyles','category' : 'Other','logName' : 'Slayer','include' : {'Granite maul', 'Mystic robe top (dark)'},'db_count' : 2, 'log_count' : 0},
{'taskName' : 'Get 1 unique from Kurasks','category' : 'Other','logName' : 'Slayer','include' : {'Leaf-bladed battleaxe', 'Mystic robe top (light)'},'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get 1 unique from Kurasks','category' : 'Other','logName' : 'Slayer','include' : {'Leaf-bladed battleaxe', 'Mystic robe top (light)'},'db_count' : 2, 'log_count' : 0},
{'taskName' : 'Get a Granite longsword','category' : 'Other','logName' : 'Slayer','include' : {'Granite longsword'},'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get Granite legs','category' : 'Other','logName' : 'Slayer','include' : {'Granite legs'},'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get the next tier of metal boots','category' : 'Other','logName' : 'Slayer','include' : {'Adamant boots', 'Rune boots'},'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get the next tier of metal boots','category' : 'Other','logName' : 'Slayer','include' : {'Adamant boots', 'Rune boots'},'db_count' : 2, 'log_count' : 0},
{'taskName' : 'Get a Mystic robe bottom (dark)','category' : 'Other','logName' : 'Slayer','include' : {'Mystic robe bottom (dark)'},'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get 1 unique Tzhaar drop','category' : 'Other','logName' : 'TzHaar','exclude' : {'Toktz-mej-tal', 'Obsidian helmet', 'Obsidian platebody', 'Obsidian platelegs'},'db_count' : 3, 'log_count' : 0},
{'taskName' : 'Get 1 unique Tzhaar drop','category' : 'Other','logName' : 'TzHaar','exclude' : {'Toktz-mej-tal', 'Obsidian helmet', 'Obsidian platebody', 'Obsidian platelegs'},'db_count' : 4, 'log_count' : 0},
{'taskName' : 'Get 1 unique Tzhaar drop','category' : 'Other','logName' : 'TzHaar','exclude' : {'Toktz-mej-tal', 'Obsidian helmet', 'Obsidian platebody', 'Obsidian platelegs'},'db_count' : 5, 'log_count' : 0},
{'taskName' : 'Get 1 unique Tzhaar drop','category' : 'Other','logName' : 'TzHaar','exclude' : {'Toktz-mej-tal', 'Obsidian helmet', 'Obsidian platebody', 'Obsidian platelegs'},'db_count' : 6, 'log_count' : 0},
{'taskName' : 'Get a Big shark','category' : 'Other','logName' : 'Miscellaneous','include' : {'Big shark'},'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get a Curved bone','category' : 'Other','logName' : 'Miscellaneous','include' : {'Curved bone'},'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get a Shaman mask','category' : 'Other','logName' : 'Miscellaneous','include' : {'Shaman mask'},'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get Superior mining gloves','category' : 'Other','logName' : 'Miscellaneous','include' : {'Superior mining gloves'},'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get a Bracelet of ethereum or Rev cave teleport','category' : 'Other','logName' : 'Revenants','include' : {'Revenant cave teleport', 'Revenant ether'},'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get a Bracelet of ethereum or Rev cave teleport','category' : 'Other','logName' : 'Revenants','include' : {'Revenant cave teleport', 'Revenant ether'},'db_count' : 2, 'log_count' : 0},
{'taskName' : 'Get a Mask of Ranul','category' : 'Other','logName' : 'Miscellaneous','include' : {'Mask of ranul'},'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get a Giant egg sac(full)','category' : 'Bosses','logName' : 'Sarachnis','include' : {'Giant egg sac(full)'},'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get a Herb sack','category' : 'Minigames','logName' : 'Tithe Farm','include' : {'Herb sack'},'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get a Plank sack','category' : 'Minigames','logName' : 'Mahogany Homes','include' : {'Plank sack'},'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get 1 piece of Carpenter equipment','category' : 'Minigames','logName' : 'Mahogany Homes','exclude' : {'Supply crate', 'Amy\'s saw', 'Plank sack', 'Hosidius blueprints'},'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get 1 piece of Carpenter equipment','category' : 'Minigames','logName' : 'Mahogany Homes','exclude' : {'Supply crate', 'Amy\'s saw', 'Plank sack', 'Hosidius blueprints'},'db_count' : 2, 'log_count' : 0},
{'taskName' : 'Get an Ectoplasmator','category' : 'Minigames','logName' : 'Soul Wars','include' : {'Ectoplasmator'},'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get a Penance skirt','category' : 'Minigames','logName' : 'Barbarian Assault','include' : {'Penance skirt'},'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get a Celestial ring','category' : 'Other','logName' : 'Shooting Stars','include' : {'Celestial ring (uncharged)'},'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get a Star fragment','category' : 'Other','logName' : 'Shooting Stars','include' : {'Star fragment'},'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get 1 unique from Tempoross','category' : 'Bosses','logName' : 'Tempoross','exclude' : {'Dragon harpoon', 'Tiny tempor'},'db_count' : 5, 'log_count' : 0},
{'taskName' : 'Get 1 unique from Tempoross','category' : 'Bosses','logName' : 'Tempoross','exclude' : {'Dragon harpoon', 'Tiny tempor'},'db_count' : 6, 'log_count' : 0},
{'taskName' : 'Get 1 unique from Tempoross','category' : 'Bosses','logName' : 'Tempoross','exclude' : {'Dragon harpoon', 'Tiny tempor'},'db_count' : 7, 'log_count' : 0},
{'taskName' : 'Get the Merfolk trident','category' : 'Other','logName' : 'Miscellaneous','include' : {'Merfolk trident'},'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get 1 unique from Tempoross','category' : 'Bosses','logName' : 'Tempoross','exclude' : {'Dragon harpoon', 'Tiny tempor'},'db_count' : 8, 'log_count' : 0},
{'taskName' : 'Get 1 unique from Tempoross','category' : 'Bosses','logName' : 'Tempoross','exclude' : {'Dragon harpoon', 'Tiny tempor'},'db_count' : 9, 'log_count' : 0},
{'taskName' : 'Get 1 unique from Guardians of the Rift','category' : 'Minigames','logName' : 'Guardians of the Rift','exclude' : {'Abyssal protector'},'db_count' : 5, 'log_count' : 0},
{'taskName' : 'Get 1 unique from Guardians of the Rift','category' : 'Minigames','logName' : 'Guardians of the Rift','exclude' : {'Abyssal protector'},'db_count' : 6, 'log_count' : 0},
{'taskName' : 'Get 1 unique from Guardians of the Rift','category' : 'Minigames','logName' : 'Guardians of the Rift','exclude' : {'Abyssal protector'},'db_count' : 7, 'log_count' : 0},
{'taskName' : 'Get 1 unique from Guardians of the Rift','category' : 'Minigames','logName' : 'Guardians of the Rift','exclude' : {'Abyssal protector'},'db_count' : 8, 'log_count' : 0},
{'taskName' : 'Get 1 unique from Giants\' Foundry','category' : 'Minigames','logName' : 'Giants\' Foundry', 'exclude' : {'Colossal blade'}, 'db_count' : 5, 'log_count' : 0},
{'taskName' : 'Get 1 unique from Giants\' Foundry','category' : 'Minigames','logName' : 'Giants\' Foundry', 'exclude' : {'Colossal blade'}, 'db_count' : 6, 'log_count' : 0},
{'taskName' : 'Get 1 unique from Giants\' Foundry','category' : 'Minigames','logName' : 'Giants\' Foundry', 'exclude' : {'Colossal blade'}, 'db_count' : 7, 'log_count' : 0},
{'taskName' : 'Get 1 unique from Giants\' Foundry','category' : 'Minigames','logName' : 'Giants\' Foundry', 'exclude' : {'Colossal blade'}, 'db_count' : 8, 'log_count' : 0},
{'taskName' : 'Get 1 unique from Forestry', 'category' : 'Other', 'logName' : 'Forestry', 'exclude' : {'Pheasant hat', 'Pheasant legs', 'Pheasant boots', 'Pheasant cape', 'Lumberjack hat', 'Lumberjack top', 'Lumberjack legs', 'Lumberjack boots'}, 'db_count' : 2, 'log_count': 0},
{'taskName' : 'Get 1 unique from Forestry', 'category' : 'Other', 'logName' : 'Forestry', 'exclude' : {'Pheasant hat', 'Pheasant legs', 'Pheasant boots', 'Pheasant cape', 'Lumberjack hat', 'Lumberjack top', 'Lumberjack legs', 'Lumberjack boots'}, 'db_count' : 3, 'log_count': 0},
{'taskName' : 'Get 1 unique from Forestry', 'category' : 'Other', 'logName' : 'Forestry', 'exclude' : {'Pheasant hat', 'Pheasant legs', 'Pheasant boots', 'Pheasant cape', 'Lumberjack hat', 'Lumberjack top', 'Lumberjack legs', 'Lumberjack boots'}, 'db_count' : 4, 'log_count': 0},
{'taskName' : 'Get 1 unique from Forestry', 'category' : 'Other', 'logName' : 'Forestry', 'exclude' : {'Pheasant hat', 'Pheasant legs', 'Pheasant boots', 'Pheasant cape', 'Lumberjack hat', 'Lumberjack top', 'Lumberjack legs', 'Lumberjack boots'}, 'db_count' : 5, 'log_count': 0},
{'taskName' : "Get a Scurrius' spine", 'category' : 'Bosses', 'logName': 'Scurrius', 'include' : {"Scurrius' spine"}, 'db_count' : 1, 'log_count' : 0},
{'taskName' : "Get a Broken zombie axe", 'category' : 'Other', 'logName': 'Miscellaneous', 'include' : {"Broken zombie axe"}, 'db_count' : 1, 'log_count' : 0},
{'taskName' : "Get 1 unique from Moons of Peril bosses", 'category' : 'Bosses', 'logName': 'Moons of Peril', 'exclude' : {"N/A"}, 'db_count' : 1, 'log_count' : 0},
{'taskName' : "Get 1 unique from Moons of Peril bosses", 'category' : 'Bosses', 'logName': 'Moons of Peril', 'exclude' : {"N/A"}, 'db_count' : 2, 'log_count' : 0},
{'taskName' : "Get 1 unique from Moons of Peril bosses", 'category' : 'Bosses', 'logName': 'Moons of Peril', 'exclude' : {"N/A"}, 'db_count' : 3, 'log_count' : 0},
{'taskName' : "Get 1 unique from Moons of Peril bosses", 'category' : 'Bosses', 'logName': 'Moons of Peril', 'exclude' : {"N/A"}, 'db_count' : 4, 'log_count' : 0},
{'taskName' : "Get 1 unique from the Hunter Guild", 'category' : 'Other', 'logName': 'Hunter Guild', 'exclude' : {'Quetzin'}, 'db_count' : 2, 'log_count' : 0},
]



hard_log_slots = [
{'taskName' : 'Get 1 unique from Barrows','category' : 'Bosses','logName' : 'Barrows Chests','exclude' : {'Bolt rack'}, 'db_count' : 6,'log_count' : 0},
{'taskName' : 'Get 1 unique from Barrows','category' : 'Bosses','logName' : 'Barrows Chests','exclude' : {'Bolt rack'}, 'db_count' : 7,'log_count' : 0},
{'taskName' : 'Get 1 unique from Barrows','category' : 'Bosses','logName' : 'Barrows Chests','exclude' : {'Bolt rack'}, 'db_count' : 8,'log_count' : 0},
{'taskName' : 'Get 1 unique from Barrows','category' : 'Bosses','logName' : 'Barrows Chests','exclude' : {'Bolt rack'}, 'db_count' : 9,'log_count' : 0},
{'taskName' : 'Get 1 unique from Barrows','category' : 'Bosses','logName' : 'Barrows Chests','exclude' : {'Bolt rack'}, 'db_count' : 10,'log_count' : 0},
{'taskName' : 'Get 1 unique from Barrows','category' : 'Bosses','logName' : 'Barrows Chests','exclude' : {'Bolt rack'}, 'db_count' : 11,'log_count' : 0},
{'taskName' : 'Get 1 unique from Barrows','category' : 'Bosses','logName' : 'Barrows Chests','exclude' : {'Bolt rack'}, 'db_count' : 12,'log_count' : 0},
{'taskName' : 'Get 1 unique from Barrows','category' : 'Bosses','logName' : 'Barrows Chests','exclude' : {'Bolt rack'}, 'db_count' : 13,'log_count' : 0},
{'taskName' : 'Get 1 unique from Barrows','category' : 'Bosses','logName' : 'Barrows Chests','exclude' : {'Bolt rack'}, 'db_count' : 14,'log_count' : 0},
{'taskName' : 'Get 1 unique from Barrows','category' : 'Bosses','logName' : 'Barrows Chests','exclude' : {'Bolt rack'}, 'db_count' : 15,'log_count' : 0},
{'taskName' : 'Get 1 unique from Barrows','category' : 'Bosses','logName' : 'Barrows Chests','exclude' : {'Bolt rack'}, 'db_count' : 16,'log_count' : 0},
{'taskName' : 'Get 1 unique from Barrows','category' : 'Bosses','logName' : 'Barrows Chests','exclude' : {'Bolt rack'}, 'db_count' : 17,'log_count' : 0},
{'taskName' : 'Get 1 unique from Barrows','category' : 'Bosses','logName' : 'Barrows Chests','exclude' : {'Bolt rack'}, 'db_count' : 18,'log_count' : 0},
{'taskName' : 'Get 1 unique from Barrows','category' : 'Bosses','logName' : 'Barrows Chests','exclude' : {'Bolt rack'}, 'db_count' : 19,'log_count' : 0},
{'taskName' : 'Get 1 unique from Barrows','category' : 'Bosses','logName' : 'Barrows Chests','exclude' : {'Bolt rack'}, 'db_count' : 20,'log_count' : 0},
{'taskName' : 'Get a unique from Unsired','category' : 'Bosses','logName' : 'Abyssal Sire','include' : {'Bludgeon spine', 'Bludgeon axon', 'Bludgeon claw', 'Abyssal dagger', 'Abyssal head'},'db_count' : 1,'log_count' : 0},
{'taskName' : 'Get a unique from Unsired','category' : 'Bosses','logName' : 'Abyssal Sire','include' : {'Bludgeon spine', 'Bludgeon axon', 'Bludgeon claw', 'Abyssal dagger', 'Abyssal head'},'db_count' : 2,'log_count' : 0},
{'taskName' : 'Get a unique from Unsired','category' : 'Bosses','logName' : 'Abyssal Sire','include' : {'Bludgeon spine', 'Bludgeon axon', 'Bludgeon claw', 'Abyssal dagger', 'Abyssal head'},'db_count' : 3,'log_count' : 0},
{'taskName' : 'Get an Abyssal whip','category' : 'Bosses','logName' : 'Abyssal Sire','include' : {'Abyssal whip'},'db_count' : 1,'log_count' : 0},
{'taskName' : 'Get 1 unique item from Mount Karuulm','category' : 'Other','logName' : 'Slayer','include' : {'Dragon thrownaxe', 'Dragon harpoon', 'Dragon sword', 'Dragon knife', 'Drake\'s tooth', 'Drake\'s claw'},'db_count' : 1,'log_count' : 0},
{'taskName' : 'Get 1 unique item from Mount Karuulm','category' : 'Other','logName' : 'Slayer','include' : {'Dragon thrownaxe', 'Dragon harpoon', 'Dragon sword', 'Dragon knife', 'Drake\'s tooth', 'Drake\'s claw'},'db_count' : 2,'log_count' : 0},
{'taskName' : 'Get 1 unique item from Mount Karuulm','category' : 'Other','logName' : 'Slayer','include' : {'Dragon thrownaxe', 'Dragon harpoon', 'Dragon sword', 'Dragon knife', 'Drake\'s tooth', 'Drake\'s claw'},'db_count' : 3,'log_count' : 0},
{'taskName' : 'Get 1 unique item from Mount Karuulm','category' : 'Other','logName' : 'Slayer','include' : {'Dragon thrownaxe', 'Dragon harpoon', 'Dragon sword', 'Dragon knife', 'Drake\'s tooth', 'Drake\'s claw'},'db_count' : 4,'log_count' : 0},
{'taskName' : 'Get 1 unique item from Mount Karuulm','category' : 'Other','logName' : 'Slayer','include' : {'Dragon thrownaxe', 'Dragon harpoon', 'Dragon sword', 'Dragon knife', 'Drake\'s tooth', 'Drake\'s claw'},'db_count' : 5,'log_count' : 0},
{'taskName' : 'Get 1 unique from the Chaos Elemental','category' : 'Bosses','logName' : 'Chaos Elemental','exclude' : {'Pet chaos elemental'},'db_count' : 1,'log_count' : 0},
{'taskName' : 'Get 1 unique from the Chaos Elemental','category' : 'Bosses','logName' : 'Chaos Elemental','exclude' : {'Pet chaos elemental'},'db_count' : 2,'log_count' : 0},
    None,
{'taskName' : 'Get 1 unique from Cerberus','category' : 'Bosses','logName' : 'Cerberus','exclude' : {'Hellpuppy', 'Jar of souls'},'db_count' : 1,'log_count' : 0},
{'taskName' : 'Get 1 unique from Cerberus','category' : 'Bosses','logName' : 'Cerberus','exclude' : {'Hellpuppy', 'Jar of souls'},'db_count' : 2,'log_count' : 0},
{'taskName' : 'Get 1 unique from Cerberus','category' : 'Bosses','logName' : 'Cerberus','exclude' : {'Hellpuppy', 'Jar of souls'},'db_count' : 3,'log_count' : 0},
{'taskName' : 'Get a unique shard 1','category' : 'Bosses','logName' : 'Chaos Fanatic','exclude' : {'Pet chaos elemental'},'db_count' : 1,'log_count' : 0},
{'taskName' : 'Get a unique shard 1','category' : 'Bosses','logName' : 'Chaos Fanatic','exclude' : {'Pet chaos elemental'},'db_count' : 2,'log_count' : 0},
{'taskName' : 'Get a new Boss pet','category' : 'Other','logName' : 'All Pets','exclude' : {'Abyssal orphan','Baby mole','Callisto cub','Hellpuppy','Ikkle hydra','Jal-nib-rek/Tzrek-zuk','Kalphite princess','Lil\' zik','Little nightmare','Nexling','Noon/Midnight','Olmlet','Pet chaos elemental','Pet dagannoth prime','Pet dagannoth rex','Pet dagannoth supreme','Pet dark core/corporeal critter','Pet general graardor','Pet k\'ril tsutsaroth','Pet kraken','Pet kree\'arra','Pet smoke devil','Pet snakeling','Pet zilyana','Prince black dragon','Scorpia\'s offspring','Skotos','Sraracha','Tzrek-jad','Tumeken\'s guardian','Venenatis spiderling','Vet\'ion jr.','Vorki'},'db_count' : 1,'log_count' : 0},
{'taskName' : 'Get 1 unique drop from Zamorak GWD','category' : 'Bosses','logName' : 'K\'ril Tsutsaroth','include' : {'Staff of the dead', 'Zamorakian spear', 'Steam battlestaff', 'Zamorak hilt'},'db_count' : 1,'log_count' : 0},
{'taskName' : 'Get 1 unique drop from Zamorak GWD','category' : 'Bosses','logName' : 'K\'ril Tsutsaroth','include' : {'Staff of the dead', 'Zamorakian spear', 'Steam battlestaff', 'Zamorak hilt'},'db_count' : 2,'log_count' : 0},
{'taskName' : 'Get 1 unique drop from Dagannoth Kings','category' : 'Bosses','logName' : 'Dagannoth Kings','exclude' : {'Pet dagannoth prime', 'Pet dagannoth supreme', 'Pet dagannoth rex'},'db_count' : 1,'log_count' : 0},
{'taskName' : 'Get 1 unique drop from Dagannoth Kings','category' : 'Bosses','logName' : 'Dagannoth Kings','exclude' : {'Pet dagannoth prime', 'Pet dagannoth supreme', 'Pet dagannoth rex'},'db_count' : 2,'log_count' : 0},
{'taskName' : 'Get 1 unique drop from Dagannoth Kings','category' : 'Bosses','logName' : 'Dagannoth Kings','exclude' : {'Pet dagannoth prime', 'Pet dagannoth supreme', 'Pet dagannoth rex'},'db_count' : 3,'log_count' : 0},
{'taskName' : 'Get 1 unique drop from Dagannoth Kings','category' : 'Bosses','logName' : 'Dagannoth Kings','exclude' : {'Pet dagannoth prime', 'Pet dagannoth supreme', 'Pet dagannoth rex'},'db_count' : 4,'log_count' : 0},
{'taskName' : 'Get 1 unique drop from Dagannoth Kings','category' : 'Bosses','logName' : 'Dagannoth Kings','exclude' : {'Pet dagannoth prime', 'Pet dagannoth supreme', 'Pet dagannoth rex'},'db_count' : 5,'log_count' : 0},
{'taskName' : 'Get 1 unique drop from Dagannoth Kings','category' : 'Bosses','logName' : 'Dagannoth Kings','exclude' : {'Pet dagannoth prime', 'Pet dagannoth supreme', 'Pet dagannoth rex'},'db_count' : 6,'log_count' : 0},
{'taskName' : 'Get 1 unique drop from Dagannoth Kings','category' : 'Bosses','logName' : 'Dagannoth Kings','exclude' : {'Pet dagannoth prime', 'Pet dagannoth supreme', 'Pet dagannoth rex'},'db_count' : 7,'log_count' : 0},
{'taskName' : 'Get 1 unique drop from Grotesque Guardians','category' : 'Bosses','logName' : 'Grotesque Guardians','exclude' : {'Noon', 'Jar of stone','Granite dust'} ,'db_count' : 1,'log_count' : 0},
{'taskName' : 'Get 1 unique drop from Grotesque Guardians','category' : 'Bosses','logName' : 'Grotesque Guardians','exclude' : {'Noon', 'Jar of stone','Granite dust'} ,'db_count' : 2,'log_count' : 0},
{'taskName' : 'Get 1 unique drop from Grotesque Guardians','category' : 'Bosses','logName' : 'Grotesque Guardians','exclude' : {'Noon', 'Jar of stone','Granite dust'} ,'db_count' : 3,'log_count' : 0},
{'taskName' : 'Get 1 unique from the Kalphite Queen','category' : 'Bosses','logName' : 'Kalphite Queen','include' : {'Dragon chainbody', 'Kq head'},'db_count' : 1,'log_count' : 0},
{'taskName' : 'Get 1 unique from the Kalphite Queen','category' : 'Bosses','logName' : 'Kalphite Queen','include' : {'Dragon chainbody', 'Kq head'},'db_count' : 2,'log_count' : 0},
{'taskName' : 'Get Kbd heads','category' : 'Bosses','logName' : 'King Black Dragon','include' : {'Kbd heads'},'db_count' : 1,'log_count' : 0},
{'taskName' : 'Get 1 unique drop from Kraken','category' : 'Bosses','logName' : 'Kraken','exclude' : {'Pet kraken', 'Jar of dirt'},'db_count' : 1,'log_count' : 0},
{'taskName' : 'Get 1 unique drop from Kraken','category' : 'Bosses','logName' : 'Kraken','exclude' : {'Pet kraken', 'Jar of dirt'},'db_count' : 2,'log_count' : 0},
{'taskName' : 'Get an Uncharged Trident','category' : 'Other','logName' : 'Slayer','include' : {'Uncharged trident'},'db_count' : 1,'log_count' : 0},
{'taskName' : 'Get a unique shard 3','category' : 'Bosses','logName' : 'Scorpia','exclude' : {'Scorpia\'s offspring'},'db_count' : 1,'log_count' : 0},
{'taskName' : 'Get a unique shard 3','category' : 'Bosses','logName' : 'Scorpia','exclude' : {'Scorpia\'s offspring'},'db_count' : 2,'log_count' : 0},
{'taskName' : 'Get Vorkath\'s head','category' : 'Bosses','logName' : 'Vorkath','include' : {'Vorkath\'s head'},'db_count' : 1,'log_count' : 0},
{'taskName' : 'Get 1 unique from Zulrah','category' : 'Bosses','logName' : 'Zulrah','include' : {'Magic fang', 'Tanzanite fang', 'Uncut onyx', 'Serpentine visage'},'db_count' : 1,'log_count' : 0},
{'taskName' : 'Get 1 unique from Zulrah','category' : 'Bosses','logName' : 'Zulrah','include' : {'Magic fang', 'Tanzanite fang', 'Uncut onyx', 'Serpentine visage'},'db_count' : 2,'log_count' : 0},
{'taskName' : 'Get 1 unique from Zulrah','category' : 'Bosses','logName' : 'Zulrah','include' : {'Magic fang', 'Tanzanite fang', 'Uncut onyx', 'Serpentine visage'},'db_count' : 3,'log_count' : 0},
{'taskName' : 'Get 1 unique from Zulrah','category' : 'Bosses','logName' : 'Zulrah','include' : {'Magic fang', 'Tanzanite fang', 'Uncut onyx', 'Serpentine visage'},'db_count' : 4,'log_count' : 0},
{'taskName' : 'Get 3 new uniques from beginner clues','category' : 'Clues','logName' : 'Beginner Treasure Trails','exclude' : {'Black pickaxe'}, 'db_count' : 15,'log_count' : 0},
{'taskName' : 'Get 5 new uniques from easy clues','category' : 'Clues','logName' : 'Easy Treasure Trails','exclude' : {'N/A'},'db_count' : 65,'log_count' : 0},
{'taskName' : 'Get 5 new uniques from easy clues','category' : 'Clues','logName' : 'Easy Treasure Trails','exclude' : {'N/A'},'db_count' : 70,'log_count' : 0},
{'taskName' : 'Get 5 new uniques from easy clues','category' : 'Clues','logName' : 'Easy Treasure Trails','exclude' : {'N/A'},'db_count' : 75,'log_count' : 0},
{'taskName' : 'Get 5 new uniques from easy clues','category' : 'Clues','logName' : 'Easy Treasure Trails','exclude' : {'N/A'},'db_count' : 80,'log_count' : 0},
{'taskName' : 'Get 5 new uniques from easy clues','category' : 'Clues','logName' : 'Easy Treasure Trails','exclude' : {'N/A'},'db_count' : 85,'log_count' : 0},
{'taskName' : 'Get 5 new uniques from medium clues','category' : 'Clues','logName' : 'Medium Treasure Trails','exclude' : {'N/A'}, 'db_count' : 45,'log_count' : 0},
{'taskName' : 'Get 5 new uniques from medium clues','category' : 'Clues','logName' : 'Medium Treasure Trails','exclude' : {'N/A'}, 'db_count' : 50,'log_count' : 0},
{'taskName' : 'Get 5 new uniques from medium clues','category' : 'Clues','logName' : 'Medium Treasure Trails','exclude' : {'N/A'}, 'db_count' : 55,'log_count' : 0},
{'taskName' : 'Get 5 new uniques from medium clues','category' : 'Clues','logName' : 'Medium Treasure Trails','exclude' : {'N/A'}, 'db_count' : 60,'log_count' : 0},
{'taskName' : 'Get 5 new uniques from medium clues','category' : 'Clues','logName' : 'Medium Treasure Trails','exclude' : {'N/A'}, 'db_count' : 65,'log_count' : 0},
{'taskName' : 'Get 5 new uniques from hard clues','category' : 'Clues','logName' : 'Hard Treasure Trails','exclude' : {'N/A'}, 'db_count' : 35,'log_count' : 0},
{'taskName' : 'Get 5 new uniques from hard clues','category' : 'Clues','logName' : 'Hard Treasure Trails','exclude' : {'N/A'}, 'db_count' : 40,'log_count' : 0},
{'taskName' : 'Get 5 new uniques from hard clues','category' : 'Clues','logName' : 'Hard Treasure Trails','exclude' : {'N/A'}, 'db_count' : 45,'log_count' : 0},
{'taskName' : 'Get 5 new uniques from hard clues','category' : 'Clues','logName' : 'Hard Treasure Trails','exclude' : {'N/A'}, 'db_count' : 50,'log_count' : 0},
{'taskName' : 'Get 5 new uniques from hard clues','category' : 'Clues','logName' : 'Hard Treasure Trails','exclude' : {'N/A'}, 'db_count' : 55,'log_count' : 0},
{'taskName' : 'Get 5 new uniques from hard clues','category' : 'Clues','logName' : 'Hard Treasure Trails','exclude' : {'N/A'}, 'db_count' : 60,'log_count' : 0},
{'taskName' : 'Get 5 new uniques from hard clues','category' : 'Clues','logName' : 'Hard Treasure Trails','exclude' : {'N/A'}, 'db_count' : 65,'log_count' : 0},
{'taskName' : 'Get 2 new uniques from elite clues','category' : 'Clues','logName' : 'Elite Treasure Trails','exclude' : {'N/A'}, 'db_count' : 2,'log_count' : 0},
{'taskName' : 'Get 2 new uniques from elite clues','category' : 'Clues','logName' : 'Elite Treasure Trails','exclude' : {'N/A'}, 'db_count' : 4,'log_count' : 0},
{'taskName' : 'Get 2 new uniques from elite clues','category' : 'Clues','logName' : 'Elite Treasure Trails','exclude' : {'N/A'}, 'db_count' : 6,'log_count' : 0},
{'taskName' : 'Get 2 new uniques from elite clues','category' : 'Clues','logName' : 'Elite Treasure Trails','exclude' : {'N/A'}, 'db_count' : 8,'log_count' : 0},
{'taskName' : 'Get 2 new uniques from elite clues','category' : 'Clues','logName' : 'Elite Treasure Trails','exclude' : {'N/A'}, 'db_count' : 10,'log_count' : 0},
{'taskName' : 'Get 1 new halo','category' : 'Minigames','logName' : 'Castle Wars','include' : {'Saradomin halo', 'Zamorak halo', 'Guthix halo'},'db_count' : 3,'log_count' : 0},
{'taskName' : 'Get 1 new unique from Gnome Restaurant','category' : 'Minigames','logName' : 'Gnome Restaurant','exclude' : {'N/A'},'db_count' : 4,'log_count' : 0},
{'taskName' : 'Get an Infinity top','category' : 'Minigames','logName' : 'Magic Training Arena','include' : {'Infinity top'},'db_count' : 1,'log_count' : 0},
{'taskName' : 'Get Infinity bottoms','category' : 'Minigames','logName' : 'Magic Training Arena','include' : {'Infinity bottoms'},'db_count' : 1,'log_count' : 0},
{'taskName' : 'Get 2 White decorative pieces','category' : 'Minigames','logName' : 'Castle Wars', 'include' : {'Decorative helm', 'Decorative full helm', 'Decorative armour', 'Decorative sword', 'Decorative shield', 'Decorative boots'}, 'db_count' : 16,'log_count' : 0},
{'taskName' : 'Get 2 White decorative pieces','category' : 'Minigames','logName' : 'Castle Wars', 'include' : {'Decorative helm', 'Decorative full helm', 'Decorative armour', 'Decorative sword', 'Decorative shield', 'Decorative boots'}, 'db_count' : 18,'log_count' : 0},
{'taskName' : 'Get 2 White decorative pieces','category' : 'Minigames','logName' : 'Castle Wars', 'include' : {'Decorative helm', 'Decorative full helm', 'Decorative armour', 'Decorative sword', 'Decorative shield', 'Decorative boots'}, 'db_count' : 20,'log_count' : 0},
{'taskName' : 'Get 2 White decorative pieces','category' : 'Minigames','logName' : 'Castle Wars', 'include' : {'Decorative helm', 'Decorative full helm', 'Decorative armour', 'Decorative sword', 'Decorative shield', 'Decorative boots'}, 'db_count' : 22,'log_count' : 0},
{'taskName' : 'Get an Elite void top','category' : 'Minigames','logName' : 'Pest Control','include' : {'Elite void top'},'db_count' : 1,'log_count' : 0},
{'taskName' : 'Get an Elite void robe','category' : 'Minigames','logName' : 'Pest Control','include' : {'Elite void robe'},'db_count' : 1,'log_count' : 0},
{'taskName' : 'Get 1 Naval set','category' : 'Minigames','logName' : 'Trouble Brewing','exclude' : {'Cutthroat flag', 'Gilded smile flag', 'Bronze fist flag', 'Lucky shot flag', 'Treasure flag', 'Phasmatys flag', 'The stuff', 'rum'},'db_count' : 9,'log_count' : 0},
{'taskName' : 'Get 1 Naval set','category' : 'Minigames','logName' : 'Trouble Brewing','exclude' : {'Cutthroat flag', 'Gilded smile flag', 'Bronze fist flag', 'Lucky shot flag', 'Treasure flag', 'Phasmatys flag', 'The stuff', 'rum'},'db_count' : 12,'log_count' : 0},
{'taskName' : 'Get 1 Naval set','category' : 'Minigames','logName' : 'Trouble Brewing','exclude' : {'Cutthroat flag', 'Gilded smile flag', 'Bronze fist flag', 'Lucky shot flag', 'Treasure flag', 'Phasmatys flag', 'The stuff', 'rum'},'db_count' : 15,'log_count' : 0},
{'taskName' : 'Get the Bronze fist flag','category' : 'Minigames','logName' : 'Trouble Brewing','include' : {'Bronze fist flag'},'db_count' : 1,'log_count' : 0},
{'taskName' : 'Get the Lucky shot flag','category' : 'Minigames','logName' : 'Trouble Brewing','include' : {'Lucky shot flag'},'db_count' : 1,'log_count' : 0},
{'taskName' : 'Get 1 unique Champion scroll','category' : 'Other','logName' : 'Champion\'s Challenge','exclude' : {'Champion\'s cape'},'db_count' : 4,'log_count' : 0},
{'taskName' : 'Get 1 unique Champion scroll','category' : 'Other','logName' : 'Champion\'s Challenge','exclude' : {'Champion\'s cape'},'db_count' : 5,'log_count' : 0},
{'taskName' : 'Get 1 unique Champion scroll','category' : 'Other','logName' : 'Champion\'s Challenge','exclude' : {'Champion\'s cape'},'db_count' : 6,'log_count' : 0},
{'taskName' : 'Get 1 unique Elder chaos robe piece','category' : 'Other','logName' : 'Chaos Druids','exclude' : {'N/A'},'db_count' : 3,'log_count' : 0},
{'taskName' : 'Get the Ogre expert headpiece','category' : 'Other','logName' : 'Chompy Bird Hunting','exclude': {'Chompy chick'}, 'db_count' : 13,'log_count' : 0},
{'taskName' : 'Get a unique from Demonic gorillas','category' : 'Other','logName' : 'Glough\'s Experiments','exclude' : {'N/A'},'db_count' : 1,'log_count' : 0},
{'taskName' : 'Get a unique from Demonic gorillas','category' : 'Other','logName' : 'Glough\'s Experiments','exclude' : {'N/A'},'db_count' : 2,'log_count' : 0},
{'taskName' : 'Get a unique from Demonic gorillas','category' : 'Other','logName' : 'Glough\'s Experiments','exclude' : {'N/A'},'db_count' : 3,'log_count' : 0},
{'taskName' : 'Get a unique from Demonic gorillas','category' : 'Other','logName' : 'Glough\'s Experiments','exclude' : {'N/A'},'db_count' : 4,'log_count' : 0},
{'taskName' : 'Get 2 unique Ancient pages','category' : 'Other','logName' : 'My Notes', 'exclude' : {'N/A'}, 'db_count' : 18,'log_count' : 0},
{'taskName' : 'Get 2 unique Ancient pages','category' : 'Other','logName' : 'My Notes', 'exclude' : {'N/A'}, 'db_count' : 20,'log_count' : 0},
{'taskName' : 'Get 2 unique Ancient pages','category' : 'Other','logName' : 'My Notes', 'exclude' : {'N/A'}, 'db_count' : 22,'log_count' : 0},
{'taskName' : 'Get a Kurask head','category' : 'Other','logName' : 'Slayer','include' : {'Kurask head'},'db_count' : 1,'log_count' : 0},
{'taskName' : 'Get Dragon boots','category' : 'Other','logName' : 'Slayer','include' : {'Dragon boots'},'db_count' : 1,'log_count' : 0},
{'taskName' : 'Get a Dark bow','category' : 'Other','logName' : 'Slayer','include' : {'Dark bow'},'db_count' : 1,'log_count' : 0},
{'taskName' : 'Get 1 unique from Thermonuclear smoke devil','category' : 'Bosses','logName' : 'Thermonuclear Smoke Devil','include' : {'Occult necklace', 'Smoke battlestaff'},'db_count' : 1,'log_count' : 0},
{'taskName' : 'Get 1 unique Obsidian armour drop','category' : 'Other','logName' : 'TzHaar','include' : {'Obsidian helmet', 'Obsidian platebody', 'Obsidian platelegs'},'db_count' : 1,'log_count' : 0},
{'taskName' : 'Get 1 unique Obsidian armour drop','category' : 'Other','logName' : 'TzHaar','include' : {'Obsidian helmet', 'Obsidian platebody', 'Obsidian platelegs'},'db_count' : 2,'log_count' : 0},
{'taskName' : 'Get a Dragon warhammer','category' : 'Other','logName' : 'Miscellaneous','include' : {'Dragon warhammer'},'db_count' : 1,'log_count' : 0},
{'taskName' : 'Get a Pharaoh\'s sceptre','category' : 'Other','logName' : 'Miscellaneous','include' : {'Pharaoh\'s sceptre (uncharged)'},'db_count' : 1,'log_count' : 0},
{'taskName' : 'Get Chewed bones','category' : 'Other','logName' : 'Miscellaneous','include' : {'Chewed bones'},'db_count' : 1,'log_count' : 0},
{'taskName' : 'Get a Dragon spear','category' : 'Other','logName' : 'Miscellaneous','include' : {'Dragon spear'},'db_count' : 1,'log_count' : 0},
{'taskName' : 'Get Expert mining gloves','category' : 'Other','logName' : 'Miscellaneous','include' : {'Expert mining gloves'},'db_count' : 1,'log_count' : 0},
{'taskName' : 'Get Bryophyta\'s essence','category' : 'Bosses','logName' : 'Bryophyta','exclude' : {'N/A'},'db_count' : 1,'log_count' : 0},
{'taskName' : 'Get a Sarachnis Cudgel','category' : 'Bosses','logName' : 'Sarachnis','include' : {'Sarachnis cudgel'},'db_count' : 1,'log_count' : 0},
{'taskName' : 'Get 1 unique from the Gauntlet','category' : 'Bosses','logName' : 'The Gauntlet','exclude' : {'Youngllef', 'Gauntlet cape'},'db_count' : 1,'log_count' : 0},
{'taskName' : 'Get 1 unique from the Gauntlet','category' : 'Bosses','logName' : 'The Gauntlet','exclude' : {'Youngllef', 'Gauntlet cape'},'db_count' : 2,'log_count' : 0},
{'taskName' : 'Get the Elven signet','category' : 'Other','logName' : 'Miscellaneous','include' : {'Elven signet'},'db_count' : 1,'log_count' : 0},
{'taskName' : 'Get an Enhanced crystal teleport seed','category' : 'Other','logName' : 'Miscellaneous','include' : {'Enhanced crystal teleport seed'},'db_count' : 1,'log_count' : 0},
{'taskName' : 'Get the Basilisk jaw','category' : 'Other','logName' : 'Slayer','include' : {'Basilisk jaw'},'db_count' : 1,'log_count' : 0},
{'taskName' : 'Get a shield left half','category' : 'Other','logName' : 'Miscellaneous','include' : {'Shield left half'},'db_count' : 1,'log_count' : 0},
{'taskName' : 'Get a Pirate\'s hook','category' : 'Minigames','logName' : 'Brimhaven Agility Arena','include' : {'Pirate\'s hook'},'db_count' : 1,'log_count' : 0},
{'taskName' : 'Get 2 uniques from the Hallowed Sepulchre','category' : 'Minigames','logName' : 'Hallowed Sepulchre','exclude' : {'N/A'},'db_count' : 2, 'log_count' : 0},
{'taskName' : 'Get 2 uniques from the Hallowed Sepulchre','category' : 'Minigames','logName' : 'Hallowed Sepulchre','exclude' : {'N/A'},'db_count' : 4, 'log_count' : 0},
{'taskName' : 'Get 2 uniques from the Hallowed Sepulchre','category' : 'Minigames','logName' : 'Hallowed Sepulchre','exclude' : {'N/A'},'db_count' : 6, 'log_count' : 0},
{'taskName' : 'Get 2 uniques from the Hallowed Sepulchre','category' : 'Minigames','logName' : 'Hallowed Sepulchre','exclude' : {'N/A'},'db_count' : 8, 'log_count' : 0},
{'taskName' : 'Get 2 uniques from the Hallowed Sepulchre','category' : 'Minigames','logName' : 'Hallowed Sepulchre','exclude' : {'N/A'},'db_count' : 10, 'log_count' : 0},
{'taskName' : 'Get 2 uniques from the Hallowed Sepulchre','category' : 'Minigames','logName' : 'Hallowed Sepulchre','exclude' : {'N/A'},'db_count' : 12, 'log_count' : 0},
{'taskName' : 'Unlock 2 monkey backpack transformations','category' : 'Other','logName' : 'Monkey Backpacks', 'exclude' : {'N/A'},'db_count' : 2,'log_count' : 0},
{'taskName' : 'Unlock 2 monkey backpack transformations','category' : 'Other','logName' : 'Monkey Backpacks', 'exclude' : {'N/A'},'db_count' : 4,'log_count' : 0},
{'taskName' : 'Unlock 2 monkey backpack transformations','category' : 'Other','logName' : 'Monkey Backpacks', 'exclude' : {'N/A'},'db_count' : 6,'log_count' : 0},
{'taskName' : 'Get Amy\'s saw','category' : 'Minigames','logName' : 'Mahogany Homes','include' : {'Amy\'s saw'},'db_count' : 1,'log_count' : 0},
{'taskName' : 'Get 1 piece of Carpenter equipment','category' : 'Minigames','logName' : 'Mahogany Homes','exclude' : {'Supply crate', 'Amy\'s saw', 'Plank sack', 'Hosidius blueprints'},'db_count' : 3,'log_count' : 0},
{'taskName' : 'Get 1 piece of Carpenter equipment','category' : 'Minigames','logName' : 'Mahogany Homes','exclude' : {'Supply crate', 'Amy\'s saw', 'Plank sack', 'Hosidius blueprints'},'db_count' : 4,'log_count' : 0},
{'taskName' : 'Get a Blood shard','category' : 'Other','logName' : 'Slayer','include' : {'Blood shard'},'db_count' : 1,'log_count' : 0},
{'taskName' : 'Get a Soul cape','category' : 'Minigames','logName' : 'Soul Wars','include' : {'Soul cape'},'db_count' : 1,'log_count' : 0},
{'taskName' : 'Get 1 unique from Shades of Mort\'ton','category' : 'Minigames','logName' : 'Shades of Mort\'ton','exclude' : {'N/A'},'db_count' : 6,'log_count' : 0},
{'taskName' : 'Get 1 unique from Shades of Mort\'ton','category' : 'Minigames','logName' : 'Shades of Mort\'ton','exclude' : {'N/A'},'db_count' : 7,'log_count' : 0},
{'taskName' : 'Get the Brimhaven graceful set recolour','category' : 'Minigames','logName' : 'Brimhaven Agility Arena', 'exclude': {'Agility arena ticket', 'Pirate\'s hook'},'db_count' : 6,'log_count' : 0},
{'taskName' : 'Get a Volcanic mine teleport','category' : 'Minigames','logName' : 'Volcanic Mine','include' : {'Volcanic mine teleport'},'db_count' : 1,'log_count' : 0},
{'taskName' : 'Get a Heat-proof vessel','category' : 'Minigames','logName' : 'Volcanic Mine','include' : {'Large water container'},'db_count' : 1,'log_count' : 0},
None,
{'taskName' : 'Get 1 unique from Tempoross','category' : 'Bosses','logName' : 'Tempoross','exclude' : {'Dragon harpoon', 'Tiny tempor'},'db_count' : 10,'log_count' : 0},
{'taskName' : 'Get a Vial of blood (from Story mode ToB)','category' : 'Raids','logName' : 'Theatre of Blood','include' : {'Vial of blood'},'db_count' : 1,'log_count' : 0},
{'taskName' : 'Get a unique Egg Sac from the Grubby Chest','category' : 'Other','logName' : 'Miscellaneous','include' : {'Orange egg sac', 'Blue egg sac'},'db_count' : 1,'log_count' : 0},
{'taskName' : 'Get a unique Egg Sac from the Grubby Chest','category' : 'Other','logName' : 'Miscellaneous','include' : {'Orange egg sac', 'Blue egg sac'},'db_count' : 2,'log_count' : 0},
{'taskName' : 'Get 1 unique Nihil shard / Ceremonial robe piece','category' : 'Other','logName' : 'Slayer','include' : {'Ancient ceremonial mask', 'Ancient ceremonial top', 'Ancient ceremonial legs', 'Ancient ceremonial gloves', 'Ancient ceremonial boots'},'db_count' : 1,'log_count' : 0},
{'taskName' : 'Get 1 unique Nihil shard / Ceremonial robe piece','category' : 'Other','logName' : 'Slayer','include' : {'Ancient ceremonial mask', 'Ancient ceremonial top', 'Ancient ceremonial legs', 'Ancient ceremonial gloves', 'Ancient ceremonial boots'},'db_count' : 2,'log_count' : 0},
{'taskName' : 'Get 1 unique Nihil shard / Ceremonial robe piece','category' : 'Other','logName' : 'Slayer','include' : {'Ancient ceremonial mask', 'Ancient ceremonial top', 'Ancient ceremonial legs', 'Ancient ceremonial gloves', 'Ancient ceremonial boots'},'db_count' : 3,'log_count' : 0},
{'taskName' : 'Get 1 unique Nihil shard / Ceremonial robe piece','category' : 'Other','logName' : 'Slayer','include' : {'Ancient ceremonial mask', 'Ancient ceremonial top', 'Ancient ceremonial legs', 'Ancient ceremonial gloves', 'Ancient ceremonial boots'},'db_count' : 4,'log_count' : 0},
{'taskName' : 'Get 1 unique Nihil shard / Ceremonial robe piece','category' : 'Other','logName' : 'Slayer','include' : {'Ancient ceremonial mask', 'Ancient ceremonial top', 'Ancient ceremonial legs', 'Ancient ceremonial gloves', 'Ancient ceremonial boots'},'db_count' : 5,'log_count' : 0},
{'taskName' : 'Get 1 unique Nihil shard / Ceremonial robe piece','category' : 'Bosses','logName' : 'Nex','include' : {'Nihil shard'},'db_count' : 1,'log_count' : 0},
{'taskName' : 'Get 1 unique from Guardians of the Rift','category' : 'Minigames','logName' : 'Guardians of the Rift','exclude' : {'Abyssal protector'},'db_count' : 9,'log_count' : 0},
{'taskName' : 'Get 1 unique from Guardians of the Rift','category' : 'Minigames','logName' : 'Guardians of the Rift','exclude' : {'Abyssal protector'},'db_count' : 10,'log_count' : 0},
{'taskName' : 'Get 1 unique from Guardians of the Rift','category' : 'Minigames','logName' : 'Guardians of the Rift','exclude' : {'Abyssal protector'},'db_count' : 11,'log_count' : 0},
{'taskName' : 'Get 1 unique from Guardians of the Rift','category' : 'Minigames','logName' : 'Guardians of the Rift','exclude' : {'Abyssal protector'},'db_count' : 12,'log_count' : 0},
{'taskName' : 'Get a Colossal blade','category' : 'Minigames','logName' : 'Giants\' Foundry','include' : {'Colossal blade'},'db_count' : 1,'log_count' : 0},
{'taskName' : 'Get 1 unique from Tombs of Amascut','category' : 'Raids','logName' : 'Tombs of Amascut','exclude' : {'Tuemaken\'s guardian', 'Menaphite ornament kit', 'Cursed phalanx', 'Masori crafting kit', 'Icthlarin\'s shroud (tier 1)', 'Icthlarin\'s shroud (tier 2)', 'Icthlarin\'s shroud (tier 3)', 'Icthlarin\'s shroud (tier 4)', 'Icthlarin\'s shroud (tier 5)', 'Remnant of akkha', 'Remnant of ba-ba', 'Remnant of kephri', 'Remnant of zebak', 'Ancient remnant'},'db_count' : 1,'log_count' : 0},
{'taskName' : 'Get 1 unique from Tombs of Amascut','category' : 'Raids','logName' : 'Tombs of Amascut','exclude' : {'Tuemaken\'s guardian', 'Menaphite ornament kit', 'Cursed phalanx', 'Masori crafting kit', 'Icthlarin\'s shroud (tier 1)', 'Icthlarin\'s shroud (tier 2)', 'Icthlarin\'s shroud (tier 3)', 'Icthlarin\'s shroud (tier 4)', 'Icthlarin\'s shroud (tier 5)', 'Remnant of akkha', 'Remnant of ba-ba', 'Remnant of kephri', 'Remnant of zebak', 'Ancient remnant'},'db_count' : 2,'log_count' : 0},
{'taskName' : 'Get 1 unique from the Phantom Muspah','category' : 'Bosses','logName' : 'Phantom Muspah', 'exclude' : {'Muphin', 'Charged ice'}, 'db_count' : 1, 'log_count' : 0},
{'taskName' : 'Get 1 unique from the Phantom Muspah','category' : 'Bosses','logName' : 'Phantom Muspah', 'exclude' : {'Muphin', 'Charged ice'}, 'db_count' : 2, 'log_count' : 0},
{'taskName' : 'Get 1 unique from Forestry', 'category' : 'Other', 'logName' : 'Forestry', 'exclude' : {'Pheasant hat', 'Pheasant legs', 'Pheasant boots', 'Pheasant cape', 'Lumberjack hat', 'Lumberjack top', 'Lumberjack legs', 'Lumberjack boots'}, 'db_count' : 6, 'log_count': 0},
{'taskName' : 'Get 1 unique from Forestry', 'category' : 'Other', 'logName' : 'Forestry', 'exclude' : {'Pheasant hat', 'Pheasant legs', 'Pheasant boots', 'Pheasant cape', 'Lumberjack hat', 'Lumberjack top', 'Lumberjack legs', 'Lumberjack boots'}, 'db_count' : 7, 'log_count': 0},
{'taskName' : 'Get 1 unique from Forestry', 'category' : 'Other', 'logName' : 'Forestry', 'exclude' : {'Pheasant hat', 'Pheasant legs', 'Pheasant boots', 'Pheasant cape', 'Lumberjack hat', 'Lumberjack top', 'Lumberjack legs', 'Lumberjack boots'}, 'db_count' : 8, 'log_count': 0},
{'taskName' : "Get 1 unique from Moons of Peril bosses", 'category' : 'Bosses', 'logName': 'Moons of Peril', 'exclude' : {"N/A"}, 'db_count' : 5, 'log_count' : 0},
{'taskName' : "Get 1 unique from Moons of Peril bosses", 'category' : 'Bosses', 'logName': 'Moons of Peril', 'exclude' : {"N/A"}, 'db_count' : 6, 'log_count' : 0},
{'taskName' : "Get 1 unique from Moons of Peril bosses", 'category' : 'Bosses', 'logName': 'Moons of Peril', 'exclude' : {"N/A"}, 'db_count' : 7, 'log_count' : 0},
{'taskName' : "Get 1 unique from Moons of Peril bosses", 'category' : 'Bosses', 'logName': 'Moons of Peril', 'exclude' : {"N/A"}, 'db_count' : 8, 'log_count' : 0},
{'taskName' : "Get 1 unique from Moons of Peril bosses", 'category' : 'Bosses', 'logName': 'Moons of Peril', 'exclude' : {"N/A"}, 'db_count' : 9, 'log_count' : 0},
{'taskName' : "Get 1 unique from Moons of Peril bosses", 'category' : 'Bosses', 'logName': 'Moons of Peril', 'exclude' : {"N/A"}, 'db_count' : 10, 'log_count' : 0},
{'taskName' : "Get 1 unique from the Hunter Guild", 'category' : 'Other', 'logName': 'Hunter Guild', 'exclude' : {'Quetzin'}, 'db_count' : 3, 'log_count' : 0},
{'taskName' : "Get 1 unique from the Hunter Guild", 'category' : 'Other', 'logName': 'Hunter Guild', 'exclude' : {'Quetzin'}, 'db_count' : 4, 'log_count' : 0},
{'taskName' : "Get 1 unique from the Hunter Guild", 'category' : 'Other', 'logName': 'Hunter Guild', 'exclude' : {'Quetzin'}, 'db_count' : 5, 'log_count' : 0},
{'taskName' : "Obtain Sunfire splinters", 'category' : 'Bosses', 'logName': 'Fortis Colosseum', 'include' : {'Sunfire splinters'}, 'db_count' : 1, 'log_count' : 0},
]

















