import tasklists

easy = [
{'Get bolt racks from Barrows': 'Bolt_rack_5.png', 'LMS': False},
{'Get a Mole claw + skin': 'Mole_claw.png', 'LMS': False},
{'Get 1 Unique from Wintertodt': 'Pyromancer_hood.png', 'LMS': False},
{'Get 1 Unique from Wintertodt': 'Pyromancer_hood.png', 'LMS': False},
{'Get 1 Unique from Wintertodt': 'Pyromancer_hood.png', 'LMS': False},
{'Get 1 Unique from Wintertodt': 'Pyromancer_hood.png', 'LMS': False},
{'Get 1 Unique from Wintertodt': 'Pyromancer_hood.png', 'LMS': False},
{'Get 3 new uniques from beginner clues': 'Clue_scroll_beginner.png', 'LMS': False},
{'Get 3 new uniques from beginner clues': 'Clue_scroll_beginner.png', 'LMS': False},
{'Get 5 new uniques from easy clues': 'Clue_scroll_easy.png', 'LMS': False},
{'Get 5 new uniques from easy clues': 'Clue_scroll_easy.png', 'LMS': False},
{'Get 5 new uniques from easy clues': 'Clue_scroll_easy.png', 'LMS': False},
{'Get 5 new uniques from easy clues': 'Clue_scroll_easy.png', 'LMS': False},
{'Get 5 new uniques from easy clues': 'Clue_scroll_easy.png', 'LMS': False},
{'Get 5 new uniques from easy clues': 'Clue_scroll_easy.png', 'LMS': False},
{'Get 5 new uniques from medium clues': 'Clue_scroll_medium.png', 'LMS': False},
{'Get 5 new uniques from medium clues': 'Clue_scroll_medium.png', 'LMS': False},
{'Get 5 new uniques from medium clues': 'Clue_scroll_medium.png', 'LMS': False},
{'Get 5 new uniques from medium clues': 'Clue_scroll_medium.png', 'LMS': False},
{'Get 5 new uniques from hard clues': 'Clue_scroll_hard.png', 'LMS': False},
{'Get 5 new uniques from hard clues': 'Clue_scroll_hard.png', 'LMS': False},
{'Get Runner boots': 'Runner_boots.png', 'LMS': False},
{'Get Penance gloves': 'Penance_gloves.png', 'LMS': False},
{'Get a Granite body': 'Granite_body.png', 'LMS': False},
{'Get 1 new halo': 'Saradomin_halo.png', 'LMS': False},
{'Get the full Red decorative set': '130px-Decorative_armour_red_platebody_detail.png', 'LMS': False},
{'Get the Zamorak hood & cloak': 'Castlewars_hood_Zamorak.png', 'LMS': False},
{'Get the Saradomin hood & cloak': 'Castlewars_hood_Saradomin.png', 'LMS': False},
{'Get 1 Angler piece': 'Angler_top.png', 'LMS': False},
{'Get 1 Angler piece': 'Angler_top.png', 'LMS': False},
{'Get 1 Angler piece': 'Angler_top.png', 'LMS': False},
{'Get 1 Angler piece': 'Angler_top.png', 'LMS': False},
{'Get 1 new unique from Gnome Restaurant': 'Gnome_scarf.png', 'LMS': False},
{'Get a Beginner wand': 'Beginner_wand.png', 'LMS': False},
{'Unlock bones to peaches': 'Bones_to_Peaches.png', 'LMS': False},
{'Get Infinity boots': 'Infinity_boots.png', 'LMS': False},
{'Get Infinity gloves': 'Infinity_gloves.png', 'LMS': False},
{'Get a Void Knight seal': 'Void_seal.png', 'LMS': False},
{'Get Void Knight gloves': 'Void_knight_gloves.png', 'LMS': False},
{'Get a Void Knight mace': 'Void_knight_mace.png', 'LMS': False},
{'Get 1 piece of Rogue equipment': 'Rogue_top.png', 'LMS': False},
{'Get 1 piece of Rogue equipment': 'Rogue_top.png', 'LMS': False},
{"Get 1 unique from Shades of Mort'ton": 'Fine_cloth.png', 'LMS': False},
{"Get 1 unique from Shades of Mort'ton": 'Fine_cloth.png', 'LMS': False},
{'Get 1 piece of Lumberjack equipment': 'Lumberjack_top.png', 'LMS': False},
{"Get the Gricoller's can": 'Gricollers_can.png', 'LMS': False},
{"Get 1 piece of Farmer's equipment": 'Farmers_jacket.png', 'LMS': False},
{'Get Blue Rum': 'Rum_blue.png', 'LMS': False},
{'Get Red Rum': 'Rum_red.png', 'LMS': False},
{'Get The stuff': 'The_stuff.png', 'LMS': False},
{'Get the Pearl fishing rod': 'Pearl_fishing_rod.png', 'LMS': False},
{'Get 1 unique Champion scroll': 'Goblin_champion_scroll.png', 'LMS': False},
{'Get the Marksman headpiece': 'Chompy_bird_hat_marksman.png', 'LMS': False},
{'Get a Tea flask': 'Tea_flask.png', 'LMS': False},
{'Get a Rune satchel': 'Rune_satchel.png', 'LMS': False},
{'Get a Green satchel': 'Green_satchel.png', 'LMS': False},
{'Get a Red satchel': 'Red_satchel.png', 'LMS': False},
{'Get a Black satchel': 'Black_satchel.png', 'LMS': False},
{'Get a Rune defender': 'Rune_defender.png', 'LMS': False},
{'Get 2 unique notes from Fossil Island': 'Scribbled_note.png', 'LMS': False},
{'Get 2 unique notes from Fossil Island': 'Scribbled_note.png', 'LMS': False},
{'Get 1 piece of Prospector equipment': 'Prospector_helmet.png', 'LMS': False},
{'Get 1 piece of Prospector equipment': 'Prospector_helmet.png', 'LMS': False},
{'Get 1 piece of Prospector equipment': 'Prospector_helmet.png', 'LMS': False},
{'Get 1 piece of Prospector equipment': 'Prospector_helmet.png', 'LMS': False},
{'Get 2 unique Ancient pages': 'Ancient_page.png', 'LMS': False},
{'Get 2 unique Ancient pages': 'Ancient_page.png', 'LMS': False},
{'Get Revenant ether': 'Revenant_ether_5.png', 'LMS': False},
{'Get 1 piece of Graceful equipment': 'Graceful_top.png', 'LMS': False},
{'Get 1 piece of Graceful equipment': 'Graceful_top.png', 'LMS': False},
{'Get 1 piece of Graceful equipment': 'Graceful_top.png', 'LMS': False},
{'Get a Crawling hand': '140px-Crawling_hand_item_detail.png', 'LMS': False},
{'Get a Cockatrice head': '170px-Cockatrice_head_detail.png', 'LMS': False},
{'Get 1 unique from Mogres': 'Mudskipper_hat.png', 'LMS': False},
{'Get 1 unique from Mogres': 'Mudskipper_hat.png', 'LMS': False},
{'Get a Brine sabre': 'Brine_sabre.png', 'LMS': False},
{'Get 1 unique from Turoths': 'Leaf-bladed_sword.png', 'LMS': False},
{'Get 1 unique from Turoths': 'Leaf-bladed_sword.png', 'LMS': False},
{'Get a Black mask': 'Black_mask.png', 'LMS': False},
{'Get the next tier of metal boots': 'Bronze_boots.png', 'LMS': False},
{'Get the next tier of metal boots': 'Bronze_boots.png', 'LMS': False},
{'Get the next tier of metal boots': 'Bronze_boots.png', 'LMS': False},
{'Get the next tier of metal boots': 'Bronze_boots.png', 'LMS': False},
{'Get the next tier of metal boots': 'Bronze_boots.png', 'LMS': False},
{'Get a Mystic hat (light)': 'Mystic_hat_light.png', 'LMS': False},
{'Get Mystic gloves (light)': 'Mystic_gloves_light.png', 'LMS': False},
{'Get Mystic boots (light)': 'Mystic_boots_light.png', 'LMS': False},
{'Get 1 unique from Infernal Mages': 'Mystic_hat_dark.png', 'LMS': False},
{'Get 1 unique from Infernal Mages': 'Mystic_hat_dark.png', 'LMS': False},
{'Get Mystic gloves (dark)': 'Mystic_gloves_dark.png', 'LMS': False},
{'Get 1 unique Tzhaar drop': 'Obsidian_cape.png', 'LMS': False},
{'Get 1 unique Tzhaar drop': 'Obsidian_cape.png', 'LMS': False},
{'Get a Big swordfish': 'Big_swordfish.png', 'LMS': False},
{'Get a Big bass': 'Big_bass.png', 'LMS': False},
{'Get a Long bone': 'Long_bone.png', 'LMS': False},
{'Get an Ecumenical key': 'Ecumenical_key.png', 'LMS': False},
{'Get 1 unique Dark totem piece / Ancient shard': 'Dark_totem_base.png', 'LMS': False},
{'Get 1 unique Dark totem piece / Ancient shard': 'Dark_totem_base.png', 'LMS': False},
{'Get 1 unique Dark totem piece / Ancient shard': 'Dark_totem_base.png', 'LMS': False},
{'Get 1 unique Dark totem piece / Ancient shard': 'Dark_totem_base.png', 'LMS': False},
{'Get Mining gloves': 'Mining_gloves.png', 'LMS': False},
{'Get a Right skull half': 'Right_skull_half.png', 'LMS': False},
{'Get a Left skull half': 'Left_skull_half.png', 'LMS': False},
{'Get a Top of sceptre': 'Top_of_sceptre.png', 'LMS': False},
{'Get a Bottom of sceptre': 'Bottom_of_sceptre.png', 'LMS': False},
{'Get a Mossy key': 'Mossy_key.png', 'LMS': False},
{'Get a Giant key': 'Giant_key.png', 'LMS': False},
{'Get a Fresh crab claw & Fresh crab shell': 'Fresh_crab_claw.png', 'LMS': False},
{"Get a Xeric's talisman (inert)": 'Xerics_talisman_inert.png', 'LMS': False},
{'Complete the Ardougne Easy Diary': 'Achievement_Diaries_icon.png', 'LMS': False},
{'Complete the Desert Easy Diary': 'Achievement_Diaries_icon.png', 'LMS': False},
{'Complete the Falador Easy Diary': 'Achievement_Diaries_icon.png', 'LMS': False},
{'Complete the Fremennik Easy Diary': 'Achievement_Diaries_icon.png', 'LMS': False},
{'Complete the Kandarin Easy Diary': 'Achievement_Diaries_icon.png', 'LMS': False},
{'Complete the Karamja Easy Diary': 'Achievement_Diaries_icon.png', 'LMS': False},
{'Complete the Kourend&Kebos Easy Diary': 'Achievement_Diaries_icon.png', 'LMS': False},
{'Complete the Lumbridge&Draynor Easy Diary': 'Achievement_Diaries_icon.png', 'LMS': False},
{'Complete the Morytania Easy Diary': 'Achievement_Diaries_icon.png', 'LMS': False},
{'Complete the Varrock Easy Diary': 'Achievement_Diaries_icon.png', 'LMS': False},
{'Complete the Western Provinces Easy Diary': 'Achievement_Diaries_icon.png', 'LMS': False},
{'Complete the Wilderness Easy Diary': 'Achievement_Diaries_icon.png', 'LMS': False},
{'Get a Supply crate from Mahogany Homes': '1024px-Supply_crate_Mahogany_Homes_detail.png', 'LMS': False},
{'Get 1 unique from Tempoross': '160px-Tome_of_water_empty_detail.png', 'LMS': False},
{'Get 1 unique from Tempoross': '160px-Tome_of_water_empty_detail.png', 'LMS': False},
{'Get 1 unique from Tempoross': '160px-Tome_of_water_empty_detail.png', 'LMS': False},
{'Get 1 unique from Tempoross': '160px-Tome_of_water_empty_detail.png', 'LMS': False},
{'Get 5 unique items at Camdozaal': '130px-Barronite_mace_detail.png', 'LMS': False},
{'Get 5 unique items at Camdozaal': '130px-Barronite_mace_detail.png', 'LMS': False},
{'Get 1 unique from Guardians of the Rift': 'Hat_of_the_eye_detail.png', 'LMS': False},
{'Get 1 unique from Guardians of the Rift': 'Hat_of_the_eye_detail.png', 'LMS': False},
{'Get 1 unique from Guardians of the Rift': 'Hat_of_the_eye_detail.png', 'LMS': False},
{'Get 1 unique from Guardians of the Rift': 'Hat_of_the_eye_detail.png', 'LMS': False},
{"Get 1 unique from Giants' Foundry": "Kovac's_grog_detail.png", 'LMS': False},
{"Get 1 unique from Giants' Foundry": "Kovac's_grog_detail.png", 'LMS': False},
{"Get 1 unique from Giants' Foundry": "Kovac's_grog_detail.png", 'LMS': False},
{"Get 1 unique from Giants' Foundry": "Kovac's_grog_detail.png", 'LMS': False},
{"Get 1 unique from Forestry" : "forestry_kit.png", 'LMS' : False},
{"Get the full Pheasant costume" : "Pheasant_hat.png", 'LMS' : False},
{"Get the Sturdy beehive parts" : "Sturdy_beehive_parts_detail.png", 'LMS' : False},
{"Get a Warped sceptre" : "warped_sceptre.png", 'LMS' : False},
{"Get 1 unique from the Hunter Guild" : "huntsman_kit.png", 'LMS' : False},
{"Get the Sulphur blades" : "sulphur_blades.png", 'LMS' : False}
]

medium = [
{'Get 1 unique from Barrows': 'Guthans_helm.png', 'LMS': False},
{'Get 1 unique from Barrows': 'Guthans_helm.png', 'LMS': False},
{'Get 1 unique from Barrows': 'Guthans_helm.png', 'LMS': False},
{'Get 1 unique from Barrows': 'Guthans_helm.png', 'LMS': False},
{'Get 1 unique from Barrows': 'Guthans_helm.png', 'LMS': False},
{'Get 1 unique from Crazy Archeologist': 'Fedora.png', 'LMS': False},
{'Get 1 unique from Crazy Archeologist': 'Fedora.png', 'LMS': False},
{'Get 1 unique from Crazy Archeologist': 'Fedora.png', 'LMS': False},
{'Get a Fire cape': 'Fire_cape.png', 'LMS': False},
{'Get Granite dust': 'Granite_dust.png', 'LMS': False},
{'Get a Hill giant club': 'Hill_giant_club.png', 'LMS': False},
{'Get 1 Unique from Wintertodt': 'Pyromancer_hood.png', 'LMS': False},
{'Get 1 Unique from Wintertodt': 'Pyromancer_hood.png', 'LMS': False},
{'Get 1 Unique from Wintertodt': 'Pyromancer_hood.png', 'LMS': False},
{"Get 1 Unique from Zulrah": 'Zulrahs_scales_5.png', 'LMS': False},
{'Get 1 Unique from Zulrah': 'Zulrahs_scales_5.png', 'LMS': False},
{'Get 3 new uniques from beginner clues': 'Clue_scroll_beginner.png', 'LMS': False},
{'Get 3 new uniques from beginner clues': 'Clue_scroll_beginner.png', 'LMS': False},
{'Get 5 new uniques from easy clues': 'Clue_scroll_easy.png', 'LMS': False},
{'Get 5 new uniques from easy clues': 'Clue_scroll_easy.png', 'LMS': False},
{'Get 5 new uniques from easy clues': 'Clue_scroll_easy.png', 'LMS': False},
{'Get 5 new uniques from easy clues': 'Clue_scroll_easy.png', 'LMS': False},
{'Get 5 new uniques from easy clues': 'Clue_scroll_easy.png', 'LMS': False},
{'Get 5 new uniques from easy clues': 'Clue_scroll_easy.png', 'LMS': False},
{'Get 5 new uniques from medium clues': 'Clue_scroll_medium.png', 'LMS': False},
{'Get 5 new uniques from medium clues': 'Clue_scroll_medium.png', 'LMS': False},
{'Get 5 new uniques from medium clues': 'Clue_scroll_medium.png', 'LMS': False},
{'Get 5 new uniques from medium clues': 'Clue_scroll_medium.png', 'LMS': False},
{'Get 5 new uniques from hard clues': 'Clue_scroll_hard.png', 'LMS': False},
{'Get 5 new uniques from hard clues': 'Clue_scroll_hard.png', 'LMS': False},
{'Get 5 new uniques from hard clues': 'Clue_scroll_hard.png', 'LMS': False},
{'Get 5 new uniques from hard clues': 'Clue_scroll_hard.png', 'LMS': False},
{'Get a Fighter hat': 'Fighter_hat.png', 'LMS': False},
{'Get a Healer hat': 'Healer_hat.png', 'LMS': False},
{'Get a Runner hat': 'Runner_hat.png', 'LMS': False},
{'Get a Ranger hat': 'Ranger_hat.png', 'LMS': False},
{'Get a Fighter torso': 'Fighter_torso.png', 'LMS': False},
{'Get a Granite helm': 'Granite_helm.png', 'LMS': False},
{'Get 1 new halo': 'Saradomin_halo.png', 'LMS': False},
{'Get the Decorative ranged set': 'Decorative_armour_ranged_top.png', 'LMS': False},
{'Get the Decorative magic set': 'Decorative_armour_magic_top.png', 'LMS': False},
{'Get 1 new unique from Gnome Restaurant': 'Gnome_scarf.png', 'LMS': False},
{'Get 1 new unique from Gnome Restaurant': 'Gnome_scarf.png', 'LMS': False},
{'Upgrade the MTA wand once': 'Teacher_wand.png', 'LMS': False},
{'Upgrade the MTA wand once': 'Teacher_wand.png', 'LMS': False},
{'Upgrade the MTA wand once': 'Teacher_wand.png', 'LMS': False},
{'Get an Infinity hat': 'Infinity_hat.png', 'LMS': False},
{"Get a Mage's book": 'Mages_book.png', 'LMS': False},
{'Get a Void melee helm': 'Void_melee_helm.png', 'LMS': False},
{'Get a Void magic helm': 'Void_mage_helm.png', 'LMS': False},
{'Get a Void ranger helm': 'Void_ranger_helm.png', 'LMS': False},
{'Get a Void Knight top': 'Void_knight_top.png', 'LMS': False},
{'Get a Void Knight robe': 'Void_knight_robe.png', 'LMS': False},
{'Get 1 piece of Rogue equipment': 'Rogue_top.png', 'LMS': False},
{'Get 1 piece of Rogue equipment': 'Rogue_top.png', 'LMS': False},
{'Get 1 piece of Rogue equipment': 'Rogue_top.png', 'LMS': False},
{"Get 1 unique from Shades of Mort'ton": 'Fine_cloth.png', 'LMS': False},
{"Get 1 unique from Shades of Mort'ton": 'Fine_cloth.png', 'LMS': False},
{"Get 1 unique from Shades of Mort'ton": 'Fine_cloth.png', 'LMS': False},
{'Get 1 piece of Lumberjack equipment': 'Lumberjack_top.png', 'LMS': False},
{'Get 1 piece of Lumberjack equipment': 'Lumberjack_top.png', 'LMS': False},
{'Get 1 piece of Lumberjack equipment': 'Lumberjack_top.png', 'LMS': False},
{"Get 1 piece of Farmer's equipment": 'Farmers_jacket.png', 'LMS': False},
{"Get 1 piece of Farmer's equipment": 'Farmers_jacket.png', 'LMS': False},
{"Get 1 piece of Farmer's equipment": 'Farmers_jacket.png', 'LMS': False},
{'Get the Seed box': 'Seed_box.png', 'LMS': False},
{'Get 1 Naval set': '130px-Green_naval_shirt_detail.png', 'LMS': False},
{'Get 1 Naval set': '130px-Green_naval_shirt_detail.png', 'LMS': False},
{'Get the Cutthroat flag': 'Cutthroat_flag.png', 'LMS': False},
{'Get the Guilded smile flag': 'Guilded_smile_flag.png', 'LMS': False},
{'Get the Pearl fly fishing rod': 'Pearl_fly_fishing_rod.png', 'LMS': False},
{'Get the Pearl barbarian rod': '150px-Pearl_barbarian_rod_detail.png', 'LMS': False},
{'Get 1 unique Champion scroll': 'Goblin_champion_scroll.png', 'LMS': False},
{'Get 1 unique Champion scroll': 'Goblin_champion_scroll.png', 'LMS': False},
{'Get 1 unique Elder chaos robe piece': 'Elder_chaos_top.png', 'LMS': False},
{'Get 1 unique Elder chaos robe piece': 'Elder_chaos_top.png', 'LMS': False},
{'Get the Ogre forester headpiece': 'Chompy_bird_hat_ogre_forester_detail.png', 'LMS': False},
{'Get a Gold satchel': 'Gold_satchel.png', 'LMS': False},
{'Get a Plain satchel': 'Plain_satchel.png', 'LMS': False},
{'Get a Dragon defender': 'Dragon_defender.png', 'LMS': False},
{'Get 2 unique notes from Fossil Island': 'Scribbled_note.png', 'LMS': False},
{'Get 2 unique notes from Fossil Island': 'Scribbled_note.png', 'LMS': False},
{'Get 2 unique notes from Fossil Island': 'Scribbled_note.png', 'LMS': False},
{'Get the Coal bag': 'Coal_bag.png', 'LMS': False},
{'Get the Gem bag': '150px-Gem_bag_detail.png', 'LMS': False},
{'Get 2 unique Ancient pages': 'Ancient_page.png', 'LMS': False},
{'Get 2 unique Ancient pages': 'Ancient_page.png', 'LMS': False},
{'Get 2 unique Ancient pages': 'Ancient_page.png', 'LMS': False},
{'Get 2 unique Ancient pages': 'Ancient_page.png', 'LMS': False},
{'Get 2 unique Ancient pages': 'Ancient_page.png', 'LMS': False},
{'Get 2 unique Ancient pages': 'Ancient_page.png', 'LMS': False},
{'Get 1 piece of Graceful equipment': 'Graceful_top.png', 'LMS': False},
{'Get 1 piece of Graceful equipment': 'Graceful_top.png', 'LMS': False},
{'Get 1 piece of Graceful equipment': 'Graceful_top.png', 'LMS': False},
{'Get tier 5 Shayzien armour': 'Shayzien_platebody_5.png', 'LMS': False},
{'Get a Basilisk head': '150px-Basilisk_head_detail.png', 'LMS': False},
{'Get 1 unique from Gargoyles': 'Granite_maul.png', 'LMS': False},
{'Get 1 unique from Gargoyles': 'Granite_maul.png', 'LMS': False},
{'Get 1 unique from Kurasks': 'Leaf-bladed_battleaxe.png', 'LMS': False},
{'Get 1 unique from Kurasks': 'Leaf-bladed_battleaxe.png', 'LMS': False},
{'Get a Granite longsword': 'Granite_longsword.png', 'LMS': False},
{'Get Granite legs': '150px-Granite_legs_detail.png', 'LMS': False},
{'Get the next tier of metal boots': 'Bronze_boots.png', 'LMS': False},
{'Get the next tier of metal boots': 'Bronze_boots.png', 'LMS': False},
{'Get a Mystic robe bottom (dark)': 'Mystic_robe_bottom_dark.png', 'LMS': False},
{'Get 1 unique Tzhaar drop': 'Obsidian_cape.png', 'LMS': False},
{'Get 1 unique Tzhaar drop': 'Obsidian_cape.png', 'LMS': False},
{'Get 1 unique Tzhaar drop': 'Obsidian_cape.png', 'LMS': False},
{'Get 1 unique Tzhaar drop': 'Obsidian_cape.png', 'LMS': False},
{'Get a Big shark': 'Big_shark.png', 'LMS': False},
{'Get a Curved bone': 'Curved_bone.png', 'LMS': False},
{'Get a Shaman mask': 'Shaman_mask.png', 'LMS': False},
{'Get Superior mining gloves': 'Superior_mining_gloves.png', 'LMS': False},
{'Get a Bracelet of ethereum or Rev cave teleport': '140px-Bracelet_of_ethereum_uncharged_detail.png', 'LMS': False},
{'Get a Bracelet of ethereum or Rev cave teleport': '140px-Bracelet_of_ethereum_uncharged_detail.png', 'LMS': False},
{'Complete the Ardougne Medium Diary': 'Achievement_Diaries_icon.png', 'LMS': False},
{'Complete the Desert Medium Diary': 'Achievement_Diaries_icon.png', 'LMS': False},
{'Complete the Falador Medium Diary': 'Achievement_Diaries_icon.png', 'LMS': False},
{'Complete the Fremennik Medium Diary': 'Achievement_Diaries_icon.png', 'LMS': False},
{'Complete the Kandarin Medium Diary': 'Achievement_Diaries_icon.png', 'LMS': False},
{'Complete the Karamja Medium Diary': 'Achievement_Diaries_icon.png', 'LMS': False},
{'Complete the Kourend&Kebos Medium Diary': 'Achievement_Diaries_icon.png', 'LMS': False},
{'Complete the Lumbridge&Draynor Medium Diary': 'Achievement_Diaries_icon.png', 'LMS': False},
{'Complete the Morytania Medium Diary': 'Achievement_Diaries_icon.png', 'LMS': False},
{'Complete the Varrock Medium Diary': 'Achievement_Diaries_icon.png', 'LMS': False},
{'Complete the Western Provinces Medium Diary': 'Achievement_Diaries_icon.png', 'LMS': False},
{'Complete the Wilderness Medium Diary': 'Achievement_Diaries_icon.png', 'LMS': False},
{'Get a Mask of Ranul': 'Mask_of_ranul.png', 'LMS': False},
{'Get a Giant egg sac(full)': '150px-Giant_egg_sacfull_detail.png', 'LMS': False},
{'Get a Herb sack': 'Herb_sack.png', 'LMS': False},
{'Get a Plank sack': '800px-Plank_sack_detail.png', 'LMS': False},
{'Get 1 piece of Carpenter equipment': '1280px-Carpenters_shirt_detail.png', 'LMS': False},
{'Get 1 piece of Carpenter equipment': '1280px-Carpenters_shirt_detail.png', 'LMS': False},
{'Get an Ectoplasmator': '130px-Ectoplasmator_detail.png', 'LMS': False},
{'Get a Penance skirt': 'Penance_skirt.png', 'LMS': False},
{'Get a Ward upgrade kit': '150px-Ward_upgrade_kit_detail.png', 'LMS': True},
{'Get a Granite clamp': '150px-Granite_clamp_detail.png', 'LMS': True},
{'Get a Volcanic whip mix': 'Volcanic_whip_mix.png', 'LMS': True},
{'Get a Frozen whip mix': '120px-Frozen_whip_mix_detail.png', 'LMS': True},
{'Get a Steam staff upgrade kit': '150px-Steam_staff_upgrade_kit_detail.png', 'LMS': True},
{'Get a Lava staff upgrade kit': '150px-Lava_staff_upgrade_kit_detail.png', 'LMS': True},
{'Get a Dragon pickaxe upgrade kit': '150px-Dragon_pickaxe_upgrade_kit_detail.png', 'LMS': True},
{'Get an Ornate maul handle': '120px-Ornate_maul_handle_detail.png', 'LMS': True},
{'Get a Celestial ring': '170px-Celestial_ring_uncharged_detail.png', 'LMS': False},
{'Get a Star fragment': '140px-Star_fragment_detail.png', 'LMS': False},
{'Get 1 unique from Tempoross': '160px-Tome_of_water_empty_detail.png', 'LMS': False},
{'Get 1 unique from Tempoross': '160px-Tome_of_water_empty_detail.png', 'LMS': False},
{'Get 1 unique from Tempoross': '160px-Tome_of_water_empty_detail.png', 'LMS': False},
{'Get the Merfolk trident': '150px-Merfolk_trident_detail.png', 'LMS': False},
{'Get 1 unique from Tempoross': '160px-Tome_of_water_empty_detail.png', 'LMS': False},
{'Get 1 unique from Tempoross': '160px-Tome_of_water_empty_detail.png', 'LMS': False},
{'Get 1 unique from Guardians of the Rift': 'Hat_of_the_eye_detail.png', 'LMS': False},
{'Get 1 unique from Guardians of the Rift': 'Hat_of_the_eye_detail.png', 'LMS': False},
{'Get 1 unique from Guardians of the Rift': 'Hat_of_the_eye_detail.png', 'LMS': False},
{'Get 1 unique from Guardians of the Rift': 'Hat_of_the_eye_detail.png', 'LMS': False},
{"Get 1 unique from Giants' Foundry": "Smiths_tunic_detail.png", 'LMS': False},
{"Get 1 unique from Giants' Foundry": "Smiths_tunic_detail.png", 'LMS': False},
{"Get 1 unique from Giants' Foundry": "Smiths_tunic_detail.png", 'LMS': False},
{"Get 1 unique from Giants' Foundry": "Smiths_tunic_detail.png", 'LMS': False},
{"Get 1 unique from Forestry" : "forestry_kit.png", 'LMS' : False},
{"Get 1 unique from Forestry" : "forestry_kit.png", 'LMS' : False},
{"Get 1 unique from Forestry" : "forestry_kit.png", 'LMS' : False},
{"Get 1 unique from Forestry" : "forestry_kit.png", 'LMS' : False},
{"Get a Scurrius' spine" : "Scurrius'_spine.png", 'LMS' : False},
{'Get a Broken zombie axe' : 'Broken_zombie_axe.png', 'LMS' : False},
{'Get 1 unique from Moons of Peril' : 'dual_macuahuitl.png', 'LMS' : False},
{'Get 1 unique from Moons of Peril' : 'dual_macuahuitl.png', 'LMS' : False},
{'Get 1 unique from Moons of Peril' : 'dual_macuahuitl.png', 'LMS' : False},
{'Get 1 unique from Moons of Peril' : 'dual_macuahuitl.png', 'LMS' : False},
{"Get 1 unique from the Hunter Guild" : "guild_hunter_top.png", 'LMS' : False}
]

hard = [
{'Get 1 unique from Barrows': 'Guthans_helm.png', 'LMS': False},
{'Get 1 unique from Barrows': 'Guthans_helm.png', 'LMS': False},
{'Get 1 unique from Barrows': 'Guthans_helm.png', 'LMS': False},
{'Get 1 unique from Barrows': 'Guthans_helm.png', 'LMS': False},
{'Get 1 unique from Barrows': 'Guthans_helm.png', 'LMS': False},
{'Get 1 unique from Barrows': 'Guthans_helm.png', 'LMS': False},
{'Get 1 unique from Barrows': 'Guthans_helm.png', 'LMS': False},
{'Get 1 unique from Barrows': 'Guthans_helm.png', 'LMS': False},
{'Get 1 unique from Barrows': 'Guthans_helm.png', 'LMS': False},
{'Get 1 unique from Barrows': 'Guthans_helm.png', 'LMS': False},
{'Get 1 unique from Barrows': 'Guthans_helm.png', 'LMS': False},
{'Get 1 unique from Barrows': 'Guthans_helm.png', 'LMS': False},
{'Get 1 unique from Barrows': 'Guthans_helm.png', 'LMS': False},
{'Get 1 unique from Barrows': 'Guthans_helm.png', 'LMS': False},
{'Get 1 unique from Barrows': 'Guthans_helm.png', 'LMS': False},
{'Get a unique from Unsired': 'Unsired.png', 'LMS': False},
{'Get a unique from Unsired': 'Unsired.png', 'LMS': False},
{'Get a unique from Unsired': 'Unsired.png', 'LMS': False},
{'Get an Abyssal whip': 'Abyssal_whip.png', 'LMS': False},
{'Get 1 unique item from Mount Karuulm': '130px-Dragon_knife_detail.png', 'LMS': False},
{'Get 1 unique item from Mount Karuulm': '130px-Dragon_knife_detail.png', 'LMS': False},
{'Get 1 unique item from Mount Karuulm': '130px-Dragon_knife_detail.png', 'LMS': False},
{'Get 1 unique item from Mount Karuulm': '130px-Dragon_knife_detail.png', 'LMS': False},
{'Get 1 unique item from Mount Karuulm': '130px-Dragon_knife_detail.png', 'LMS': False},
{'Get 1 unique from the Wildy bosses' : 'Skull_of_vetion_detail.png', 'LMS': False},
{'Get 1 unique from the Wildy bosses' : 'Skull_of_vetion_detail.png', 'LMS': False},
{'Get 1 unique from the Wildy bosses' : 'Skull_of_vetion_detail.png', 'LMS': False},
{'Get 1 unique from Cerberus': 'Eternal_crystal.png', 'LMS': False},
{'Get 1 unique from Cerberus': 'Eternal_crystal.png', 'LMS': False},
{'Get 1 unique from Cerberus': 'Eternal_crystal.png', 'LMS': False},
{'Get a unique shard 1': 'Odium_shard_1.png', 'LMS': False},
{'Get a unique shard 1': 'Odium_shard_1.png', 'LMS': False},
{'Get a new Boss pet': 'Olmlet.png', 'LMS': False},
{'Get 1 unique drop from Zamorak GWD': 'Staff_of_the_dead.png', 'LMS': False},
{'Get 1 unique drop from Zamorak GWD': 'Staff_of_the_dead.png', 'LMS': False},
{'Get 1 unique drop from Dagannoth Kings': 'Dragon_axe.png', 'LMS': False},
{'Get 1 unique drop from Dagannoth Kings': 'Dragon_axe.png', 'LMS': False},
{'Get 1 unique drop from Dagannoth Kings': 'Dragon_axe.png', 'LMS': False},
{'Get 1 unique drop from Dagannoth Kings': 'Dragon_axe.png', 'LMS': False},
{'Get 1 unique drop from Dagannoth Kings': 'Dragon_axe.png', 'LMS': False},
{'Get 1 unique drop from Dagannoth Kings': 'Dragon_axe.png', 'LMS': False},
{'Get 1 unique drop from Dagannoth Kings': 'Dragon_axe.png', 'LMS': False},
{'Get 1 unique drop from Grotesque Guardians': 'Black_tourmaline_core.png', 'LMS': False},
{'Get 1 unique drop from Grotesque Guardians': 'Black_tourmaline_core.png', 'LMS': False},
{'Get 1 unique drop from Grotesque Guardians': 'Black_tourmaline_core.png', 'LMS': False},
{'Get 1 unique from the Kalphite Queen': 'Kq_head.png', 'LMS': False},
{'Get 1 unique from the Kalphite Queen': 'Kq_head.png', 'LMS': False},
{'Get Kbd heads': 'Kbd_heads.png', 'LMS': False},
{'Get 1 unique drop from Kraken': 'Trident_of_the_seas.png', 'LMS': False},
{'Get 1 unique drop from Kraken': 'Trident_of_the_seas.png', 'LMS': False},
{'Get an Uncharged Trident': 'Trident_of_the_seas.png', 'LMS': False},
{'Get a unique shard 3': 'Odium_shard_3.png', 'LMS': False},
{'Get a unique shard 3': 'Odium_shard_3.png', 'LMS': False},
{"Get Vorkath's head": 'Vorkaths_head.png', 'LMS': False},
{'Get 1 unique from Zulrah': 'Tanzanite_fang.png', 'LMS': False},
{'Get 1 unique from Zulrah': 'Tanzanite_fang.png', 'LMS': False},
{'Get 1 unique from Zulrah': 'Tanzanite_fang.png', 'LMS': False},
{'Get 1 unique from Zulrah': 'Tanzanite_fang.png', 'LMS': False},
{'Get 3 new uniques from beginner clues': 'Clue_scroll_beginner.png', 'LMS': False},
{'Get 5 new uniques from easy clues': 'Clue_scroll_easy.png', 'LMS': False},
{'Get 5 new uniques from easy clues': 'Clue_scroll_easy.png', 'LMS': False},
{'Get 5 new uniques from easy clues': 'Clue_scroll_easy.png', 'LMS': False},
{'Get 5 new uniques from easy clues': 'Clue_scroll_easy.png', 'LMS': False},
{'Get 5 new uniques from easy clues': 'Clue_scroll_easy.png', 'LMS': False},
{'Get 5 new uniques from medium clues': 'Clue_scroll_medium.png', 'LMS': False},
{'Get 5 new uniques from medium clues': 'Clue_scroll_medium.png', 'LMS': False},
{'Get 5 new uniques from medium clues': 'Clue_scroll_medium.png', 'LMS': False},
{'Get 5 new uniques from medium clues': 'Clue_scroll_medium.png', 'LMS': False},
{'Get 5 new uniques from medium clues': 'Clue_scroll_medium.png', 'LMS': False},
{'Get 5 new uniques from hard clues': 'Clue_scroll_hard.png', 'LMS': False},
{'Get 5 new uniques from hard clues': 'Clue_scroll_hard.png', 'LMS': False},
{'Get 5 new uniques from hard clues': 'Clue_scroll_hard.png', 'LMS': False},
{'Get 5 new uniques from hard clues': 'Clue_scroll_hard.png', 'LMS': False},
{'Get 5 new uniques from hard clues': 'Clue_scroll_hard.png', 'LMS': False},
{'Get 5 new uniques from hard clues': 'Clue_scroll_hard.png', 'LMS': False},
{'Get 5 new uniques from hard clues': 'Clue_scroll_hard.png', 'LMS': False},
{'Get 2 new uniques from elite clues': 'Clue_scroll_elite.png', 'LMS': False},
{'Get 2 new uniques from elite clues': 'Clue_scroll_elite.png', 'LMS': False},
{'Get 2 new uniques from elite clues': 'Clue_scroll_elite.png', 'LMS': False},
{'Get 2 new uniques from elite clues': 'Clue_scroll_elite.png', 'LMS': False},
{'Get 2 new uniques from elite clues': 'Clue_scroll_elite.png', 'LMS': False},
{'Get 1 new halo': 'Saradomin_halo.png', 'LMS': False},
{'Get 1 new unique from Gnome Restaurant': 'Gnome_scarf.png', 'LMS': False},
{'Get an Infinity top': 'Infinity_top.png', 'LMS': False},
{'Get Infinity bottoms': 'Infinity_bottoms.png', 'LMS': False},
{'Get 2 White decorative pieces': 'Decorative_armour_white_platebody_detail.png', 'LMS': False},
{'Get 2 White decorative pieces': 'Decorative_armour_white_platebody_detail.png', 'LMS': False},
{'Get 2 White decorative pieces': 'Decorative_armour_white_platebody_detail.png', 'LMS': False},
{'Get 2 White decorative pieces': 'Decorative_armour_white_platebody_detail.png', 'LMS': False},
{'Get an Elite void top': 'Elite_void_top.png', 'LMS': False},
{'Get an Elite void robe': 'Elite_void_robe.png', 'LMS': False},
{'Get 1 Naval set': 'Green_naval_shirt.png', 'LMS': False},
{'Get 1 Naval set': 'Green_naval_shirt.png', 'LMS': False},
{'Get 1 Naval set': 'Green_naval_shirt.png', 'LMS': False},
{'Get the Bronze fist flag': 'Bronze_fist_flag.png', 'LMS': False},
{'Get the Lucky shot flag': 'Lucky_shot_flag.png', 'LMS': False},
{'Get 1 unique Champion scroll': 'Goblin_champion_scroll.png', 'LMS': False},
{'Get 1 unique Champion scroll': 'Goblin_champion_scroll.png', 'LMS': False},
{'Get 1 unique Champion scroll': 'Goblin_champion_scroll.png', 'LMS': False},
{'Get 1 unique Elder chaos robe piece': 'Elder_chaos_top.png', 'LMS': False},
{'Get the Ogre expert headpiece': 'Chompy_bird_hat_ogre_expert_detail.png', 'LMS': False},
{'Get a unique from Demonic gorillas': 'Zenyte_shard.png', 'LMS': False},
{'Get a unique from Demonic gorillas': 'Zenyte_shard.png', 'LMS': False},
{'Get a unique from Demonic gorillas': 'Zenyte_shard.png', 'LMS': False},
{'Get a unique from Demonic gorillas': 'Zenyte_shard.png', 'LMS': False},
{'Get 2 unique Ancient pages': 'Ancient_page.png', 'LMS': False},
{'Get 2 unique Ancient pages': 'Ancient_page.png', 'LMS': False},
{'Get 2 unique Ancient pages': 'Ancient_page.png', 'LMS': False},
{'Get a Kurask head': 'Kurask_head.png', 'LMS': False},
{'Get Dragon boots': 'Dragon_boots.png', 'LMS': False},
{'Get a Dark bow': 'Dark_bow.png', 'LMS': False},
{'Get 1 unique from Thermonuclear smoke devil': 'Occult_necklace.png', 'LMS': False},
{'Get 1 unique Obsidian armour drop': 'Obsidian_platebody.png', 'LMS': False},
{'Get 1 unique Obsidian armour drop': 'Obsidian_platebody.png', 'LMS': False},
{'Get a Dragon warhammer': 'Dragon_warhammer.png', 'LMS': False},
{"Get a Pharaoh's sceptre": 'Pharaohs_sceptre_3.png', 'LMS': False},
{'Get Chewed bones': 'Chewed_bones.png', 'LMS': False},
{'Get a Dragon spear': 'Dragon_spear.png', 'LMS': False},
{'Get Expert mining gloves': 'Expert_mining_gloves.png', 'LMS': False},
{'Complete the Ardougne Hard Diary': 'Achievement_Diaries_icon.png', 'LMS': False},
{'Complete the Desert Hard Diary': 'Achievement_Diaries_icon.png', 'LMS': False},
{'Complete the Falador Hard Diary': 'Achievement_Diaries_icon.png', 'LMS': False},
{'Complete the Fremennik Hard Diary': 'Achievement_Diaries_icon.png', 'LMS': False},
{'Complete the Kandarin Hard Diary': 'Achievement_Diaries_icon.png', 'LMS': False},
{'Complete the Karamja Hard Diary': 'Achievement_Diaries_icon.png', 'LMS': False},
{'Complete the Kourend&Kebos Hard Diary': 'Achievement_Diaries_icon.png', 'LMS': False},
{'Complete the Lumbridge&Draynor Hard Diary': 'Achievement_Diaries_icon.png', 'LMS': False},
{'Complete the Morytania Hard Diary': 'Achievement_Diaries_icon.png', 'LMS': False},
{'Complete the Varrock Hard Diary': 'Achievement_Diaries_icon.png', 'LMS': False},
{'Complete the Western Provinces Hard Diary': 'Achievement_Diaries_icon.png', 'LMS': False},
{'Complete the Wilderness Hard Diary': 'Achievement_Diaries_icon.png', 'LMS': False},
{"Get Bryophyta's essence": 'Bryophytas_essence.png', 'LMS': False},
{'Get a Sarachnis Cudgel': 'Sarachnis_cudgel.png', 'LMS': False},
{'Get 1 unique from the Gauntlet': 'Blade_of_saeldor_inactive.png', 'LMS': False},
{'Get 1 unique from the Gauntlet': 'Blade_of_saeldor_inactive.png', 'LMS': False},
{'Get the Elven signet': '100px-Elven_signet_detail.png', 'LMS': False},
{'Get an Enhanced crystal teleport seed': '80px-Enhanced_crystal_teleport_seed_detail.png', 'LMS': False},
{'Get the Basilisk jaw': '130px-Basilisk_jaw_detail.png', 'LMS': False},
{'Get a shield left half': '120px-Shield_left_half_detail.png', 'LMS': False},
{"Get a Pirate's hook": 'Pirates_hook.png', 'LMS': False},
{'Get 2 uniques from the Hallowed Sepulchre': '120px-Hallowed_mark_detail.png', 'LMS': False},
{'Get 2 uniques from the Hallowed Sepulchre': '120px-Hallowed_mark_detail.png', 'LMS': False},
{'Get 2 uniques from the Hallowed Sepulchre': '120px-Hallowed_mark_detail.png', 'LMS': False},
{'Get 2 uniques from the Hallowed Sepulchre': '120px-Hallowed_mark_detail.png', 'LMS': False},
{'Get 2 uniques from the Hallowed Sepulchre': '120px-Hallowed_mark_detail.png', 'LMS': False},
{'Get 2 uniques from the Hallowed Sepulchre': '120px-Hallowed_mark_detail.png', 'LMS': False},
{'Unlock 2 monkey backpack transformations': '1280px-Monkey_Monkey_Madness_II_detail.png', 'LMS': False},
{'Unlock 2 monkey backpack transformations': '1280px-Monkey_Monkey_Madness_II_detail.png', 'LMS': False},
{'Unlock 2 monkey backpack transformations': '1280px-Monkey_Monkey_Madness_II_detail.png', 'LMS': False},
{"Get Amy's saw": '1024px-Amys_saw_detail.png', 'LMS': False},
{'Get 1 piece of Carpenter equipment': '1280px-Carpenters_shirt_detail.png', 'LMS': False},
{'Get 1 piece of Carpenter equipment': '1280px-Carpenters_shirt_detail.png', 'LMS': False},
{'Get a Blood shard': '100px-Blood_shard_detail.png', 'LMS': False},
{'Get a Soul cape': '100px-Soul_cape_red_detail.png', 'LMS': False},
{"Get 1 unique from Shades of Mort'ton": 'Fine_cloth.png', 'LMS': False},
{"Get 1 unique from Shades of Mort'ton": 'Fine_cloth.png', 'LMS': False},
{'Get a new dark bow paint from LMS': '120px-Yellow_dark_bow_paint_detail.png', 'LMS': True},
{'Get a new dark bow paint from LMS': '120px-Yellow_dark_bow_paint_detail.png', 'LMS': True},
{'Get a new dark bow paint from LMS': '120px-Yellow_dark_bow_paint_detail.png', 'LMS': True},
{'Get a new dark bow paint from LMS': '120px-Yellow_dark_bow_paint_detail.png', 'LMS': True},
{'Get the Brimhaven graceful set recolour': '140px-Graceful_top_Agility_Arena_detail.png', 'LMS': False},
{'Get a Volcanic mine teleport': '150px-Volcanic_mine_teleport_detail.png', 'LMS': False},
{'Get a Heat-proof vessel': '140px-Heat-proof_vessel_detail.png', 'LMS': False},
{'Get the Ash covered tome': '130px-Ash_covered_tome_detail.png', 'LMS': False},
{'Get 1 unique from Tempoross': '160px-Tome_of_water_empty_detail.png', 'LMS': False},
{'Get a Vial of blood (from Story mode ToB)': 'Vial_of_blood.png', 'LMS': False},
{'Get a unique Egg Sac from the Grubby Chest': '130px-Grubby_key_detail.png', 'LMS': False},
{'Get a unique Egg Sac from the Grubby Chest': '130px-Grubby_key_detail.png', 'LMS': False},
{'Get 1 unique Nihil shard / Ceremonial robe piece': 'Ancient_ceremonial_top.png', 'LMS': False},
{'Get 1 unique Nihil shard / Ceremonial robe piece': 'Ancient_ceremonial_top.png', 'LMS': False},
{'Get 1 unique Nihil shard / Ceremonial robe piece': 'Ancient_ceremonial_top.png', 'LMS': False},
{'Get 1 unique Nihil shard / Ceremonial robe piece': 'Ancient_ceremonial_top.png', 'LMS': False},
{'Get 1 unique Nihil shard / Ceremonial robe piece': 'Ancient_ceremonial_top.png', 'LMS': False},
{'Get 1 unique Nihil shard / Ceremonial robe piece': 'Ancient_ceremonial_top.png', 'LMS': False},
{'Get 1 unique from Guardians of the Rift': 'Hat_of_the_eye_detail.png', 'LMS': False},
{'Get 1 unique from Guardians of the Rift': 'Hat_of_the_eye_detail.png', 'LMS': False},
{'Get 1 unique from Guardians of the Rift': 'Hat_of_the_eye_detail.png', 'LMS': False},
{'Get 1 unique from Guardians of the Rift': 'Hat_of_the_eye_detail.png', 'LMS': False},
{'Get a Colossal blade': "Colossal_blade_detail.png", 'LMS': False},
{"Get 1 unique from Tombs of Amascut": "Thread_of_elidinis.png", 'LMS': False},
{"Get 1 unique from Tombs of Amascut": "Thread_of_elidinis.png", 'LMS': False},
{"Get 1 unique from the Phantom Muspah" : "Ancient_essence_detail.png", 'LMS': False},
{"Get 1 unique from the Phantom Muspah" : "Ancient_essence_detail.png", 'LMS': False},
{"Get 1 unique from Forestry" : "forestry_kit.png", 'LMS' : False},
{"Get 1 unique from Forestry" : "forestry_kit.png", 'LMS' : False},
{"Get 1 unique from Forestry" : "forestry_kit.png", 'LMS' : False},
{'Get 1 unique from Moons of Peril' : 'dual_macuahuitl.png', 'LMS' : False},
{'Get 1 unique from Moons of Peril' : 'dual_macuahuitl.png', 'LMS' : False},
{'Get 1 unique from Moons of Peril' : 'dual_macuahuitl.png', 'LMS' : False},
{'Get 1 unique from Moons of Peril' : 'dual_macuahuitl.png', 'LMS' : False},
{'Get 1 unique from Moons of Peril' : 'dual_macuahuitl.png', 'LMS' : False},
{'Get 1 unique from Moons of Peril' : 'dual_macuahuitl.png', 'LMS' : False},
{"Get 1 unique from the Hunter Guild" : "guild_hunter_top.png", 'LMS' : False},
{"Get 1 unique from the Hunter Guild" : "guild_hunter_top.png", 'LMS' : False},
{"Get 1 unique from the Hunter Guild" : "guild_hunter_top.png", 'LMS' : False},
{"Obtain Sunfire splinters" : 'sunfire_splinters.png', 'LMS' : False}
]



elite = [
{'Get 1 unique from Barrows': 'Guthans_helm.png', 'LMS': False},
{'Get 1 unique from Barrows': 'Guthans_helm.png', 'LMS': False},
{'Get 1 unique from Barrows': 'Guthans_helm.png', 'LMS': False},
{'Get 1 unique from Barrows': 'Guthans_helm.png', 'LMS': False},
{'Get a unique from Unsired': 'Unsired.png', 'LMS': False},
{'Get a unique from Unsired': 'Unsired.png', 'LMS': False},
{'Get 1 unique item from Mount Karuulm': '130px-Dragon_knife_detail.png', 'LMS': False},
{'Get 1 unique item from Mount Karuulm': '130px-Dragon_knife_detail.png', 'LMS': False},
{'Get 1 unique item from Mount Karuulm': '130px-Dragon_knife_detail.png', 'LMS': False},
{'Get 1 unique item from Mount Karuulm': '130px-Dragon_knife_detail.png', 'LMS': False},
{'Get 1 unique item from Mount Karuulm': '130px-Dragon_knife_detail.png', 'LMS': False},
{'Get 1 unique item from Mount Karuulm': '130px-Dragon_knife_detail.png', 'LMS': False},
{'Get 1 unique item from Mount Karuulm': '130px-Dragon_knife_detail.png', 'LMS': False},
{'Get 1 unique item from Mount Karuulm': '130px-Dragon_knife_detail.png', 'LMS': False},
{'Get 1 unique crystal/stone from Cerberus': 'Eternal_crystal.png', 'LMS': False},
{'Get 1 unique crystal/stone from Cerberus': 'Eternal_crystal.png', 'LMS': False},
{'Get 1 unique drop from God Wars Dungeon': 'Armadyl_helmet.png', 'LMS': False},
{'Get 1 unique drop from God Wars Dungeon': 'Armadyl_helmet.png', 'LMS': False},
{'Get 1 unique drop from God Wars Dungeon': 'Armadyl_helmet.png', 'LMS': False},
{'Get 1 unique drop from God Wars Dungeon': 'Armadyl_helmet.png', 'LMS': False},
{'Get 1 unique drop from God Wars Dungeon': 'Armadyl_helmet.png', 'LMS': False},
{'Get 1 unique drop from God Wars Dungeon': 'Armadyl_helmet.png', 'LMS': False},
{'Get 1 unique drop from God Wars Dungeon': 'Armadyl_helmet.png', 'LMS': False},
{'Get 1 unique drop from God Wars Dungeon': 'Armadyl_helmet.png', 'LMS': False},
{'Get 1 unique drop from God Wars Dungeon': 'Armadyl_helmet.png', 'LMS': False},
{'Get 1 unique drop from God Wars Dungeon': 'Armadyl_helmet.png', 'LMS': False},
{'Get 1 unique drop from God Wars Dungeon': 'Armadyl_helmet.png', 'LMS': False},
{'Get 1 unique drop from God Wars Dungeon': 'Armadyl_helmet.png', 'LMS': False},
{'Get 1 unique drop from God Wars Dungeon': 'Armadyl_helmet.png', 'LMS': False},
{'Get 1 unique drop from God Wars Dungeon': 'Armadyl_helmet.png', 'LMS': False},
{'Get 1 unique drop from God Wars Dungeon': 'Armadyl_helmet.png', 'LMS': False},
{'Get 1 unique drop from God Wars Dungeon': 'Armadyl_helmet.png', 'LMS': False},
{'Get a Spirit shield or Holy elixir': '120px-Blessed_spirit_shield_detail.png', 'LMS': False},
{'Get a Spirit shield or Holy elixir': '120px-Blessed_spirit_shield_detail.png', 'LMS': False},
{'Get a new Boss pet': 'Olmlet.png', 'LMS': False},
{'Get a new Boss pet': 'Olmlet.png', 'LMS': False},
{'Get a new Boss pet': 'Olmlet.png', 'LMS': False},
{'Get 1 unique from Thermonuclear smoke devil': 'Occult_necklace.png', 'LMS': False},
{'Get 1 unique from the Wildy bosses' : 'Skull_of_vetion_detail.png', 'LMS': False},
{'Get 1 unique from the Wildy bosses' : 'Skull_of_vetion_detail.png', 'LMS': False},
{'Get 1 unique from the Wildy bosses' : 'Skull_of_vetion_detail.png', 'LMS': False},
{'Get 1 unique from the Wildy bosses' : 'Skull_of_vetion_detail.png', 'LMS': False},
{'Get 1 unique drop from Grotesque Guardians': 'Black_tourmaline_core.png', 'LMS': False},
{'Get 1 unique from Raids (CoX or ToB or ToA)': 'Twisted_bow.png', 'LMS': False},
{'Get 1 unique from Raids (CoX or ToB or ToA)': 'Twisted_bow.png', 'LMS': False},
{'Get 1 unique from Raids (CoX or ToB or ToA)': 'Twisted_bow.png', 'LMS': False},
{'Get 1 unique from Raids (CoX or ToB or ToA)': 'Twisted_bow.png', 'LMS': False},
{'Get 1 unique from Raids (CoX or ToB or ToA)': 'Twisted_bow.png', 'LMS': False},
{'Get 1 unique from Raids (CoX or ToB or ToA)': 'Twisted_bow.png', 'LMS': False},
{'Get 1 unique from Raids (CoX or ToB or ToA)': 'Twisted_bow.png', 'LMS': False},
{'Get 1 unique from Raids (CoX or ToB or ToA)': 'Twisted_bow.png', 'LMS': False},
{'Get 1 unique from Raids (CoX or ToB or ToA)': 'Twisted_bow.png', 'LMS': False},
{'Get 1 unique from Raids (CoX or ToB or ToA)': 'Twisted_bow.png', 'LMS': False},
{'Get 1 unique from Raids (CoX or ToB or ToA)': 'Twisted_bow.png', 'LMS': False},
{'Get 1 unique from Raids (CoX or ToB or ToA)': 'Twisted_bow.png', 'LMS': False},
{'Get 1 unique from Raids (CoX or ToB or ToA)': 'Twisted_bow.png', 'LMS': False},
{'Get 1 unique from Raids (CoX or ToB or ToA)': 'Twisted_bow.png', 'LMS': False},
{'Get 5 new uniques from easy clues': 'Clue_scroll_easy.png', 'LMS': False},
{'Get 5 new uniques from easy clues': 'Clue_scroll_easy.png', 'LMS': False},
{'Get 5 new uniques from easy clues': 'Clue_scroll_easy.png', 'LMS': False},
{'Get 5 new uniques from easy clues': 'Clue_scroll_easy.png', 'LMS': False},
{'Get 5 new uniques from easy clues': 'Clue_scroll_easy.png', 'LMS': False},
{'Get 5 new uniques from medium clues': 'Clue_scroll_medium.png', 'LMS': False},
{'Get 5 new uniques from medium clues': 'Clue_scroll_medium.png', 'LMS': False},
{'Get 5 new uniques from medium clues': 'Clue_scroll_medium.png', 'LMS': False},
{'Get 5 new uniques from medium clues': 'Clue_scroll_medium.png', 'LMS': False},
{'Get 5 new uniques from medium clues': 'Clue_scroll_medium.png', 'LMS': False},
{'Get 5 new uniques from hard clues': 'Clue_scroll_hard.png', 'LMS': False},
{'Get 5 new uniques from hard clues': 'Clue_scroll_hard.png', 'LMS': False},
{'Get 5 new uniques from hard clues': 'Clue_scroll_hard.png', 'LMS': False},
{'Get 5 new uniques from hard clues': 'Clue_scroll_hard.png', 'LMS': False},
{'Get 5 new uniques from hard clues': 'Clue_scroll_hard.png', 'LMS': False},
{'Get 5 new uniques from hard clues': 'Clue_scroll_hard.png', 'LMS': False},
{'Get 5 new uniques from hard clues': 'Clue_scroll_hard.png', 'LMS': False},
{'Get 5 new uniques from hard clues': 'Clue_scroll_hard.png', 'LMS': False},
{'Get 1 new unique from elite clues': 'Clue_scroll_elite.png', 'LMS': False},
{'Get 1 new unique from elite clues': 'Clue_scroll_elite.png', 'LMS': False},
{'Get 1 new unique from elite clues': 'Clue_scroll_elite.png', 'LMS': False},
{'Get 1 new unique from elite clues': 'Clue_scroll_elite.png', 'LMS': False},
{'Get 1 new unique from elite clues': 'Clue_scroll_elite.png', 'LMS': False},
{'Get 1 new unique from elite clues': 'Clue_scroll_elite.png', 'LMS': False},
{'Get 1 new unique from elite clues': 'Clue_scroll_elite.png', 'LMS': False},
{'Get 1 new unique from elite clues': 'Clue_scroll_elite.png', 'LMS': False},
{'Get 1 new unique from elite clues': 'Clue_scroll_elite.png', 'LMS': False},
{'Get 1 new unique from elite clues': 'Clue_scroll_elite.png', 'LMS': False},
{'Get 1 new unique from master clues': 'Clue_scroll_master.png', 'LMS': False},
{'Get 1 new unique from master clues': 'Clue_scroll_master.png', 'LMS': False},
{'Get 1 new unique from master clues': 'Clue_scroll_master.png', 'LMS': False},
{'Get 1 new unique from master clues': 'Clue_scroll_master.png', 'LMS': False},
{'Get 1 new unique from master clues': 'Clue_scroll_master.png', 'LMS': False},
{'Get 1 new unique from master clues': 'Clue_scroll_master.png', 'LMS': False},
{'Get 1 new unique from master clues': 'Clue_scroll_master.png', 'LMS': False},
{'Get 1 new unique from master clues': 'Clue_scroll_master.png', 'LMS': False},
{'Get 1 new unique from master clues': 'Clue_scroll_master.png', 'LMS': False},
{'Get 1 new unique from master clues': 'Clue_scroll_master.png', 'LMS': False},
{'Get 1 new unique from master clues': 'Clue_scroll_master.png', 'LMS': False},
{'Get 1 new unique from master clues': 'Clue_scroll_master.png', 'LMS': False},
{'Get a Saradomin banner': 'Saradomin_banner.png', 'LMS': False},
{'Get a Zamorak banner': 'Zamorak_banner.png', 'LMS': False},
{'Get a Gold decorative helm': 'Decorative_helm_gold.png', 'LMS': False},
{'Get a pair of Gold decorative boots': '100px-Decorative_boots_gold_detail.png', 'LMS': False},
{'Get 1 Naval set': 'Green_naval_shirt.png', 'LMS': False},
{'Get 1 Naval set': 'Green_naval_shirt.png', 'LMS': False},
{'Get the Treasure flag': 'Treasure_flag.png', 'LMS': False},
{'Get the Phasmatys flag': '130px-Phasmatys_flag_detail.png', 'LMS': False},
{'Get the Chompy chick': 'Chompy_chick.png', 'LMS': False},
{'Get 1 unique Champion scroll': 'Goblin_champion_scroll.png', 'LMS': False},
{'Get 1 unique Champion scroll': 'Goblin_champion_scroll.png', 'LMS': False},
{'Get 1 unique Champion scroll': 'Goblin_champion_scroll.png', 'LMS': False},
{'Get 1 unique Champion scroll': 'Goblin_champion_scroll.png', 'LMS': False},
{'Upgrade to the (expert) dragon archer headpiece': '110px-Chompy_bird_hat_expert_dragon_archer_detail.png', 'LMS': False},
{'Upgrade to the (expert) dragon archer headpiece': '110px-Chompy_bird_hat_expert_dragon_archer_detail.png', 'LMS': False},
{'Get a unique from Demonic gorillas': 'Zenyte_shard.png', 'LMS': False},
{'Get a unique from Demonic gorillas': 'Zenyte_shard.png', 'LMS': False},
{'Get 2 unique Ancient pages': 'Ancient_page.png', 'LMS': False},
{'Get 2 unique Ancient pages': 'Ancient_page.png', 'LMS': False},
{'Get a Dust battlestaff': 'Dust_battlestaff.png', 'LMS': False},
{'Get a Mist battlestaff': 'Mist_battlestaff.png', 'LMS': False},
{'Get 1 unique Obsidian armour drop': 'Obsidian_platebody.png', 'LMS': False},
{'Get a Toktz-mej-tal': 'Toktz-mej-tal.png', 'LMS': False},
{'Get dragon limbs': '130px-Dragon_limbs_detail.png', 'LMS': False},
{'Complete the Ardougne Elite Diary': 'Achievement_Diaries_icon.png', 'LMS': False},
{'Complete the Desert Elite Diary': 'Achievement_Diaries_icon.png', 'LMS': False},
{'Complete the Falador Elite Diary': 'Achievement_Diaries_icon.png', 'LMS': False},
{'Complete the Fremennik Elite Diary': 'Achievement_Diaries_icon.png', 'LMS': False},
{'Complete the Kandarin Elite Diary': 'Achievement_Diaries_icon.png', 'LMS': False},
{'Complete the Karamja Elite Diary': 'Achievement_Diaries_icon.png', 'LMS': False},
{'Complete the Kourend&Kebos Elite Diary': 'Achievement_Diaries_icon.png', 'LMS': False},
{'Complete the Lumbridge&Draynor Elite Diary': 'Achievement_Diaries_icon.png', 'LMS': False},
{'Complete the Morytania Elite Diary': 'Achievement_Diaries_icon.png', 'LMS': False},
{'Complete the Varrock Elite Diary': 'Achievement_Diaries_icon.png', 'LMS': False},
{'Complete the Western Provinces Elite Diary': 'Achievement_Diaries_icon.png', 'LMS': False},
{'Complete the Wilderness Elite Diary': 'Achievement_Diaries_icon.png', 'LMS': False},
{'Get the Crystal grail': 'Crystal_grail.png', 'LMS': False},
{'Get the Fish sack': '130px-Fish_sack_detail.png', 'LMS': False},
{"Get 1 unique piece of the Dagon'hai robes": '130px-Dagonhai_robe_top_detail.png', 'LMS': False},
{"Get 1 unique piece of the Dagon'hai robes": '130px-Dagonhai_robe_top_detail.png', 'LMS': False},
{'Get 1 unique from the Hallowed Sepulchre': '120px-Hallowed_mark_detail.png', 'LMS': False},
{'Get 1 unique from the Hallowed Sepulchre': '120px-Hallowed_mark_detail.png', 'LMS': False},
{'Get 1 unique from the Hallowed Sepulchre': '120px-Hallowed_mark_detail.png', 'LMS': False},
{'Get Granite boots': 'Granite_boots.png', 'LMS': False},
{'Get the Hosidius blueprints': '120px-Hosidius_blueprints_detail.png', 'LMS': False},
{"Get 1 unique from Shades of Mort'ton": 'Fine_cloth.png', 'LMS': False},
{"Get 1 unique from Shades of Mort'ton": 'Fine_cloth.png', 'LMS': False},
{"Get 1 unique from Shades of Mort'ton": 'Fine_cloth.png', 'LMS': False},
{"Get 1 unique from Shades of Mort'ton": 'Fine_cloth.png', 'LMS': False},
{"Get 1 unique from Shades of Mort'ton": 'Fine_cloth.png', 'LMS': False},
{"Get 1 unique from Shades of Mort'ton": 'Fine_cloth.png', 'LMS': False},
{"Get 1 unique from Shades of Mort'ton": 'Fine_cloth.png', 'LMS': False},
{'Get a new Golden godsword special from LMS': '120px-Armadyl_hilt_detail.png', 'LMS': True},
{'Get a new Golden godsword special from LMS': '120px-Armadyl_hilt_detail.png', 'LMS': True},
{'Get a new Golden godsword special from LMS': '120px-Armadyl_hilt_detail.png', 'LMS': True},
{'Get a new Golden godsword special from LMS': '120px-Armadyl_hilt_detail.png', 'LMS': True},
{'Get a Broken dragon pickaxe': 'Broken_pickaxe_dragon_detail.png', 'LMS' : False},
{'Get 1 unique from Revenants': 'Ancient_relic.png', 'LMS': False},
{'Get 1 unique from Revenants': 'Ancient_relic.png', 'LMS': False},
{'Get 1 unique from Revenants': 'Ancient_relic.png', 'LMS': False},
{'Get 1 unique from Revenants': 'Ancient_relic.png', 'LMS': False},
{'Get 1 unique from Guardians of the Rift': 'Hat_of_the_eye_detail.png', 'LMS': False},
{'Get 1 unique from Guardians of the Rift': 'Hat_of_the_eye_detail.png', 'LMS': False},
{'Get 1 unique from Guardians of the Rift': 'Hat_of_the_eye_detail.png', 'LMS': False},
{"Get 1 unique from the Phantom Muspah" : "Ancient_essence_detail.png", 'LMS': False},
{"Get 1 unique from the Phantom Muspah" : "Ancient_essence_detail.png", 'LMS': False},
{"Get 1 unique from Forestry" : "forestry_kit.png", 'LMS' : False},
{"Get 1 unique from Forestry" : "forestry_kit.png", 'LMS' : False},
{"Get 1 unique from Forestry" : "forestry_kit.png", 'LMS' : False},
{"Get 1 unique from Forestry" : "forestry_kit.png", 'LMS' : False},
{"Get 1 unique from Forestry" : "forestry_kit.png", 'LMS' : False},
{"Get 1 unique from Forestry" : "forestry_kit.png", 'LMS' : False},
{"Get 1 unique from the DT2 bosses" : "Soulreaper_axe_detail.png", 'LMS' : False},
{"Get 1 unique from the DT2 bosses" : "Soulreaper_axe_detail.png", 'LMS' : False},
{"Get 1 unique from the DT2 bosses" : "Soulreaper_axe_detail.png", 'LMS' : False},
{"Get 1 unique from the DT2 bosses" : "Soulreaper_axe_detail.png", 'LMS' : False},
{"Get 1 unique from the DT2 bosses" : "Soulreaper_axe_detail.png", 'LMS' : False},
{"Get 1 unique from the DT2 bosses" : "Soulreaper_axe_detail.png", 'LMS' : False},
{"Get 1 unique from the DT2 bosses" : "Soulreaper_axe_detail.png", 'LMS' : False},
{"Get 1 unique from the DT2 bosses" : "Soulreaper_axe_detail.png", 'LMS' : False},
{"Get 1 unique from the DT2 bosses" : "Soulreaper_axe_detail.png", 'LMS' : False},
{"Get 1 unique from the DT2 bosses" : "Soulreaper_axe_detail.png", 'LMS' : False},
{"Get 1 unique from the DT2 bosses" : "Soulreaper_axe_detail.png", 'LMS' : False},
{'Get 1 unique from Moons of Peril' : 'dual_macuahuitl.png', 'LMS' : False},
{'Get 1 unique from Moons of Peril' : 'dual_macuahuitl.png', 'LMS' : False},
{'Get 1 unique from Moons of Peril' : 'dual_macuahuitl.png', 'LMS' : False}
]



boss_pet = [
{'Abyssal orphan': 'Abyssal_orphan.png', 'LMS': False},
{'Baby mole': 'Baby_mole.png', 'LMS': False},
{'Callisto cub': 'Callisto_cub.png', 'LMS': False},
{'Hellpuppy': 'Hellpuppy.png', 'LMS': False},
{'Ikkle hydra': 'Ikkle_hydra.png', 'LMS': False},
{'Jal-nib-rek/Tzrek-zuk': 'Jal-nib-rek.png', 'LMS': False},
{'Kalphite princess': 'Kalphite_princess_2nd_form.png', 'LMS': False},
{"Lil' zik": 'Lil_zik.png', 'LMS': False},
{'Little nightmare': 'Little_nightmare.png', 'LMS': False},
{"Muphin" : "Muphin_detail.png", 'LMS' : False},
{'Nexling': 'Nexling.png', 'LMS' : False},
{'Noon/Midnight': 'Noon.png', 'LMS': False},
{'Olmlet': 'Olmlet.png', 'LMS': False},
{'Pet chaos elemental': 'Pet_chaos_elemental.png', 'LMS': False},
{'Pet dagannoth prime': 'Pet_dagannoth_prime.png', 'LMS': False},
{'Pet dagannoth rex': 'Pet_dagannoth_rex.png', 'LMS': False},
{'Pet dagannoth supreme': 'Pet_dagannoth_supreme.png', 'LMS': False},
{'Pet dark core/corporeal critter': 'Pet_dark_core.png', 'LMS': False},
{'Pet general graardor': 'Pet_general_graardor.png', 'LMS': False},
{"Pet k'ril tsutsaroth": 'Pet_kril_tsutsaroth.png', 'LMS': False},
{'Pet kraken': 'Pet_kraken.png', 'LMS': False},
{"Pet kree'arra": 'Pet_kreearra.png', 'LMS': False},
{'Pet smoke devil': 'Pet_smoke_devil.png', 'LMS': False},
{'Pet snakeling': 'Pet_snakeling.png', 'LMS': False},
{'Pet zilyana': 'Pet_zilyana.png', 'LMS': False},
{'Prince black dragon': 'Prince_black_dragon.png', 'LMS': False},
{"Scorpia's offspring": 'Scorpias_offspring.png', 'LMS': False},
{"Scurry" : "Scurry.png", 'LMS' : False},
{'Skotos': 'Skotos.png', 'LMS': False},
{'Sraracha': 'Sraracha.png', 'LMS': False},
{'Tzrek-jad': 'Tzrek-jad.png', 'LMS': False},
{"Tumeken's guardian": "Tumeken's_Guardian.png", 'LMS': False},
{'Venenatis spiderling': 'Venenatis_spiderling.png', 'LMS': False},
{"Vet'ion jr": 'Vetion_jr.png', 'LMS': False},
{'Vorki': 'Vorki.png', 'LMS': False},
{'Smol Heredit' : "smol_heredit.png", 'LMS' : False}
]

skill_pet = [
{'Baby chinchompa': 'Baby_chinchompa_black.png', 'LMS': False},
{'Beaver': 'Beaver.png', 'LMS': False},
{'Giant squirrel': 'Giant_squirrel.png', 'LMS': False},
{'Heron': 'Heron.png', 'LMS': False},
{'Rift guardian': 'Rift_guardian_fire.png', 'LMS': False},
{'Rock golem': 'Rock_golem.png', 'LMS': False},
{'Rocky': 'Rocky.png', 'LMS': False},
{'Tangleroot': 'Tangleroot.png', 'LMS': False},
{'Quetzin' : 'quetzin.png', 'LMS' : False}
]

other_pet = [
{'Bloodhound': 'Bloodhound.png', 'LMS': False},
{'Chompy chick': 'Chompy_chick.png', 'LMS': False},
{'Herbi': 'Herbi.png', 'LMS': False},
{'Pet penance queen': 'Pet_penance_queen.png', 'LMS': False},
{'Phoenix': 'Phoenix.png', 'LMS': False},
{'Youngllef': 'Youngllef.png', 'LMS': False},
{'Smolcano': 'Smolcano.png', 'LMS': False},
{'Tiny Tempor': 'Tiny_Tempor_chathead.png', 'LMS': False},
{"Lil' creator": 'Lil_Creator_chathead.png', 'LMS': False},
{'Abyssal protector': 'Abyssal_protector_chathead.png', 'LMS': False}
]


extra = [
{'Get a Jar of chemicals': 'Jar_of_chemicals.png', 'LMS': False},
{'Get a Jar of souls': 'Jar_of_souls.png', 'LMS': False},
{'Get a Jar of sand': 'Jar_of_sand.png', 'LMS': False},
{'Get a Jar of decay': 'Jar_of_decay.png', 'LMS': False},
{'Get a Jar of swamp': 'Jar_of_swamp.png', 'LMS': False},
{'Get a Jar of eyes': '90px-Jar_of_eyes_detail.png', 'LMS': False},
{'Get a Jar of stone': 'Jar_of_stone.png', 'LMS': False},
{'Get a Jar of darkness': 'Jar_of_darkness.png', 'LMS': False},
{'Get a Jar of dreams': 'Jar_of_dreams.png', 'LMS': False},
{'Get a Jar of dirt': '90px-Jar_of_dirt_detail.png', 'LMS': False},
{'Get a Jar of miasma': '90px-Jar_of_miasma_detail.png', 'LMS': False},
{'Get a Jar of spirits': '90px-Jar_of_spirits_detail.png', 'LMS': False},
{'Get a Jar of smoke': '90px-Jar_of_smoke_detail.png', 'LMS': False},
{'Get 1 unique sigil from Corp': 'Arcane_sigil.png', 'LMS': False},
{'Get 1 unique sigil from Corp': 'Arcane_sigil.png', 'LMS': False},
{'Get 1 unique sigil from Corp': 'Arcane_sigil.png', 'LMS': False},
{'Get an Infernal cape': 'Infernal_cape.png', 'LMS': False},
{'Get a Skeletal visage': 'Skeletal_visage.png', 'LMS': False},
{'Get a Wyvern visage': 'Wyvern_visage.png', 'LMS': False},
{'Get 1 unique from Raids (CoX or ToB or ToA)': 'Twisted_bow.png', 'LMS': False},
{'Get 1 unique from Raids (CoX or ToB or ToA)': 'Twisted_bow.png', 'LMS': False},
{'Get 1 unique from Raids (CoX or ToB or ToA)': 'Twisted_bow.png', 'LMS': False},
{'Get 1 unique from Raids (CoX or ToB or ToA)': 'Twisted_bow.png', 'LMS': False},
{'Get 1 unique from Raids (CoX or ToB or ToA)': 'Twisted_bow.png', 'LMS': False},
{'Get 1 unique from Raids (CoX or ToB or ToA)': 'Twisted_bow.png', 'LMS': False},
{'Get 1 unique from Raids (CoX or ToB or ToA)': 'Twisted_bow.png', 'LMS': False},
{'Get 1 unique from Raids (CoX or ToB or ToA)': 'Twisted_bow.png', 'LMS': False},
{'Get 1 unique from Raids (CoX or ToB or ToA)': 'Twisted_bow.png', 'LMS': False},
{'Get 1 unique from Raids (CoX or ToB or ToA)': 'Twisted_bow.png', 'LMS': False},
{'Get 1 unique from Raids (CoX or ToB or ToA)': 'Twisted_bow.png', 'LMS': False},
{'Get 1 unique from Raids (CoX or ToB or ToA)': 'Twisted_bow.png', 'LMS': False},
{'Get 1 unique from Raids (CoX or ToB or ToA)': 'Twisted_bow.png', 'LMS': False},
{'Get 1 unique from Raids (CoX or ToB or ToA)': 'Twisted_bow.png', 'LMS': False},
{'Get 1 unique from Raids (CoX or ToB or ToA)': 'Twisted_bow.png', 'LMS': False},
{'Finish all shared clue rewards ': 'Clue_scroll.png', 'LMS': False},
{'Finish all easy clue uniques': 'Clue_scroll_easy.png', 'LMS': False},
{'Finish all medium clue uniques': 'Clue_scroll_medium.png', 'LMS': False},
{'Finish all hard clue uniques': 'Clue_scroll_hard.png', 'LMS': False},
{'Finish all elite clue uniques': 'Clue_scroll_elite.png', 'LMS': False},
{'Finish all master clue uniques': 'Clue_scroll_master.png', 'LMS': False},
{'Finish all hard clue rare uniques': 'Clue_scroll_hard.png', 'LMS': False},
{'Finish all elite clue rare uniques': 'Clue_scroll_elite.png', 'LMS': False},
{'Finish all master rare clue uniques': 'Clue_scroll_master.png', 'LMS': False},
{'Complete the Gold decorative set': '130px-Decorative_armour_gold_platebody_detail.png', 'LMS': False},
{'Get 1 unique from Revenants': 'Ancient_relic.png', 'LMS': False},
{'Get 1 unique from Revenants': 'Ancient_relic.png', 'LMS': False},
{'Get 1 unique from Revenants': 'Ancient_relic.png', 'LMS': False},
{'Get 1 unique from Revenants': 'Ancient_relic.png', 'LMS': False},
{'Get 1 unique from Revenants': 'Ancient_relic.png', 'LMS': False},
{'Get 1 unique from Revenants': 'Ancient_relic.png', 'LMS': False},
{'Get 1 unique from Revenants': 'Ancient_relic.png', 'LMS': False},
{'Get an Amulet of eternal glory': '150px-Amulet_of_eternal_glory_detail.png', 'LMS': False},
{'Get 1 unique Dragonstone armour piece': 'Dragonstone_full_helm.png', 'LMS': False},
{'Get 1 unique Dragonstone armour piece': 'Dragonstone_full_helm.png', 'LMS': False},
{'Get 1 unique Dragonstone armour piece': 'Dragonstone_full_helm.png', 'LMS': False},
{'Get 1 unique Dragonstone armour piece': 'Dragonstone_full_helm.png', 'LMS': False},
{'Get 1 unique Dragonstone armour piece': 'Dragonstone_full_helm.png', 'LMS': False},
{'Get a full Dark totem drop from Skotizo': 'Dark_totem.png', 'LMS': False},
{"Get 1 unique piece of the Dagon'hai robes": '130px-Dagonhai_robe_top_detail.png', 'LMS': False},
{'Get 1 unique from the Zalcano': 'Zalcano_shard.png', 'LMS': False},
{'Get 1 unique from The Nightmare': 'Inquisitors_hauberk.png', 'LMS': False},
{'Get 1 unique from The Nightmare': 'Inquisitors_hauberk.png', 'LMS': False},
{'Get 1 unique from The Nightmare': 'Inquisitors_hauberk.png', 'LMS': False},
{'Get 1 unique from The Nightmare': 'Inquisitors_hauberk.png', 'LMS': False},
{'Get 1 unique from The Nightmare': 'Inquisitors_hauberk.png', 'LMS': False},
{'Get 1 unique from The Nightmare': 'Inquisitors_hauberk.png', 'LMS': False},
{'Get 1 unique from The Nightmare': 'Inquisitors_hauberk.png', 'LMS': False},
{'Get 1 unique from The Nightmare': 'Inquisitors_hauberk.png', 'LMS': False},
{'Get 1 unique mutagen': 'Tanzanite_mutagen.png', 'LMS': False},
{'Get 1 unique mutagen': 'Tanzanite_mutagen.png', 'LMS': False},
{'Get an Imbued heart or Eternal gem': 'Imbued_heart.png', 'LMS': False},
{'Get an Imbued heart or Eternal gem': 'Imbued_heart.png', 'LMS': False},
{'Get a Dragon full helm': 'Dragon_full_helm.png', 'LMS': False},
{'Get a Dragon metal lump': '100px-Dragon_metal_lump_detail.png', 'LMS': False},
{'Get a Dragon metal slice': '150px-Dragon_metal_slice_detail.png', 'LMS': False},
{'Get 1 unique piece of the Evil chicken outfit': 'Evil_chicken_head.png', 'LMS': False},
{'Get 1 unique piece of the Evil chicken outfit': 'Evil_chicken_head.png', 'LMS': False},
{'Get 1 unique piece of the Evil chicken outfit': 'Evil_chicken_head.png', 'LMS': False},
{'Get 1 unique piece of the Evil chicken outfit': 'Evil_chicken_head.png', 'LMS': False},
{'Get 1 unique from the Gauntlet': 'Blade_of_saeldor_inactive.png', 'LMS': False},
{'Get a Draconic visage': 'Draconic_visage.png', 'LMS': False},
{'Get a Dragonbone necklace': 'Dragonbone_necklace.png', 'LMS': False},
{"Get the Deadman's chest": '150px-Deadmans_chest_detail.png', 'LMS': False},
{"Get the Deadman's legs": '90px-Deadmans_legs_detail.png', 'LMS': False},
{"Get the Deadman's cape": '130px-Deadmans_cape_detail.png', 'LMS': False},
{'Get a Swift blade': '140px-Swift_blade_detail.png', 'LMS': False},
{'Get an Armadyl halo': '150px-Armadyl_halo_detail.png', 'LMS': False},
{'Get a Bandos halo': '150px-Bandos_halo_detail.png', 'LMS': False},
{'Get a Seren halo': '150px-Seren_halo_detail.png', 'LMS': False},
{'Get an Ancient halo': '150px-Ancient_halo_detail.png', 'LMS': False},
{'Get a Brassica halo': '130px-Brassica_halo_detail.png', 'LMS': False},
{'Get a Guthixian icon': '150px-Guthixian_icon_detail.png', 'LMS': False},
{'Get a Slepey tablet': '100px-Slepey_tablet_detail.png', 'LMS': False},
{'Get the Metamorphic dust': '150px-Metamorphic_dust_detail.png', 'LMS': False},
{'Get the Sanguine dust': '150px-Sanguine_dust_detail.png', 'LMS': False},
{'Get the Parasitic egg': '100px-Parasitic_egg_detail.png', 'LMS': False},
{'Get a Twisted ancestral colour kit': '170px-Twisted_ancestral_colour_kit_detail.png', 'LMS': False},
{'Get a Holy ornament kit': '150px-Holy_ornament_kit_detail.png', 'LMS': False},
{'Get a Sanguine ornament kit': '120px-Sanguine_ornament_kit_detail.png', 'LMS': False},
{'Get a Menaphite ornament kit': 'Menaphite_ornament_kit_detail', 'LMS': False},
{'Get a Cursed phalanx': 'Cursed_phalanx_detail.png', 'LMS': False},
{'Get a Masori crafting kit': 'Masori_crafting_kit_detail.png', 'LMS': False},
{'Get a Remnant of akkha': 'Remnant_of_akkha_detail.png', 'LMS': False},
{'Get a Remnant of ba-ba': 'Remnant_of_ba-ba_detail.png', 'LMS': False},
{'Get a Remnant of kephri': 'Remnant_of_kephri_detail.png', 'LMS': False},
{'Get a Remnant of zebak': 'Remnant_of_zebak_detail.png', 'LMS': False},
{'Get an Ancient remnant': 'Ancient_remnant_detail.png', 'LMS': False},
{'Get 1 unique from the Zalcano': 'Zalcano_shard.png', 'LMS': False},
{'Get 1 unique from the Hallowed Sepulchre': '120px-Hallowed_mark_detail.png', 'LMS': False},
{'Get 1 unique drop from God Wars Dungeon': 'Armadyl_helmet.png', 'LMS': False},
{'Get 1 unique drop from God Wars Dungeon': 'Armadyl_helmet.png', 'LMS': False},
{'Get 1 unique drop from God Wars Dungeon': 'Armadyl_helmet.png', 'LMS': False},
{'Get 1 unique drop from God Wars Dungeon': 'Armadyl_helmet.png', 'LMS': False},
{'Get 1 unique from Guardians of the Rift': 'Hat_of_the_eye_detail.png', 'LMS': False},
{'Get 1 unique from the Wildy bosses' : 'Skull_of_vetion_detail.png', 'LMS': False},
{'Get 1 unique from the Wildy bosses' : 'Skull_of_vetion_detail.png', 'LMS': False},
{'Get 1 unique from the Wildy bosses' : 'Skull_of_vetion_detail.png', 'LMS': False},
{'Get 1 unique from the Wildy bosses' : 'Skull_of_vetion_detail.png', 'LMS': False},
{'Get 1 unique from Fortis Colosseum' : 'dizanas_quiver.png', 'LMS' : False},
{'Get 1 unique from Fortis Colosseum' : 'dizanas_quiver.png', 'LMS' : False},
{'Get 1 unique from Fortis Colosseum' : 'dizanas_quiver.png', 'LMS' : False},
{'Get 1 unique from Fortis Colosseum' : 'dizanas_quiver.png', 'LMS' : False},
{'Get 1 unique from Fortis Colosseum' : 'dizanas_quiver.png', 'LMS' : False},
{'Get 1 unique from Fortis Colosseum' : 'dizanas_quiver.png', 'LMS' : False},
{'Get 1 unique from Fortis Colosseum' : 'dizanas_quiver.png', 'LMS' : False}
]


passive = [
{'Get the Golden tench': 'Golden_tench.png', 'LMS': False},
{'Get the Bottomless compost bucket': 'Bottomless_compost_bucket.png', 'LMS': False},
{'Get the Stale Baguette': 'Stale_baguette.png', 'LMS': False},
{'Get a Hespori seed': 'Hespori_seed_5.png', 'LMS': False},
{'Get an Iasor seed': 'Iasor_seed_5.png', 'LMS': False},
{'Get a Kronos seed': 'Iasor_seed_5.png', 'LMS': False},
{'Get an Attas seed': 'Iasor_seed_5.png', 'LMS': False},
{'Get all random event outfits': 'Mime_mask.png', 'LMS': False},
{'Get a Broken dragon hasta': '130px-Broken_dragon_hasta_detail.png', 'LMS': False},
{'Get a Mystic hat (dusk)': '130px-Mystic_hat_dusk_detail.png', 'LMS': False},
{'Get a Mystic robe top (dusk)': '180px-Mystic_robe_top_dusk_detail.png', 'LMS': False},
{'Get a Mystic robe bottom (dusk)': '180px-Mystic_robe_bottom_dusk_detail.png', 'LMS': False},
{'Get Mystic gloves (dusk)': '130px-Mystic_gloves_dusk_detail.png', 'LMS': False},
{'Get Mystic boots (dusk)': '120px-Mystic_boots_dusk_detail.png', 'LMS': False},
{'Get a Godsword shard 1': '120px-Godsword_shard_1_detail.png', 'LMS': False},
{'Get a Godsword shard 2': '120px-Godsword_shard_2_detail.png', 'LMS': False},
{'Get a Godsword shard 3': '320px-Godsword_shard_3_detail.png', 'LMS': False},
{'Get a Dark relic': 'Dark_relic.png', 'LMS': False},
{'Get a Torn prayer scroll': '160px-Torn_prayer_scroll_detail.png', 'LMS': False},
{"Get the Xeric's guard": 'Xerics_guard.png', 'LMS': False},
{"Get the Xeric's warrior": 'Xerics_warrior.png', 'LMS': False},
{"Get the Xeric's sentinel": 'Xerics_sentinel.png', 'LMS': False},
{"Get the Xeric's general": 'Xerics_general.png', 'LMS': False},
{"Get the Xeric's champion": 'Xerics_champion.png', 'LMS': False},
{'Get the Sinhaza shroud tier 1': 'Sinhaza_shroud_tier_1.png', 'LMS': False},
{'Get the Sinhaza shroud tier 2': 'Sinhaza_shroud_tier_2.png', 'LMS': False},
{'Get the Sinhaza shroud tier 3': 'Sinhaza_shroud_tier_3.png', 'LMS': False},
{'Get the Sinhaza shroud tier 4': 'Sinhaza_shroud_tier_4.png', 'LMS': False},
{'Get the Sinhaza shroud tier 5': 'Sinhaza_shroud_tier_5.png', 'LMS': False},
{'Get a cut Onyx from Tekton': 'Onyx.png', 'LMS': False},
{'Get the Gauntlet cape': '130px-Gauntlet_cape_detail.png', 'LMS': False},
{"Get the Victor's cape (1)": '150px-Victors_cape_1_detail.png', 'LMS': False},
{"Get the Victor's cape (10)": '150px-Victors_cape_10_detail.png', 'LMS': False},
{"Get the Victor's cape (50)": '150px-Victors_cape_50_detail.png', 'LMS': False},
{"Get the Victor's cape (100)": '150px-Victors_cape_100_detail.png', 'LMS': False},
{"Get the Victor's cape (500)": '150px-Victors_cape_500_detail.png', 'LMS': False},
{"Get the Victor's cape (1000)": '150px-Victors_cape_1000_detail.png', 'LMS': False},
{"Get the Icthlarin's shroud (tier 1)": "Icthlarins_shroud_tier_1_detail.png"},
{"Get the Icthlarin's shroud (tier 2)": "Icthlarins_shroud_tier_2_detail.png"},
{"Get the Icthlarin's shroud (tier 3)": "Icthlarins_shroud_tier_3_detail.png"},
{"Get the Icthlarin's shroud (tier 4)": "Icthlarins_shroud_tier_4_detail.png"},
{"Get the Icthlarin's shroud (tier 5)": "Icthlarins_shroud_tier_5_detail.png"},
{"Get the Charged ice": "Charged_ice_detail.png"},
{'Get a Dark claw': 'Dark_claw.png', 'LMS': False}
]

def to_old_task(new_task):
    return { new_task['name']: new_task['assetImage'], 'LMS': 'isLMS' in new_task }

if __name__ == "__main__":
    print(easy)
    print('\n\n\n\n\n\n\n\n\n')
    print(list(map(to_old_task, tasklists.easy)))
    assert easy == list(map(to_old_task, tasklists.easy))
