
easy_tips = [
'Bolt racks are obtained from the Barrows Combat Minigame.',
'Mole Skin and Mole Claw are guarenteed drops from the Giant Mole Boss.',
'Wintertodt uniques come from the Wintertodt Skilling boss. Dragon axe does not count this task. Dragon axe is a Dagannoth Kings task. Why Fletch?',
'Wintertodt uniques come from the Wintertodt Skilling boss. Dragon axe does not count this task. Dragon axe is a Dagannoth Kings task. Why Fletch?',
'Wintertodt uniques come from the Wintertodt Skilling boss. Dragon axe does not count this task. Dragon axe is a Dagannoth Kings task. Why Fletch?',
'Wintertodt uniques come from the Wintertodt Skilling boss. Dragon axe does not count this task. Dragon axe is a Dagannoth Kings task. Why Fletch?',
'Wintertodt uniques come from the Wintertodt Skilling boss. Dragon axe does not count this task. Dragon axe is a Dagannoth Kings task. Why Fletch?',
'Potential reward from beginner  clues. Typically you would want to kill Goblins or Minotaurs for the clues themselves. ',
'Potential reward from beginner  clues. Typically you would want to kill Goblins or Minotaurs for the clues themselves. ',
'Potential reward from easy clues. Pick pocketing H.A.M members are a great way of getting the clues. ',
'Potential reward from easy clues. Pick pocketing H.A.M members are a great way of getting the clues. ',
'Potential reward from easy clues. Pick pocketing H.A.M members are a great way of getting the clues. ',
'Potential reward from easy clues. Pick pocketing H.A.M members are a great way of getting the clues. ',
'Potential reward from easy clues. Pick pocketing H.A.M members are a great way of getting the clues. ',
'Potential reward from easy clues. Pick pocketing H.A.M members are a great way of getting the clues. ',
'Potential reward from medium clues. Killing guards is a decent way of getting the clues, later on Ecletic impings are are fantasic source for them.',
'Potential reward from medium clues. Killing guards is a decent way of getting the clues, later on Ecletic impings are are fantasic source for them.',
'Potential reward from medium clues. Killing guards is a decent way of getting the clues, later on Ecletic impings are are fantasic source for them.',
'Potential reward from medium clues. Killing guards is a decent way of getting the clues, later on Ecletic impings are are fantasic source for them.',
'Potential reward from hard clues. Killing hellhounds is a decent way of getting the clues.',
'Potential reward from hard clues. Killing hellhounds is a decent way of getting the clues.',
'Can be purchased as a reward from the Barbarian Assault Combat Minigame. You can ask the Clan Chat or the Discord to gather a team, last ditch effort would be to do PUB runs in World 306.. YIKES. ',
'Can be purchased as a reward from the Barbarian Assault Combat Minigame. You can ask the Clan Chat or the Discord to gather a team, last ditch effort would be to do PUB runs in World 306.. YIKES. ',
'Can be purchased as a reward from the Barbarian Assault Combat Minigame. You can ask the Clan Chat or the Discord to gather a team, last ditch effort would be to do PUB runs in World 306.. YIKES. ',
'Can be purchased as a reward from the Castle Wars \"Combat Minigame\". The best way to do this is by using an alt account and join the games with both accounts. Castle Wars is F2P therefore, alt account does not needed to be a member. Enjoy your AFK time. ',
'Can be purchased as a reward from the Castle Wars \"Combat Minigame\". The best way to do this is by using an alt account and join the games with both accounts. Castle Wars is F2P therefore, alt account does not needed to be a member. Enjoy your AFK time. ',
'Can be purchased as a reward from the Castle Wars \"Combat Minigame\". The best way to do this is by using an alt account and join the games with both accounts. Castle Wars is F2P therefore, alt account does not needed to be a member. Enjoy your AFK time. ',
'Can be purchased as a reward from the Castle Wars \"Combat Minigame\". The best way to do this is by using an alt account and join the games with both accounts. Castle Wars is F2P therefore, alt account does not needed to be a member. Enjoy your AFK time. ',
'Potential reward from the Fishing Trawler minigame. Protip: Turn the camera shake off whilst within the minigame and don\'t let your feet get too wet. ',
'Potential reward from the Fishing Trawler minigame. Protip: Turn the camera shake off whilst within the minigame and don\'t let your feet get too wet. ',
'Potential reward from the Fishing Trawler minigame. Protip: Turn the camera shake off whilst within the minigame and don\'t let your feet get too wet. ',
'Potential reward from the Fishing Trawler minigame. Protip: Turn the camera shake off whilst within the minigame and don\'t let your feet get too wet. ',
'Potential reward from the Gnome Restaurant minigame. Complete hard deliveries. ',
'Can be purchased as a reward from the Mage Mage Training Arena minigame. ',
'Can be purchased as a reward from the Mage Mage Training Arena minigame. ',
'Can be purchased as a reward from the Mage Mage Training Arena minigame. ',
'Can be purchased as a reward from the Mage Mage Training Arena minigame. ',
'Can be purchased as a reward from the Pest Control Combat Minigame. ',
'Can be purchased as a reward from the Pest Control Combat Minigame. ',
'Can be purchased as a reward from the Pest Control Combat Minigame. ',
'Potential reward from the Rogues Den Minigame. ',
'Potential reward from the Rogues Den Minigame.',
'Potential reward from the Shades of Morton Minigame. ',
'Potential reward from the Shades of Morton Minigame. ',
'Guarenteed reward from the Temple Trekking Minigame find the correct \"Bog\" event. Do easy Treks for best results. ',
'Can be purchased as a reward from the Tithe Farm Minigame. Plant those seeds! ',
'Can be purchased as a reward from the Tithe Farm Minigame. Plant those seeds! ',
'Can be purchased as a reward from the Trouble Brewing Minigame. Fill and deposit 100 buckets of water. Enjoy your AFK time. ',
'Can be purchased as a reward from the Trouble Brewing Minigame. Fill and deposit 100 buckets of water. Enjoy your AFK time. ',
'Can be purchased as a reward from the Trouble Brewing Minigame. Fill and deposit 100 buckets of water. Enjoy your AFK time. ',
'Can be purchased as a reward from the Aerial Fishing hunter method. Good luck with that RSI. ',
'Can be received from a drop from several monsters. PRO TIP: Don\'t go 19,000 dry for goblin scroll...',
'Guarenteed from Chompy bird hunting. ',
'Can be received as a drop from the Creature Creation \"Minigame\". Make a abominiation with two different ingredients, mix together and murder. ',
'Can be received as a drop from the Creature Creation \"Minigame\". Make a abominiation with two different ingredients, mix together and murder. ',
'Can be received as a drop from the Creature Creation \"Minigame\". Make a abominiation with two different ingredients, mix together and murder. ',
'Can be received as a drop from the Creature Creation \"Minigame\". Make a abominiation with two different ingredients, mix together and murder. ',
'Can be received as a drop from the Creature Creation \"Minigame\". Make a abominiation with two different ingredients, mix together and murder. ',
'Can be received as a drop from Cycolps in the warrier guild. Good ole defender grind.',
'Can be received by opening the chest(s) on Fossil Island with 100 Numulite. Killing hoop snakes for the Numulite is recommended. ',
'Can be received by opening the chest(s) on Fossil Island with 100 Numulite. Killing hoop snakes for the Numulite is recommended. ',
'Can be purchased as a reward from the Motherlode Mine training method. Pay-Dirt!',
'Can be purchased as a reward from the Motherlode Mine training method. Pay-Dirt!',
'Can be purchased as a reward from the Motherlode Mine training method. Pay-Dirt!',
'Can be purchased as a reward from the Motherlode Mine training method. Pay-Dirt!',
'Can be received when searching remains in the Whirlpool Dungeon. Check out the Ancient Page guide on the FAQ page! I\'m not going to remember to link that page here I feel.',
'Can be received when searching remains in the Whirlpool Dungeon. Check out the Ancient Page guide on the FAQ page! I\'m not going to remember to link that page here I feel.',
'Can be received as a drop from any Revenant. ',
'Can be purchased from Grace in the Rogues Den. Run laps, get marks. Eww Agility. ',
'Can be purchased from Grace in the Rogues Den. Run laps, get marks. Eww Agility. ',
'Can be purchased from Grace in the Rogues Den. Run laps, get marks. Eww Agility. ',
'Can be received as drop from Crawling hands. Coincidence? Maybe. ',
'Can be received as a drop from Cocatrice.',
'Can be received as a drop from Mogres. ',
'Can be received as a drop from Mogres. ',
'Can be received as a drop from Brine Rats.',
'Can be received as a drop from Turoths. ',
'Can be received as a drop from Turoths. ',
'Can be received as a drop from Cave Horrors. ',
'Can be received as a drop from serveral monsters. You must start by obtaining the lowest pair of you do not currently have. Bronze through Rune. ',
'Can be received as a drop from serveral monsters. You must start by obtaining the lowest pair of you do not currently have. Bronze through Rune. ',
'Can be received as a drop from serveral monsters. You must start by obtaining the lowest pair of you do not currently have. Bronze through Rune. ',
'Can be received as a drop from serveral monsters. You must start by obtaining the lowest pair of you do not currently have. Bronze through Rune. ',
'Can be received as a drop from serveral monsters. You must start by obtaining the lowest pair of you do not currently have. Bronze through Rune. ',
'Can be received as a drop from Wall Beast or Basilisk. ',
'Can be received as a drop from Desert Lizards, Rockslugs, Lizards, Small Lizards and, Sulphur Lizards. ',
'Can be received as a drop from Cocatrice.',
'Can be received as a drop from Infernal Mages. Note, the Lava Battlestaff does not count as it is not in theeee Collection Log. ',
'Can be received as a drop from Infernal Mages. Note, the Lava Battlestaff does not count as it is not in theeee Collection Log. ',
'Can be received as a drop from Banshees. ',
'Can be received as a drop from TzHaar creatures. Recommended to kill Kets until you have all their unique drops, the kill Xils. ',
'Can be received as a drop from TzHaar creatures. Recommended to kill Kets until you have all their unique drops, the kill Xils. ',
'Obainted randomly while fishing for swordfish. Good luck!',
'Obtained randomly while Big Net fishing. Good luck!',
'Can be received as a drop from any monster that drop big bones.',
'Can be received as a drop from any monster in the Wilderness God Wars Dungeon. Recommended to kill imps and hopping between two worlds for faster kills. ',
'Can be received as a drop from any mosnter in the Catacombs of Kourend.  ',
'Can be received as a drop from any mosnter in the Catacombs of Kourend.  ',
'Can be received as a drop from any mosnter in the Catacombs of Kourend.  ',
'Can be received as a drop from any mosnter in the Catacombs of Kourend.  ',
'Can be purchased as a reward in the Mining Guild. Obtain unidentified minerals by minining in the guild. Mining iron ore is recommended. ',
'Can be received as a drop from Minotaurs in the Stronghold of Security. ',
'Can be received as a drop from Ankou in the Stronghold of Security. ',
'Can be received as a drop from Catablepon in the Stronghold of Security.',
'Can be received as a drop from Flesh Crawlers in the Stronghold of Security.',
'Can be received as a drop from Moss Giants',
'Can be received as a drop from Hill Giants',
'Can be received as a drop from Crabs.',
'Can be received as a drop from Lizardmen. ',
'Complete all the diary tasks. Don\'t really have much else to tell you. ',
'Complete all the diary tasks. Don\'t really have much else to tell you. ',
'Complete all the diary tasks. Don\'t really have much else to tell you. ',
'Complete all the diary tasks. Don\'t really have much else to tell you. ',
'Complete all the diary tasks. Don\'t really have much else to tell you. ',
'Complete all the diary tasks. Don\'t really have much else to tell you. ',
'Complete all the diary tasks. Don\'t really have much else to tell you. ',
'Complete all the diary tasks. Don\'t really have much else to tell you. ',
'Complete all the diary tasks. Don\'t really have much else to tell you. ',
'Complete all the diary tasks. Don\'t really have much else to tell you. ',
'Complete all the diary tasks. Don\'t really have much else to tell you. ',
'Complete all the diary tasks. Don\'t really have much else to tell you. ',
'Can be purchased as a reward from the Mahogany Homes Minigame. Don\'t pull a Kats and do Daddys Home. :) ',
'Can be received as a reward from the Tempoross Skilling Boss. ',
'Can be received as a reward from the Tempoross Skilling Boss. ',
'Can be received as a reward from the Tempoross Skilling Boss. ',
'Can be received as a reward from the Tempoross Skilling Boss. ',
'Can be received as drops from performing various activities within the Ruins_of_Camdozaal.',
'Can be received as drops from performing various activities within the Ruins_of_Camdozaal.',
'Can be received as a reward from the Guardians of the Rift Skilling Minigame. Runecrafting... it\'s actually kinda fun now.',
'Can be received as a reward from the Guardians of the Rift Skilling Minigame. Runecrafting... it\'s actually kinda fun now.',
'Can be received as a reward from the Guardians of the Rift Skilling Minigame. Runecrafting... it\'s actually kinda fun now.',
'Can be received as a reward from the Guardians of the Rift Skilling Minigame. Runecrafting... it\'s actually kinda fun now.',
"Can be purchased as a reward from the Giants' Foundry Skilling Minigame.",
"Can be purchased as a reward from the Giants' Foundry Skilling Minigame.",
"Can be purchased as a reward from the Giants' Foundry Skilling Minigame.",
"Can be purchased as a reward from the Giants' Foundry Skilling Minigame.",
'Can be purchased as a reward from the Friendly Forester',
'Sturdy beehive parts is an item that can be obtained as a reward from the Beehive forestry event',
'Can be obtained by using pheasant tail feathers from foresty!',
"Can be obtained by slaughtering Warped Terror Birds / Warped Tortoises",
'Received as a drop when completing Hunters Rumours',
'Received as a drop from sulphur Nagua',
]

medium_tips = [
'Can be received as a reward from the Barrows Combat Minigame. ',
'Can be received as a reward from the Barrows Combat Minigame. ',
'Can be received as a reward from the Barrows Combat Minigame. ',
'Can be received as a reward from the Barrows Combat Minigame. ',
'Can be received as a reward from the Barrows Combat Minigame. ',
'Can be received as a drop from the Crazy Archaeologist.',
'Can be received as a drop from the Crazy Archaeologist.',
'Can be received as a drop from the Crazy Archaeologist.',
'Guarenteed reward upon completion of the Fight Caves. Good luck with Jad!',
'Guarenteed drop from the Grotesque Guardians Boss. ',
'Can be received as a drop form Obor. ',
'Wintertodt uniques come from the Wintertodt Skilling boss. Dragon axe does not count this task. Dragon axe is a Dagannoth Kings task. Rip TaskOnly UIM ',
'Wintertodt uniques come from the Wintertodt Skilling boss. Dragon axe does not count this task. Dragon axe is a Dagannoth Kings task. Rip TaskOnly UIM ',
'Wintertodt uniques come from the Wintertodt Skilling boss. Dragon axe does not count this task. Dragon axe is a Dagannoth Kings task. Rip TaskOnly UIM ',
'Guarenteed drop from the Zulrah Boss. ',
'Can be received as a drop from Zulrah. ',
'Potential reward from beginner clues. Typically you would want to kill Goblins or Minotaurs for the clues themselves. ',
'Potential reward from beginner clues. Typically you would want to kill Goblins or Minotaurs for the clues themselves. ',
'Potential reward from easy clues. Pick pocketing H.A.M members are a great way of getting the clues. ',
'Potential reward from easy clues. Pick pocketing H.A.M members are a great way of getting the clues. ',
'Potential reward from easy clues. Pick pocketing H.A.M members are a great way of getting the clues. ',
'Potential reward from easy clues. Pick pocketing H.A.M members are a great way of getting the clues. ',
'Potential reward from easy clues. Pick pocketing H.A.M members are a great way of getting the clues. ',
'Potential reward from easy clues. Pick pocketing H.A.M members are a great way of getting the clues. ',
'Potential reward from medium clues. Killing guards is a decent way of getting the clues, later on Ecletic impings are are fantasic source for them.',
'Potential reward from medium clues. Killing guards is a decent way of getting the clues, later on Ecletic impings are are fantasic source for them.',
'Potential reward from medium clues. Killing guards is a decent way of getting the clues, later on Ecletic impings are are fantasic source for them.',
'Potential reward from medium clues. Killing guards is a decent way of getting the clues, later on Ecletic impings are are fantasic source for them.',
'Potential reward from hard clues. Killing hellhounds is a decent way of getting the clues.',
'Potential reward from hard clues. Killing hellhounds is a decent way of getting the clues.',
'Potential reward from hard clues. Killing hellhounds is a decent way of getting the clues.',
'Potential reward from hard clues. Killing hellhounds is a decent way of getting the clues.',
'Can be purchased as a reward from the Barbarian Assault Combat Minigame. You can ask the Clan Chat or the Discord to gather a team, last ditch effort would be to do PUB runs in World 306.. YIKES. ',
'Can be purchased as a reward from the Barbarian Assault Combat Minigame. You can ask the Clan Chat or the Discord to gather a team, last ditch effort would be to do PUB runs in World 306.. YIKES. ',
'Can be purchased as a reward from the Barbarian Assault Combat Minigame. You can ask the Clan Chat or the Discord to gather a team, last ditch effort would be to do PUB runs in World 306.. YIKES. ',
'Can be purchased as a reward from the Barbarian Assault Combat Minigame. You can ask the Clan Chat or the Discord to gather a team, last ditch effort would be to do PUB runs in World 306.. YIKES. ',
'Can be purchased as a reward from the Barbarian Assault Combat Minigame. You can ask the Clan Chat or the Discord to gather a team, last ditch effort would be to do PUB runs in World 306.. YIKES. ',
'Can be received as a drop Terror Dogs. ',
'Can be purchased as a reward from the Castle Wars \"Combat Minigame\". The best way to do this is by using an alt account and join the games with both accounts. Castle Wars is F2P therefore, alt account does not needed to be a member. Enjoy your AFK time.',
'Can be purchased as a reward from the Castle Wars \"Combat Minigame\". The best way to do this is by using an alt account and join the games with both accounts. Castle Wars is F2P therefore, alt account does not needed to be a member. Enjoy your AFK time.',
'Can be purchased as a reward from the Castle Wars \"Combat Minigame\". The best way to do this is by using an alt account and join the games with both accounts. Castle Wars is F2P therefore, alt account does not needed to be a member. Enjoy your AFK time.',
'Potential reward from the Gnome Restaurant minigame. You should no the deal by now having done this task in the Easy Tier!',
'Potential reward from the Gnome Restaurant minigame. You should no the deal by now having done this task in the Easy Tier!',
'Can be purchased as a reward from the Mage Mage Training Arena minigame. ',
'Can be purchased as a reward from the Mage Mage Training Arena minigame. ',
'Can be purchased as a reward from the Mage Mage Training Arena minigame. ',
'Can be purchased as a reward from the Mage Mage Training Arena minigame. ',
'Can be purchased as a reward from the Mage Mage Training Arena minigame. ',
'Can be purchased as a reward from the Pest Control Combat Minigame. ',
'Can be purchased as a reward from the Pest Control Combat Minigame. ',
'Can be purchased as a reward from the Pest Control Combat Minigame. ',
'Can be purchased as a reward from the Pest Control Combat Minigame. ',
'Can be purchased as a reward from the Pest Control Combat Minigame. ',
'Potential reward from the Rogues Den Minigame. ',
'Potential reward from the Rogues Den Minigame. ',
'Potential reward from the Rogues Den Minigame. ',
'Potential reward from the Shades of Morton Minigame. ',
'Potential reward from the Shades of Morton Minigame. ',
'Potential reward from the Shades of Morton Minigame. ',
'Guarenteed reward from the Temple Trekking Minigame find the correct \"Bog\" event. Do easy Treks for best results. ',
'Guarenteed reward from the Temple Trekking Minigame find the correct \"Bog\" event. Do easy Treks for best results. ',
'Guarenteed reward from the Temple Trekking Minigame find the correct \"Bog\" event. Do easy Treks for best results. ',
'Can be purchased as a reward from the Tithe Farm Minigame. Plant those seeds! ',
'Can be purchased as a reward from the Tithe Farm Minigame. Plant those seeds! ',
'Can be purchased as a reward from the Tithe Farm Minigame. Plant those seeds! ',
'Can be purchased as a reward from the Tithe Farm Minigame. Plant those seeds! ',
'Can be purchased as a reward from the Trouble Brewing Minigame. Fill and deposit 100 buckets of water. Enjoy your AFK time. ',
'Can be purchased as a reward from the Trouble Brewing Minigame. Fill and deposit 100 buckets of water. Enjoy your AFK time. ',
'Can be purchased as a reward from the Trouble Brewing Minigame. Fill and deposit 100 buckets of water. Enjoy your AFK time. ',
'Can be purchased as a reward from the Trouble Brewing Minigame. Fill and deposit 100 buckets of water. Enjoy your AFK time. ',
'Can be purchased as a reward from the Aerial Fishing hunter method. Good luck with that RSI. ',
'Can be purchased as a reward from the Aerial Fishing hunter method. Good luck with that RSI. ',
'Can be received from a drop from several monsters.',
'Can be received from a drop from several monsters.',
'Can be received as a drop from Elder Chaos Druids. ',
'Can be received as a drop from Elder Chaos Druids. ',
'Guarenteed from Chompy bird hunting. ',
'Can be received as a drop from the Creature Creation \"Minigame\". Make a abominiation with two different ingredients, mix together and murder. ',
'Can be received as a drop from the Creature Creation \"Minigame\". Make a abominiation with two different ingredients, mix together and murder. ',
'Can be received as a drop from Cyclops in the Warriors Guild basement. ',
'Can be received by opening the chest(s) on Fossil Island with 100 Numulite. Killing hoop snakes for the Numulite is recommended. ',
'Can be received by opening the chest(s) on Fossil Island with 100 Numulite. Killing hoop snakes for the Numulite is recommended. ',
'Can be received by opening the chest(s) on Fossil Island with 100 Numulite. Killing hoop snakes for the Numulite is recommended. ',
'Can be purchased as a reward from the Motherlode Mine training method. Pay-Dirt!',
'Can be purchased as a reward from the Motherlode Mine training method. Pay-Dirt!',
'Can be received when searching remains in the Whirlpool Dungeon. Check out the Ancient Page guide on the FAQ page! I\'m not going to remember to link that page here I feel.',
'Can be received when searching remains in the Whirlpool Dungeon. Check out the Ancient Page guide on the FAQ page! I\'m not going to remember to link that page here I feel.',
'Can be received when searching remains in the Whirlpool Dungeon. Check out the Ancient Page guide on the FAQ page! I\'m not going to remember to link that page here I feel.',
'Can be received when searching remains in the Whirlpool Dungeon. Check out the Ancient Page guide on the FAQ page! I\'m not going to remember to link that page here I feel.',
'Can be received when searching remains in the Whirlpool Dungeon. Check out the Ancient Page guide on the FAQ page! I\'m not going to remember to link that page here I feel.',
'Can be received when searching remains in the Whirlpool Dungeon. Check out the Ancient Page guide on the FAQ page! I\'m not going to remember to link that page here I feel.',
'Can be purchased from Grace in the Rogues Den. Run laps, get marks. Agility isn\'t too bad.  ',
'Can be purchased from Grace in the Rogues Den. Run laps, get marks. Agility isn\'t too bad.',
'Can be purchased from Grace in the Rogues Den. Run laps, get marks. Agility isn\'t too bad.',
'Guarenteed drop by fighting the members of the Shayzien Combat Ring. Must obtain armour sets 1 through 5 to complete the task. ',
'Can be received as a drop from Basilisk. ',
'Can be received as a drop from Gargoyles. ',
'Can be received as a drop from Gargoyles. ',
'Can be received as a drop from Kurask.',
'Can be received as a drop from Kurask.',
'Can be received as a drop from Fossil Island Wyverns. ',
'Can be received as a drop from Wyverns. ',
'Can be received as a drop from serveral monsters. You must start by obtaining the lowest pair of you do not currently have. Bronze through Rune. ',
'Can be received as a drop from serveral monsters. You must start by obtaining the lowest pair of you do not currently have. Bronze through Rune. ',
'Can be received as a drop from Aberrant spectres. ',
'Can be received as a drop from TzHaar creatures. Recommended to kill Kets until you have all their unique drops, the kill Xils. ',
'Can be received as a drop from TzHaar creatures. Recommended to kill Kets until you have all their unique drops, the kill Xils. ',
'Can be received as a drop from TzHaar creatures. Recommended to kill Kets until you have all their unique drops, the kill Xils. ',
'Can be received as a drop from TzHaar creatures. Recommended to kill Kets until you have all their unique drops, the kill Xils. ',
'Obtained randomly whilst fishing for sharks. Good Luck. ',
'Can be received as a drop rarely, from any monster that drop big bones.',
'Can be received as drop from Shaman Ogress Warriors',
'Can be purchased as a reward in the Mining Guild. Obtain unidentified minerals by minining in the guild. Mining iron ore is recommended. ',
'Can be received as a drop from any Revenant.',
'Can be received as a drop from any Revenant.',
'Complete all the diary tasks. Don\'t really have much else to tell you. ',
'Complete all the diary tasks. Don\'t really have much else to tell you. ',
'Complete all the diary tasks. Don\'t really have much else to tell you. ',
'Complete all the diary tasks. Don\'t really have much else to tell you. ',
'Complete all the diary tasks. Don\'t really have much else to tell you. ',
'Complete all the diary tasks. Don\'t really have much else to tell you. ',
'Complete all the diary tasks. Don\'t really have much else to tell you. ',
'Complete all the diary tasks. FINALLY AVA\'S DEVICE!',
'Complete all the diary tasks. Don\'t really have much else to tell you. ',
'Complete all the diary tasks. Don\'t really have much else to tell you. ',
'Complete all the diary tasks. Don\'t really have much else to tell you. ',
'Complete all the diary tasks. Don\'t really have much else to tell you. ',
'Can be received as a drop from Undead Druids. ',
'Can be received as a drop from Sarachnis. ',
'Can be purchased from Tithe farm or Slayer shop. ',
'Can be purchased as a reward from the Mahogany Homes Minigame. Don\'t pull a Kats and do Daddys Home. :) This joke is more applicable in easy tier but still, don\'t.  ',
'Can be purchased as a reward from the Mahogany Homes Minigame. Don\'t pull a Kats and do Daddys Home. :) This joke is more applicable in easy tier but still, don\'t.  ',
'Can be purchased as a reward from the Mahogany Homes Minigame. Don\'t pull a Kats and do Daddys Home. :) This joke is more applicable in easy tier but still, don\'t. ',
'Can be purchased as a reward from the Soul Wars Minigame. ',
'Can be purchased as a reward from the Barbarian Assault Combat Minigame. You can ask the Clan Chat or the Discord to gather a team, last ditch effort would be to do PUB runs in World 306.. Defender is best role, AMA. ',
'Can be purchased as a reward from the Last Man Standing PVP Minigame. ',
'Can be purchased as a reward from the Last Man Standing PVP Minigame. ',
'Can be purchased as a reward from the Last Man Standing PVP Minigame. ',
'Can be purchased as a reward from the Last Man Standing PVP Minigame. ',
'Can be purchased as a reward from the Last Man Standing PVP Minigame. ',
'Can be purchased as a reward from the Last Man Standing PVP Minigame. ',
'Can be purchased as a reward from the Last Man Standing PVP Minigame. ',
'Can be purchased as a reward from the Last Man Standing PVP Minigame. ',
'Can be purchased as a reward from the Shooting Stars Diversion and Distraction Minigame. Star Miners Clan Chat to find stars. ',
'Can be purchased as a reward from the Shooting Stars Diversion and Distraction Minigame. Star Miners Clan Chat to find stars. ',
'Can be received as a reward from the Tempoross Skilling Boss. ',
'Can be received as a reward from the Tempoross Skilling Boss. ',
'Can be received as a reward from the Tempoross Skilling Boss. ',
'Can be purchased as a reward from the Underwater agility course on Fossil Island. ',
'Can be received as a reward from the Tempoross Skilling Boss. ',
'Can be received as a reward from the Tempoross Skilling Boss. ',
'Can be received as a reward from the Guardians of the Rift Skilling Minigame. Runecrafting... it\'s actually kinda fun now.',
'Can be received as a reward from the Guardians of the Rift Skilling Minigame. Runecrafting... it\'s actually kinda fun now.',
'Can be received as a reward from the Guardians of the Rift Skilling Minigame. Runecrafting... it\'s actually kinda fun now.',
'Can be received as a reward from the Guardians of the Rift Skilling Minigame. Runecrafting... it\'s actually kinda fun now.',
"Can be purchased as a reward from the Giants' Foundry Skilling Minigame.",
"Can be purchased as a reward from the Giants' Foundry Skilling Minigame.",
"Can be purchased as a reward from the Giants' Foundry Skilling Minigame.",
"Can be purchased as a reward from the Giants' Foundry Skilling Minigame.",
'Can be purchased as a reward from the Friendly Forester',
'Can be purchased as a reward from the Friendly Forester',
'Can be purchased as a reward from the Friendly Forester',
'Can be purchased as a reward from the Friendly Forester',
'Received as a drop when killing Scurrius',
'Received as a drop from killing armoured zombies',
'Received as a drop from Moons of Peril bosses',
'Received as a drop from Moons of Peril bosses',
'Received as a drop from Moons of Peril bosses',
'Received as a drop from Moons of Peril bosses',
'Received as a drop when completing Hunters Rumours'
]


hard_tips = [
'Can be received as a reward from the Barrows Combat Minigame. ',
'Can be received as a reward from the Barrows Combat Minigame. ',
'Can be received as a reward from the Barrows Combat Minigame. ',
'Can be received as a reward from the Barrows Combat Minigame. ',
'Can be received as a reward from the Barrows Combat Minigame. ',
'Can be received as a reward from the Barrows Combat Minigame. ',
'Can be received as a reward from the Barrows Combat Minigame. ',
'Can be received as a reward from the Barrows Combat Minigame. ',
'Can be received as a reward from the Barrows Combat Minigame. ',
'Can be received as a reward from the Barrows Combat Minigame. ',
'Can be received as a reward from the Barrows Combat Minigame. ',
'Can be received as a reward from the Barrows Combat Minigame. ',
'Can be received as a reward from the Barrows Combat Minigame. ',
'Can be received as a reward from the Barrows Combat Minigame. ',
'Can be received as a reward from the Barrows Combat Minigame. ',
'Can be received as a drop from the Abyssal Sire Boss. The Unsired drop itself does NOT count for the task. ',
'Can be received as a drop from the Abyssal Sire Boss. The Unsired drop itself does NOT count for the task. ',
'Can be received as a drop from the Abyssal Sire Boss. The Unsired drop itself does NOT count for the task. ',
'Can be received as a drop from Abyssal Demons. ',
'Received as drop from serveral monsters in the Mount Karuulm Dungeon.',
'Received as drop from serveral monsters in the Mount Karuulm Dungeon.',
'Received as drop from serveral monsters in the Mount Karuulm Dungeon.',
'Received as drop from serveral monsters in the Mount Karuulm Dungeon.',
'Received as drop from serveral monsters in the Mount Karuulm Dungeon.',
'Wildy boss uniques are: Dragon 2H, Dragon pickaxe, 3 voidwaker pieces, 3 rev weapon upgrades, 3 rings',
'Wildy boss uniques are: Dragon 2H, Dragon pickaxe, 3 voidwaker pieces, 3 rev weapon upgrades, 3 rings',
'Wildy boss uniques are: Dragon 2H, Dragon pickaxe, 3 voidwaker pieces, 3 rev weapon upgrades, 3 rings',
'Received as a drop from the Cerberus Boss. ',
'Received as a drop from the Cerberus Boss. ',
'Received as a drop from the Cerberus Boss. ',
'Received as a drop from the Chaos Fanatic.',
'Received as a drop from the Chaos Fanatic',
'Can be obtained rarley, from any Boss. Advised to go for the Chaos Elemental Pet as the drop rate is much lowered compared to the other bosses. ',
'Received as a drop from the Zamorak God Wards Dungeon Boss.',
'Received as a drop from the Zamorak God Wards Dungeon Boss.',
'Received as a drop from the Dagannoth Kings Bosses. ',
'Received as a drop from the Dagannoth Kings Bosses. ',
'Received as a drop from the Dagannoth Kings Bosses. ',
'Received as a drop from the Dagannoth Kings Bosses. ',
'Received as a drop from the Dagannoth Kings Bosses. ',
'Received as a drop from the Dagannoth Kings Bosses. ',
'Received as a drop from the Dagannoth Kings Bosses. ',
'Received as a drop from the Grotesque Guardians Bosses. ',
'Received as a drop from the Grotesque Guardians Bosses. ',
'Received as a drop from the Grotesque Guardians Bosses. ',
'Received as a drop from the Kalphite Queen Boss. Dragon 2H sword does count for the task, as it is apart of the Chaos Elemental task. ',
'Received as a drop from the Kalphite Queen Boss. Dragon 2H sword does count for the task, as it is apart of the Chaos Elemental task. ',
'Received as a drop from the King Black Dragon Boss. ',
'Received as a drop from the Kraken Boss. ',
'Received as a drop from the Kraken Boss.',
'Received as a drom from Cave Kraken. ',
'Received as a drop from the Scorpia Boss.',
'Received as a drop from the Scorpia Boss.',
'Received as a drop from the Vorkath Boss. ',
'Received as a drop from the Zulrah Boss. ',
'Received as a drop from the Zulrah Boss. ',
'Received as a drop from the Zulrah Boss. ',
'Received as a drop from the Zulrah Boss. ',
'Potential reward from beginner clues. Minotaurs baby. ',
'Potential reward from easy clues. Pick pocketing H.A.M members are a great way of getting the clues. ',
'Potential reward from easy clues. Pick pocketing H.A.M members are a great way of getting the clues. ',
'Potential reward from easy clues. Pick pocketing H.A.M members are a great way of getting the clues. ',
'Potential reward from easy clues. Pick pocketing H.A.M members are a great way of getting the clues. ',
'Potential reward from easy clues. Pick pocketing H.A.M members are a great way of getting the clues. ',
'Potential reward from medium clues. Ecletic impings are are fantasic source for them. Arceuss spell: Dark Lure is nice if you have it!',
'Potential reward from medium clues. Ecletic impings are are fantasic source for them. Arceuss spell: Dark Lure is nice if you have it!',
'Potential reward from medium clues. Ecletic impings are are fantasic source for them. Arceuss spell: Dark Lure is nice if you have it!',
'Potential reward from medium clues. Ecletic impings are are fantasic source for them. Arceuss spell: Dark Lure is nice if you have it!',
'Potential reward from medium clues. Ecletic impings are are fantasic source for them. Arceuss spell: Dark Lure is nice if you have it!',
'Potential reward from hard clues. Barrage/Burst Jellies if you have anicents. ',
'Potential reward from hard clues. Barrage/Burst Jellies if you have anicents. ',
'Potential reward from hard clues. Barrage/Burst Jellies if you have anicents.',
'Potential reward from hard clues. Barrage/Burst Jellies if you have anicents. ',
'Potential reward from hard clues. Barrage/Burst Jellies if you have anicents. ',
'Potential reward from hard clues. Barrage/Burst Jellies if you have anicents. ',
'Potential reward from hard clues. Barrage/Burst Jellies if you have anicents. ',
'Potential reward from elite clues. Elite clue rewards are not real. Jagex please fix. ',
'Potential reward from elite clues. Elite clue rewards are not real. Jagex please fix. ',
'Potential reward from elite clues. Elite clue rewards are not real. Jagex please fix. ',
'Potential reward from elite clues. Elite clue rewards are not real. Jagex please fix. ',
'Potential reward from elite clues. Elite clue rewards are not real. Jagex please fix. ',
'Can be purchased as a reward from the Castle Wars \"Combat Minigame\". The best way to do this is by using an alt account and join the games with both accounts. Castle Wars is F2P therefore, alt account does not needed to be a member. Enjoy your AFK time. ',
'Potential reward from the Gnome Restaurant minigame. Last one yay!',
'Can be purchased as a reward from the Mage Mage Training Arena minigame. ',
'Can be purchased as a reward from the Mage Mage Training Arena minigame. ',
'Can be purchased as a reward from the Castle Wars \"Combat Minigame\". The best way to do this is by using an alt account and join the games with both accounts. Castle Wars is F2P therefore, alt account does not needed to be a member. Enjoy your AFK time. ',
'Can be purchased as a reward from the Castle Wars \"Combat Minigame\". The best way to do this is by using an alt account and join the games with both accounts. Castle Wars is F2P therefore, alt account does not needed to be a member. Enjoy your AFK time. ',
'Can be purchased as a reward from the Castle Wars \"Combat Minigame\". The best way to do this is by using an alt account and join the games with both accounts. Castle Wars is F2P therefore, alt account does not needed to be a member. Enjoy your AFK time. ',
'Can be purchased as a reward from the Castle Wars \"Combat Minigame\". The best way to do this is by using an alt account and join the games with both accounts. Castle Wars is F2P therefore, alt account does not needed to be a member. Enjoy your AFK time. ',
'Can be purchased as a reward from the Pest Control Combat Minigame. Poggers elite void!',
'Can be purchased as a reward from the Pest Control Combat Minigame. Poggers elite void!',
'Can be purchased as a reward from the Trouble Brewing Minigame. This one time at Trouble Brewing...',
'Can be purchased as a reward from the Trouble Brewing Minigame. This one time at Trouble Brewing...',
'Can be purchased as a reward from the Trouble Brewing Minigame. This one time at Trouble Brewing...',
'Can be purchased as a reward from the Trouble Brewing Minigame. This one time at Trouble Brewing...',
'Can be purchased as a reward from the Trouble Brewing Minigame. This one time at Trouble Brewing...',
'Can be received from a drop from several monsters.',
'Can be received from a drop from several monsters.',
'Can be received from a drop from several monsters.',
'Can be received as a drop from Elder Chaos Druids. Last one yay!',
'Guarenteed from Chompy bird hunting. ',
'Can be received as a drop from Demonic Gorillas(Murder Monkeys)',
'Can be received as a drop from Demonic Gorillas(Murder Monkeys)',
'Can be received as a drop from Demonic Gorillas(Murder Monkeys)',
'Can be received as a drop from Demonic Gorillas(Murder Monkeys)',
'Can be received when searching remains in the Whirlpool Dungeon. Check out the Ancient Page guide on the FAQ page! I\'m not going to remember to link that page here I feel.',
'Can be received when searching remains in the Whirlpool Dungeon. Check out the Ancient Page guide on the FAQ page! I\'m not going to remember to link that page here I feel.',
'Can be received when searching remains in the Whirlpool Dungeon. Check out the Ancient Page guide on the FAQ page! I\'m not going to remember to link that page here I feel.',
'Can be received as a drop from Kurask. ',
'Can be received as a drop from Spiritual Mages. ',
'Can be received as a drop from Dark Beasts. ',
'Can be received as a drop from the Thermonuclear Smoke Devil Boss. ',
'Can be recevied as a drop from Tzhaar Kets in the inner section of Mor Ul Rek. Burst/Barraging them is the best method for obtaining. ',
'Can be recevied as a drop from Tzhaar Kets in the inner section of Mor Ul Rek. Burst/Barraging them is the best method for obtaining. ',
'Can be received as a drop rarely, from Lizardmen Shaman.',
'Can be received as a drop from the Pyramid Plunder Theiving Minigame. ',
'Can be received as a drop from Mithril Dragons.',
'Can be received as a drop from the RDT. Killing Goraks with a Ring of Wealth a decent method.',
'Can be purchased as a reward in the Mining Guild. Two pairs of gloves and some minierals, ok Jamflex. ',
'Complete all the diary tasks.',
'Complete all the diary tasks.',
'Complete all the diary tasks.',
'Complete all the diary tasks.',
'Complete all the diary tasks.',
'Complete all the diary tasks.',
'Complete all the diary tasks.',
'Complete all the diary tasks.',
'Complete all the diary tasks.',
'Complete all the diary tasks.',
'Complete all the diary tasks.',
'Complete all the diary tasks.',
'Can be received as a drop from the Bryophyta Boss. ',
'Can be received as a drop from the Sarachnis Boss. You can\'t make me go back to that hellish boss.',
'Can be received as a drop from the Gauntlet. Been there done that. ',
'Can be received as a drop from the Gauntlet. Anyone want some armour seeds?. ',
'Can be received as a drop whilst catching Crystal impings. ',
'Can be received as a drop whilst pick pocketing Elves in Prifddinas. ',
'Can be received as a drop from Basalisk Knights. ',
'Can be received as a drop from the RDT. Killing Goraks with a Ring of Wealth is a decent method.',
'Can be purchased as a reward from the Brimhaven Agility Arena.',
'Can be recevied as a drop / purchased from the Hallowed Sepulchre.',
'Can be recevied as a drop / purchased from the Hallowed Sepulchre.',
'Can be recevied as a drop / purchased from the Hallowed Sepulchre.',
'Can be recevied as a drop / purchased from the Hallowed Sepulchre.',
'Can be recevied as a drop / purchased from the Hallowed Sepulchre.',
'Can be recevied as a drop / purchased from the Hallowed Sepulchre.',
'Unlocked after many laps on the Ape Atoll Agility course. Only after completion of Monkey Madness II.',
'Unlocked after many laps on the Ape Atoll Agility course. Only after completion of Monkey Madness II.',
'Unlocked after many laps on the Ape Atoll Agility course. Only after completion of Monkey Madness II.',
'Can be purchased as a reward from the Mahogany Homes Minigame. ',
'Can be purchased as a reward from the Mahogany Homes Minigame.  ',
'Can be purchased as a reward from the Mahogany Homes Minigame.',
'Can be received as a drop whilst killing Vyrewatch Sentinels / Pick pocketing Vyre. Killing is pretty chill. ',
'Can be purchased as a reward from the Soul Wars Minigame. ',
'Potential reward from the Shades of Morton Minigame. ',
'Potential reward from the Shades of Morton Minigame. ',
'Can be purchased as a reward from the Last Man Standing PVP Minigame. ',
'Can be purchased as a reward from the Last Man Standing PVP Minigame. ',
'Can be purchased as a reward from the Last Man Standing PVP Minigame. ',
'Can be purchased as a reward from the Last Man Standing PVP Minigame. ',
'Can be purchased as a reward from the Brimhaven Agility Arena.',
'Can be purchased as a reward from the Volcanic Mine Minigame. ',
'Can be purchased as a reward from the Volcanic Mine Minigame. ',
'Can be purchased as a reward from the Volcanic Mine Minigame.',
'Can be received as a reward from the Tempoross Skilling Boss. ',
'Can be received as a reward from the Theatre of Blood Story/Entry Mode.',
'Can be received as a drop whilst opening the Grubby Chest in the Forthos Dungeon. ',
'Can be received as a drop whilst opening the Grubby Chest in the Forthos Dungeon. ',
'Can be received as a drop whilst killing Ancient Creatures in the God Wars Dungeon. ',
'Can be received as a drop whilst killing Ancient Creatures in the God Wars Dungeon. ',
'Can be received as a drop whilst killing Ancient Creatures in the God Wars Dungeon. ',
'Can be received as a drop whilst killing Ancient Creatures in the God Wars Dungeon. ',
'Can be received as a drop whilst killing Ancient Creatures in the God Wars Dungeon. ',
'Can be received as a drop whilst killing Ancient Creatures in the God Wars Dungeon. ',
'Can be received as a reward from the Guardians of the Rift Skilling Minigame. Runecrafting... it\'s actually kinda fun now.',
'Can be received as a reward from the Guardians of the Rift Skilling Minigame. Runecrafting... it\'s actually kinda fun now.',
'Can be received as a reward from the Guardians of the Rift Skilling Minigame. Runecrafting... it\'s actually kinda fun now.',
'Can be received as a reward from the Guardians of the Rift Skilling Minigame. Runecrafting... it\'s actually kinda fun now.',
"Can be purchased as a reward from the Giants' Foundry Skilling Minigame.",
"Can be received as a reqard from the Tombs of Amascut Raid",
"Can be received as a reqard from the Tombs of Amascut Raid",
"Can be received a drop from Phantom Muspah Boss",
"Can be received a drop from Phantom Muspah Boss",
'Can be purchased as a reward from the Friendly Forester',
'Can be purchased as a reward from the Friendly Forester',
'Can be purchased as a reward from the Friendly Forester',
'Received as a drop from Moons of Peril bosses',
'Received as a drop from Moons of Peril bosses',
'Received as a drop from Moons of Peril bosses',
'Received as a drop from Moons of Peril bosses',
'Received as a drop from Moons of Peril bosses',
'Received as a drop from Moons of Peril bosses',
'Received as a drop when completing Hunters Rumours',
'Received as a drop when completing Hunters Rumours',
'Received as a drop when completing Hunters Rumours',
'Reward from Fortis Colosseum or from hunting Sunfire Antelope'
]


elite_tips = [
'Can be received as a reward from the Barrows Combat Minigame. ',
'Can be received as a reward from the Barrows Combat Minigame. ',
'Can be received as a reward from the Barrows Combat Minigame. ',
'Can be received as a reward from the Barrows Combat Minigame. ',
'Can be received as a drop from the Abyssal Sire Boss. ',
'Can be received as a drop from the Abyssal Sire Boss. ',
'Received as drop from serveral monsters in the Mount Karuulm Dungeon.',
'Received as drop from serveral monsters in the Mount Karuulm Dungeon.',
'Received as drop from serveral monsters in the Mount Karuulm Dungeon.',
'Received as drop from serveral monsters in the Mount Karuulm Dungeon.',
'Received as drop from serveral monsters in the Mount Karuulm Dungeon.',
'Received as drop from serveral monsters in the Mount Karuulm Dungeon.',
'Received as drop from serveral monsters in the Mount Karuulm Dungeon.',
'Received as drop from serveral monsters in the Mount Karuulm Dungeon.',
'Received as a drop from the Cerberus Boss. ',
'Received as a drop from the Cerberus Boss. ',
'Can be received as a drop from the God Wars Dungeon Bosses. ',
'Can be received as a drop from the God Wars Dungeon Bosses. ',
'Can be received as a drop from the God Wars Dungeon Bosses. ',
'Can be received as a drop from the God Wars Dungeon Bosses. ',
'Can be received as a drop from the God Wars Dungeon Bosses. ',
'Can be received as a drop from the God Wars Dungeon Bosses. ',
'Can be received as a drop from the God Wars Dungeon Bosses. ',
'Can be received as a drop from the God Wars Dungeon Bosses. ',
'Can be received as a drop from the God Wars Dungeon Bosses. ',
'Can be received as a drop from the God Wars Dungeon Bosses. ',
'Can be received as a drop from the God Wars Dungeon Bosses. ',
'Can be received as a drop from the God Wars Dungeon Bosses. ',
'Can be received as a drop from the God Wars Dungeon Bosses. ',
'Can be received as a drop from the God Wars Dungeon Bosses. ',
'Can be received as a drop from the God Wars Dungeon Bosses. ',
'Can be received as a drop from the God Wars Dungeon Bosses. ',
'Can be received as a drop from the Corporeal Beast Boss. ',
'Can be received as a drop from the Corporeal Beast Boss. ',
'Can be obtained rarley, from any Boss. Advised to go for the Chaos Elemental Pet as the drop rate is much lowered compared to the other bosses. ',
'Can be obtained rarley, from any Boss. Advised to go for the Chaos Elemental Pet as the drop rate is much lowered compared to the other bosses. ',
'Can be obtained rarley, from any Boss. Advised to go for the Chaos Elemental Pet as the drop rate is much lowered compared to the other bosses. ',
'Can be received as a drop from the Thermonuclear Smoke Devil Boss. ',
'Wildy boss uniques are: Dragon 2H, Dragon pickaxe, 3 voidwaker pieces, 3 rev weapon upgrades, 3 rings',
'Wildy boss uniques are: Dragon 2H, Dragon pickaxe, 3 voidwaker pieces, 3 rev weapon upgrades, 3 rings',
'Wildy boss uniques are: Dragon 2H, Dragon pickaxe, 3 voidwaker pieces, 3 rev weapon upgrades, 3 rings',
'Wildy boss uniques are: Dragon 2H, Dragon pickaxe, 3 voidwaker pieces, 3 rev weapon upgrades, 3 rings',
'Received as a drop from the Grotesque Guardians Bosses. ',
'Can be received as a drop from Raids. Chambers of Xerics or Theatre of Blood or Tombs of Amascut. ',
'Can be received as a drop from Raids. Chambers of Xerics or Theatre of Blood or Tombs of Amascut. ',
'Can be received as a drop from Raids. Chambers of Xerics or Theatre of Blood or Tombs of Amascut. ',
'Can be received as a drop from Raids. Chambers of Xerics or Theatre of Blood or Tombs of Amascut. ',
'Can be received as a drop from Raids. Chambers of Xerics or Theatre of Blood or Tombs of Amascut. ',
'Can be received as a drop from Raids. Chambers of Xerics or Theatre of Blood or Tombs of Amascut. ',
'Can be received as a drop from Raids. Chambers of Xerics or Theatre of Blood or Tombs of Amascut. ',
'Can be received as a drop from Raids. Chambers of Xerics or Theatre of Blood or Tombs of Amascut. ',
'Can be received as a drop from Raids. Chambers of Xerics or Theatre of Blood or Tombs of Amascut. ',
'Can be received as a drop from Raids. Chambers of Xerics or Theatre of Blood or Tombs of Amascut. ',
'Can be received as a drop from Raids. Chambers of Xerics or Theatre of Blood or Tombs of Amascut. ',
'Can be received as a drop from Raids. Chambers of Xerics or Theatre of Blood or Tombs of Amascut. ',
'Can be received as a drop from Raids. Chambers of Xerics or Theatre of Blood or Tombs of Amascut. ',
'Can be received as a drop from Raids. Chambers of Xerics or Theatre of Blood or Tombs of Amascut. ',
'Potential reward from easy clues. Pick pocketing H.A.M members are a great way of getting the clues. ',
'Potential reward from easy clues. Pick pocketing H.A.M members are a great way of getting the clues. ',
'Potential reward from easy clues. Pick pocketing H.A.M members are a great way of getting the clues. ',
'Potential reward from easy clues. Pick pocketing H.A.M members are a great way of getting the clues. ',
'Potential reward from easy clues. Pick pocketing H.A.M members are a great way of getting the clues. ',
'Potential reward from medium clues. Ecletic impings are are fantasic source for them.',
'Potential reward from medium clues. Ecletic impings are are fantasic source for them.',
'Potential reward from medium clues. Ecletic impings are are fantasic source for them.',
'Potential reward from medium clues. Ecletic impings are are fantasic source for them.',
'Potential reward from medium clues. Ecletic impings are are fantasic source for them.',
'Potential reward from hard clues.',
'Potential reward from hard clues.',
'Potential reward from hard clues. ',
'Potential reward from hard clues.',
'Potential reward from hard clues.',
'Potential reward from hard clues.',
'Potential reward from hard clues.',
'Potential reward from hard clues.',
'Potential reward from elite clues. Elite clue rewards are not real. Jagex please fix. ',
'Potential reward from elite clues. Elite clue rewards are not real. Jagex please fix. ',
'Potential reward from elite clues. Elite clue rewards are not real. Jagex please fix. ',
'Potential reward from elite clues. Elite clue rewards are not real. Jagex please fix. ',
'Potential reward from elite clues. Elite clue rewards are not real. Jagex please fix. ',
'Potential reward from elite clues. Elite clue rewards are not real. Jagex please fix. ',
'Potential reward from elite clues. Elite clue rewards are not real. Jagex please fix. ',
'Potential reward from elite clues. Elite clue rewards are not real. Jagex please fix. ',
'Potential reward from elite clues. Elite clue rewards are not real. Jagex please fix. ',
'Potential reward from elite clues. Elite clue rewards are not real. Jagex please fix. ',
'Potential reward from master clues. ',
'Potential reward from master clues. ',
'Potential reward from master clues. ',
'Potential reward from master clues. ',
'Potential reward from master clues. ',
'Potential reward from master clues. ',
'Potential reward from master clues. ',
'Potential reward from master clues. ',
'Potential reward from master clues. ',
'Potential reward from master clues. ',
'Potential reward from master clues. ',
'Potential reward from master clues. ',
'Can be purchased as a reward from the Castle Wars \"Combat Minigame\".',
'Can be purchased as a reward from the Castle Wars \"Combat Minigame\".',
'Can be purchased as a reward from the Castle Wars \"Combat Minigame\".',
'Can be purchased as a reward from the Castle Wars \"Combat Minigame\".',
'Can be purchased as a reward from the Trouble Brewing Minigame.',
'Can be purchased as a reward from the Trouble Brewing Minigame.',
'Can be purchased as a reward from the Trouble Brewing Minigame.',
'Can be purchased as a reward from the Trouble Brewing Minigame.',
'Received as a drop from Chompy bird hunting after completeling the Western Provinces Elite Diary. ',
'Can be received from a drop from several monsters.',
'Can be received from a drop from several monsters.',
'Can be received from a drop from several monsters.',
'Can be received from a drop from several monsters.',
'Guarenteed reward from Chompy bird hunting. The first time you receive this task, you must get the Dragon Archer Hat. Second time get the Expert Dragon Archer Hat. ',
'Guarenteed reward from Chompy bird hunting. The first time you receive this task, you must get the Dragon Archer Hat. Second time get the Expert Dragon Archer Hat. ',
'Can be received as a drop from Demonic Gorillas(Murder Monkeys)',
'Can be received as a drop from Demonic Gorillas(Murder Monkeys)',
'Can be received when searching remains in the Whirlpool Dungeon. Check out the Ancient Page guide on the FAQ page! I\'m not going to remember to link that page here I feel.',
'Can be received when searching remains in the Whirlpool Dungeon. Check out the Ancient Page guide on the FAQ page! I\'m not going to remember to link that page here I feel.',
'Received as a drop from Superior Slayer Creatures. ',
'Received as a drop from Superior Slayer Creatures. ',
'Can be recevied as a drop from Tzhaar Kets in the inner section of Mor Ul Rek.',
'Received as a drop from Toktz-mej. ',
'Received as a drop from Rune/Adamant dragons. ',
'Complete all the diary tasks.',
'Complete all the diary tasks.',
'Complete all the diary tasks.',
'Complete all the diary tasks.',
'Complete all the diary tasks.',
'Complete all the diary tasks.',
'Complete all the diary tasks.',
'Complete all the diary tasks.',
'Complete all the diary tasks.',
'Complete all the diary tasks.',
'Complete all the diary tasks.',
'Complete all the diary tasks.',
'Guarenteed drop from the Rabbit in Prifddinas.',
'Can be purchased as a reward from Aerial Fishing hunter method. Giga RSI. ',
'Can be received as a drop from the Larrens Chest. ',
'Can be received as a drop from the Larrens Chest. ',
'Can be recevied as a drop / purchased from the Hallowed Sepulchre.',
'Can be recevied as a drop / purchased from the Hallowed Sepulchre.',
'Can be recevied as a drop / purchased from the Hallowed Sepulchre.',
'Can be received as a drop from Fossil Island Wyverns. ',
'Can be purchased as a reward from the Mahogany Homes Minigame.',
'Potential reward from the Shades of Morton Minigame. ',
'Potential reward from the Shades of Morton Minigame. ',
'Potential reward from the Shades of Morton Minigame. ',
'Potential reward from the Shades of Morton Minigame. ',
'Potential reward from the Shades of Morton Minigame. ',
'Potential reward from the Shades of Morton Minigame. ',
'Potential reward from the Shades of Morton Minigame. ',
'Can be purchased as a reward from the Last Man Standing PVP Minigame. ',
'Can be purchased as a reward from the Last Man Standing PVP Minigame. ',
'Can be purchased as a reward from the Last Man Standing PVP Minigame. ',
'Can be purchased as a reward from the Last Man Standing PVP Minigame. ',
'Can be purchased as a reward from the Volcanic Mine Minigame.',
'Can be received as a drop from any Revenant.',
'Can be received as a drop from any Revenant.',
'Can be received as a drop from any Revenant.',
'Can be received as a drop from any Revenant.',
'Can be received as a reward from the Guardians of the Rift Skilling Minigame.',
'Can be received as a reward from the Guardians of the Rift Skilling Minigame.',
'Can be received as a reward from the Guardians of the Rift Skilling Minigame.',
"Can be received a drop from Phantom Muspah Boss",
"Can be received a drop from Phantom Muspah Boss",
'Can be purchased as a reward from the Friendly Forester',
'Can be purchased as a reward from the Friendly Forester',
'Can be purchased as a reward from the Friendly Forester',
'Can be purchased as a reward from the Friendly Forester',
'Can be purchased as a reward from the Friendly Forester',
'Can be purchased as a reward from the Friendly Forester',
'Can be received as drop from any of the four DT2 bosses',
'Can be received as drop from any of the four DT2 bosses',
'Can be received as drop from any of the four DT2 bosses',
'Can be received as drop from any of the four DT2 bosses',
'Can be received as drop from any of the four DT2 bosses',
'Can be received as drop from any of the four DT2 bosses',
'Can be received as drop from any of the four DT2 bosses',
'Can be received as drop from any of the four DT2 bosses',
'Can be received as drop from any of the four DT2 bosses',
'Can be received as drop from any of the four DT2 bosses',
'Can be received as drop from any of the four DT2 bosses',
'Received as a drop from Moons of Peril bosses',
'Received as a drop from Moons of Peril bosses',
'Received as a drop from Moons of Peril bosses'
]